<dl class="sp-methods" id="checkout-payment-method-load">

<?php $methods = $this->getPaymentMethodsFilter(); ?>
<?php $oneMethod = count($methods) <= 1; ?>
<?php if (empty ($methods)): ?>
    <dt>
        <?php echo $this->__('No Payment Methods'); ?>
    </dt>
<?php else: ?>
    <?php $paymentHide = array(); ?>
    <?php foreach ($methods as $_method): ?>
        <?php $_code = $_method['code']; ?>
        <?php $_title = $_method['title']; ?>
        <?php if (in_array($_code, $paymentHide)): ?>
            <?php continue; ?>
        <?php endif; ?>
        <dt>
            <?php if (!$oneMethod): ?>
                <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_title) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
            <?php else: ?>
                <span class="no-display">
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" />
                </span>
                <?php $oneMethod = $_code; ?>
            <?php endif; ?>
            <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($_title) ?> <?php echo $this->getMethodLabelAfterHtmlExtend($_code) ?></label>
        </dt>
    
        <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
            <dd>
                <?php echo $html; ?>
            </dd>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
</dl>
    
<?php echo $this->getChildChildHtml('additional'); ?>

<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
    <?php if (is_string($oneMethod)): ?>
        payment.switchMethod('<?php echo $oneMethod ?>');
    <?php endif; ?>
    //]]>
</script>
