<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Islider
 * @version    1.3.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<?php $_helper = Mage::helper('megamenu'); ?>
<?php $_currentCategory = $_helper->getUrlKey($_helper->getCurrentMainCategory()); ?>
<?php if ($_currentCategory == 'baby'): ?>
    <script type="text/javascript">
        $j(function() {
          $j('body.style-baby #slides-banner').slidesjs({
            width: 750,
            height: 333,
            pagination: {
              active: true,
                // [string] Can be either "slide" or "fade".
            },
             play: {
                 auto: true,
                 interval: 5000,
             },
              effect: {
                  slide: {
                        speed : 2000
                        }
                  }
          });
        });
    </script>
    <?php $helper = Mage::helper('awislider') ?>
    <?php if($this->canDisplay() && $this->getSlides()->getSize()) : ?>
    <div id="slides-banner">
      <?php $_i = 0 ?>
        <?php foreach($this->getSlides() as $slide) : ?>
            <?php if($slide->getData('url')) : ?>
            <a href="<?php echo $helper->getUseDirectLinks() ? $slide->getData('url') : $this->getUrl('awislider/link/out', array('sid' => $slide->getData('id'))) ?>"<?php if($slide->getData('new_window')) : ?> onclick="return !window.open(this.href)"<?php endif ?><?php if($slide->getData('nofollow')) : ?> rel="nofollow"<?php endif ?>>
            <?php endif ?>
                <img src="<?php echo ($slide->getUriLocation()) ?>" title="<?php echo htmlspecialchars($slide->getData('title')) ?>" alt="<?php echo htmlspecialchars($slide->getData('title')) ?>"/>
            <?php if($slide->getData('url')) : ?>
            </a>
            <?php endif ?>
        <?php $_i++ ?>
        <?php endforeach ?>
        
    </div>
    <?php endif ?>
<?php elseif ($_currentCategory == 'perlengkapan-rumah'): ?>
    <script type="text/javascript">
        $j(function() {
          $j('body.style-perlengkapan-rumah #slides-banner-home').slidesjs({
            width: 523,
            height: 383,
            pagination: {
              active: true,
                // [string] Can be either "slide" or "fade".
            },
             play: {
                 auto: true,
                 interval: 5000,
             },
              effect: {
                  slide: {
                        speed : 2000
                        }
                  }
          });
        });
    </script>
    <?php $helper = Mage::helper('awislider') ?>
    <?php if($this->canDisplay() && $this->getSlides()->getSize()) : ?>
    <div id="slides-banner-home">
      <?php $_i = 0 ?>
        <?php foreach($this->getSlides() as $slide) : ?>
            <?php if($slide->getData('url')) : ?>
            <a href="<?php echo $helper->getUseDirectLinks() ? $slide->getData('url') : $this->getUrl('awislider/link/out', array('sid' => $slide->getData('id'))) ?>"<?php if($slide->getData('new_window')) : ?> onclick="return !window.open(this.href)"<?php endif ?><?php if($slide->getData('nofollow')) : ?> rel="nofollow"<?php endif ?>>
            <?php endif ?>
                <img src="<?php echo ($slide->getUriLocation()) ?>" title="<?php echo htmlspecialchars($slide->getData('title')) ?>" alt="<?php echo htmlspecialchars($slide->getData('title')) ?>" />
            <?php if($slide->getData('url')) : ?>
            </a>
            <?php endif ?>
        <?php $_i++ ?>
        <?php endforeach ?>
        
    </div>
    <?php endif ?>
<?php else: ?>
    <script type="text/javascript">
        $j(function() {
          $j('#slides-banner').slidesjs({
            width: 759,
            height: 338,
            pagination: {
              active: true,
                // [string] Can be either "slide" or "fade".
            },
             play: {
                 auto: true,
                 interval: 5000,
             },
              effect: {
                  slide: {
                        speed : 2000
                        }
                  }
          });
        });
    </script>
    <?php $helper = Mage::helper('awislider') ?>
    <?php if($this->canDisplay() && $this->getSlides()->getSize()) : ?>
        <div id="slides-banner">
          <?php $_i = 0 ?>
            <?php foreach($this->getSlides() as $slide) : ?>
                <?php if($slide->getData('url')) : ?>
                <a href="<?php echo $helper->getUseDirectLinks() ? $slide->getData('url') : $this->getUrl('awislider/link/out', array('sid' => $slide->getData('id'))) ?>"<?php if($slide->getData('new_window')) : ?> onclick="return !window.open(this.href)"<?php endif ?><?php if($slide->getData('nofollow')) : ?> rel="nofollow"<?php endif ?>>
                <?php endif ?>
                    <img src="<?php echo ($slide->getUriLocation()) ?>" title="<?php echo htmlspecialchars($slide->getData('title')) ?>" alt="<?php echo htmlspecialchars($slide->getData('title')) ?>" />
                <?php if($slide->getData('url')) : ?>
                </a>
                <?php endif ?>
            <?php $_i++ ?>
            <?php endforeach ?>
            
        </div>
    <?php endif; ?>
<?php endif; ?>
