<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Featured
 * @version    3.5.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if($this->canDisplay() && $this->getProductsCollection()->getSize() && !$this->getIsEmpty()) : ?>
<?php $_helper = $this->helper('catalog/output') ?>
<?php $_escape_helper = Mage::helper('catalog/utils'); ?>
<?php $_imageQsize = 152 // Maximal image width\height value, pixels ?>
<?php $_onSaleHelper = $this->helper('awfeatured/onsale') ?>
<?php $_abstractBlock = $this->helper('awfeatured')->getAbstractProductBlock() ?>
<?php $_cart = Mage::getModel('checkout/cart')->getQuote(); ?>
<?php $_items = $_cart->getAllItems(); ?>
<?php $itemQty = 0; ?>
<?php foreach ($_items as $_item) { $parentId = $_item->getParentItemId(); if(empty($parentId)) {$itemQty++;} } ?>
<div class="awfeatured awafpgrid" id="<?php echo $this->getUniqueBlockId() ?>" style="<?php echo $this->getContainerStyleString() ?>">
    <?php $_i = $_ulOpened = $_ulClosed = 0; ?>
    <?php $_iterates=0;foreach($this->getProductsCollection() as $_product) : ?>
        <?php $sku[] = $_product->getSku(); ?>
        <?php $productName[] = $_product->getName(); ?>
        <?php $productPrice[] = $_product->getPrice(); ?>
        <?php $skuCollection = array(); ?>
        <?php if($_i % $this->getItemsPerRow() == 0) : ?>
        <?php $_ulOpened++ ?>
        <ul class="products-grid">
        <!-- row begins -->
        <?php endif ?>
        <?php
            $skuCollection[] = $_product->getId();
        ?>
            <li class="item" style="width: <?php echo $this->getItemWidth() ?>%">
				<div class="top_thumb_list_product">
                    <a alt="<?php echo $this->__('tambah ke koleksi') ?>" href="javascript:;" class="link-wishlist addToCollectionLink" onclick="showAddToCollectionDialog()" data-brand-name="<?php echo $_product->getAttributeText('brand'); ?>" data-image="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(320 , 320); ?>" data-product-name="<?php echo $this->stripTags($_product->getName(), null, true); ?>" data-price="<?php echo 'Rp ' . number_format(round($_product->getFinalPrice()), 0, '', '.'); ?>" data-id="<?php echo $_product->getId(); ?>"><i class="fa fa-heart"></i>
                    <span class="poper poper<?php echo $_iterates; ?>"> </span>
                    <span class="check-to-clicking check-to-clicking<?php echo $_iterates;?>">tambah ke koleksi</span></a>
                    <style>
                        .pop-it<?php echo $_iterates;?>
                        {
                          opacity: 1 !important;
                        }
                    </style>
                    <script language="javascript">

                     $j(document).ready(function() {

                      $j(".poper<?php echo $_iterates;?>").on ('mouseover', function(){
                          $j(".check-to-clicking<?php echo $_iterates;?>").addClass('pop-it<?php echo $_iterates;?>');
                        });
                      $j(".poper<?php echo $_iterates;?>").on ('mouseout', function(){
                          $j(".check-to-clicking<?php echo $_iterates;?>").removeClass('pop-it<?php echo $_iterates;?>');
                        });

                      });
                      </script>
                <!-- product item begin -->
                <?php $_imageSrc = Mage::helper('awfeatured/images')->getProductImage($_product, $_product->getData('image_id'))->resize(152,152) ?>
                <?php if($_imageSrc) : ?>
                <div class="afp-thumbnail">
                    <?php if($_onSaleHelper->isOnsale()) echo $_onSaleHelper->startOnsale($_product, $_imageQsize) ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_abstractBlock->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" onclick="ecommerceStaticBlockProductClick('<?php echo $_escape_helper->escapeQuote($_product->getName()) ?>','<?php echo $_product->getSku() ?>','<?php echo $_product->getPrice() ?>','<?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?>','browsing');">
                        <img class="lazy" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(152); ?>" alt="<?php echo $this->stripTags($_abstractBlock->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <span class="loader"><img class="loader-img" src="<?php echo $this->getSkinUrl('images/loading.gif') ?>"></span>
                    </a>
                    <?php if($_onSaleHelper->isOnsale()) echo $_onSaleHelper->endOnsale() ?>
                </div>
                <?php endif ?>
                </div>
				<div class="product-info-wrapper">
                <?php if($this->getShowProductName()) : ?>
                <div class="awafptitle">
                	<?php // NEW label placement
					$now = date("Y-m-d");
					$newsFrom= substr($_product->getData('news_from_date'),0,10);
					$newsTo=  substr($_product->getData('news_to_date'),0,10);
					if ($now>=$newsFrom && $now<=$newsTo):?>
						<span class="lbl-newproduct"><?php echo $this->__('New!') ?></span>
					<?php endif; ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" onclick="ecommerceStaticBlockProductClick('<?php echo $_escape_helper->escapeQuote($_product->getName()) ?>','<?php echo $_product->getSku(); ?>','<?php echo $_product->getPrice() ?>','<?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?>','browsing');"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                </div>
                <?php endif ?>
                <?php if($this->getShowDetails()) : ?>
                <div class="afp-details">
                    <?php echo $this->getDetailsFromProduct($_product) ?>
                </div>
                <?php endif ?>
                <?php if($this->getShowPrice()) : ?>
                <?php echo $_abstractBlock->getPriceHtml($_product, true) ?>
                <?php endif ?>
                
                <?php if ($this->getShowRating()):?>
                <div class="ratings">
                    <?php if ($_product->getRatingSummary()):?>
                    <div class="rating-box">
                        <div class="rating" style="width:<?php echo $_product->getRatingSummary() ?>%"></div>
                    </div>
                    <span class="amount">
                        <?php if($_product->getReviewsCount()>1):?>
                        <a href="#" onclick="ecommerceStaticBlockProductClick('<?php echo $_escape_helper->escapeQuote($_product->getName()) ?>','<?php echo $_product->getSku(); ?>','<?php echo $_product->getPrice() ?>','<?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?>','browsing'); var t = opener ? opener.window : window; t.location.href='<?php echo $this->getReviewsUrl($_product) ?>'; return false;"><?php echo $this->__('%d Reviews', $_product->getReviewsCount()) ?></a>
                        <?php else:?>
                            <a href="#" onclick="ecommerceStaticBlockProductClick('<?php echo $_escape_helper->escapeQuote($_product->getName()) ?>','<?php echo $_product->getSku(); ?>','<?php echo $_product->getPrice() ?>','<?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?>','browsing'); var t = opener ? opener.window : window; t.location.href='<?php echo $this->getReviewsUrl($_product) ?>'; return false;"><?php echo $this->__('%d Review', $_product->getReviewsCount()) ?></a>
                        <?php endif?>
                    </span>
                    <?php endif;?>
                </div>
                <?php endif;?>
                <!-- product item end -->
				</div>
                <?php if($this->getShowAddToCartButton()) : ?>
                <div class="afp-addtocart">
                    <?php if($_product->isSaleable()) : ?>
                    <?php if($_product->getTypeId() != 'simple'):?>
                        <p><a class="link-cart-special" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><i class="fa fa-cart-plus"></i><?php echo $this->__('Tambah ke troli') ?></a></p>
                        <?php else:?>
						<p><button type="button" title="<?php echo $this->__('Tambah ke troli') ?>" class="button btn-buynow" onclick="setLocation('<?php echo $_abstractBlock->getAddToCartUrl($_product) ?>'); ecommerceStaticBlockAddToCart('<?php echo $_escape_helper->escapeQuote($_product->getName()); ?>','<?php echo $_product->getSku(); ?>','<?php echo $_product->getPrice() ?>','<?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?>','browsing','<?php echo $_product->getProductUrl() ?>','<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(152); ?>');"><i class="fa fa-cart-plus"></i><?php echo $this->__('Tambah ke troli') ?></button></p>
						<?php endif;?>
						<?php else : ?>
						<p class="availability out-of-stock"><span><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->__('Kabari bila tersedia') ?></a></span></p>
						<?php endif ?>
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Buy Later') ?></a>
						<?php endif; ?>
					</div>
                <?php endif ?>
            </li>
        <?php if(($_i+1) % $this->getItemsPerRow() == 0) : ?>
        <?php $_ulClosed++ ?>
        <!-- row ends -->
        </ul>
        <?php endif ?>
    <?php $_i++ ?>
    <?php endforeach; ?>
    <?php $randSku = array_rand($skuCollection); ?>
    <?php Mage::getSingleton('core/session')->setDRPageType('home'); ?>
    <?php Mage::getSingleton('core/session')->setDRProdId($skuCollection[$randSku]); ?>
    <?php if($_ulOpened != $_ulClosed) : ?>
        </ul>
    <?php endif ?>

    <?php
    $category = '';
    $dataForUA = array();
    foreach($sku as $key=>$rowSKU) {
        $dataForUA[] = array(
            'id' => $rowSKU,
            'name' => $productName[$key],
            'price' => number_format($productPrice[$key], 0, '', ''),
            'category' => (!empty($category)) ? $category : 'Default Category',
            'position' => $key+1
        );
    }
    ?>
</div>
<script type="text/javascript">
    var afpGrid<?php echo $this->getUniqueBlockId() ?> = new afpGrid({
        blockId: '<?php echo $this->getUniqueBlockId() ?>'
    });
</script>
<?php endif ?>

<script type="text/javascript">
    jQuery(document).ready(function(){
        var list_name, parent_list, li_list, li_browse_list, parent_browse_list, button_buynow, onclick_buynow, button_product, onclick_product, itr, itr_product = "";
        var array_list = new Array();
        parent_list = jQuery('.awfeatured.awafpgrid').parent().first().attr("class");
        parent_browse_list = parent_list.replace(" ",".");
        li_list = jQuery('div.'+ parent_list +' div.awfeatured.awafpgrid ul li');
        li_browse_list = jQuery('div.'+ parent_browse_list +' div.awfeatured.awafpgrid ul li');
        button_buynow = jQuery("button.button.btn-buynow");
        if (li_list.length > 0) {       // impression for static block in category page
            if (!(jQuery('.awfeatured.awafpgrid').parent().eq(0).attr('data-universal-analytics'))) {
                jQuery('.awfeatured.awafpgrid').parent().eq(0).attr('data-universal-analytics', 'ok');
                button_buynow = jQuery('div.product-mostpopular button.button.btn-buynow');
                button_product = jQuery('div.product-mostpopular a');
                list_name = "product-mostpopular";
                for (itr = 0 ; itr <= button_buynow.length-1 ; itr++) {     // add to cart
                    onclick_buynow = button_buynow.eq(itr).attr('onclick').replace("browsing",list_name);
                    jQuery('div.product-mostpopular .button.btn-buynow').eq(itr).attr('onclick',onclick_buynow);
                }
                for (itr_product = 0 ; itr_product <= button_product.length-1 ; itr_product++) {        // product click
                    if (button_product.eq(itr_product).attr('onclick')) {
                        onclick_product = button_product.eq(itr_product).attr('onclick').replace("browsing",list_name);
                        jQuery('div.product-mostpopular a').eq(itr_product).attr('onclick',onclick_product);
                    }
                }
            }
            else if (!(jQuery('.awfeatured.awafpgrid').parent().eq(1).attr('data-universal-analytics'))) {
                jQuery('.awfeatured.awafpgrid').parent().eq(1).attr('data-universal-analytics', 'ok');
                list_name = "product-new";
                parent_list = "product-new";
                li_list = jQuery('div.'+ parent_list +' div.awfeatured.awafpgrid ul li');
                button_buynow = jQuery('div.product-new button.button.btn-buynow');
                button_product = jQuery('div.product-new a');
                for (itr = 0 ; itr <= button_buynow.length-1 ; itr++) {     // add to cart
                    onclick_buynow = button_buynow.eq(itr).attr('onclick').replace("browsing",list_name);
                    jQuery('div.product-new .button.btn-buynow').eq(itr).attr('onclick',onclick_buynow);
                }
                for (itr_product = 0 ; itr_product <= button_product.length-1 ; itr_product++) {        // product click
                    if (button_product.eq(itr_product).attr('onclick')) {
                        onclick_product = button_product.eq(itr_product).attr('onclick').replace("browsing",list_name);
                        jQuery('div.product-new a').eq(itr_product).attr('onclick',onclick_product);
                    }
                }
            }
            else if (!(jQuery('.awfeatured.awafpgrid').parent().eq(2).attr('data-universal-analytics'))) {
                jQuery('.awfeatured.awafpgrid').parent().eq(2).attr('data-universal-analytics', 'ok');
                list_name = "product-onsale";
                parent_list = "product-onsale";
                li_list = jQuery('div.'+ parent_list +' div.awfeatured.awafpgrid ul li');
                button_buynow = jQuery('div.product-onsale button.button.btn-buynow');
                button_product = jQuery('div.product-onsale a');
                for (itr = 0 ; itr <= button_buynow.length-1 ; itr++) {     // add to cart
                    onclick_buynow = button_buynow.eq(itr).attr('onclick').replace("browsing",list_name);
                    jQuery('div.product-onsale .button.btn-buynow').eq(itr).attr('onclick',onclick_buynow);
                }
                for (itr_product = 0 ; itr_product <= button_product.length-1 ; itr_product++) {        // product click
                    if (button_product.eq(itr_product).attr('onclick')) {
                        onclick_product = button_product.eq(itr_product).attr('onclick').replace("browsing",list_name);
                        jQuery('div.product-onsale a').eq(itr_product).attr('onclick',onclick_product);
                    }
                }
            }

            if (typeof staticblockDataLayer == "undefined") {
                staticblockDataLayer = new Array();
            }
            <?php $total = count($dataForUA); ?>
            staticblockDataLayer.push(
                <?php foreach($dataForUA as $key=>$rowDataForUA): ?>
                    <?php echo '{"id":"'.$rowDataForUA['id'].'", "name":"'.$_escape_helper->escapeQuote($rowDataForUA['name']).'", "price":'.$rowDataForUA['price'].', "category":"Default Category", "position":'.$rowDataForUA['position'].', "list":';?>list_name <?php echo '}'; ?>
                    <?php if(($key+1) < $total) {
                        echo ",";
                    } ?>
                <?php endforeach; ?>
            );
            if ((jQuery('.awfeatured.awafpgrid').parent().eq(2).attr('data-universal-analytics')) == "ok") {
                var ecommerceData = {
                "ecommerce" :
                {
                    "impressions" : staticblockDataLayer,
                    "currencyCode":"IDR"
                },
                'event': 'impression',
                'eventCategory':'ecommerce',
                'eventAction':'impression'
                };
                dataLayer.push(ecommerceData);
            }  
        }
        else if (li_browse_list.length > 0) {       // impression for static block in homepage
            if (!(jQuery('.awfeatured.awafpgrid').parent().eq(0).attr('data-universal-analytics'))) {
                jQuery('.awfeatured.awafpgrid').parent().eq(0).attr('data-universal-analytics', 'ok');
            }
            else if (!(jQuery('.awfeatured.awafpgrid').parent().eq(1).attr('data-universal-analytics'))) {
                jQuery('.awfeatured.awafpgrid').parent().eq(1).attr('data-universal-analytics', 'ok');
                parent_browse_list = "featured-product.rekomendasi";
                li_browse_list = jQuery('div.'+ parent_browse_list +' div.awfeatured.awafpgrid ul li');
            }

            if (typeof objDataLayer == "undefined") {
                objDataLayer = new Array();
                <?php $total = count($dataForUA); ?>
                objDataLayer.push(
                    <?php foreach($dataForUA as $key=>$rowDataForUA): ?>
                        <?php echo '{"id":"'.$rowDataForUA['id'].'", "name":"'.$_escape_helper->escapeQuote($rowDataForUA['name']).'", "price":'.$rowDataForUA['price'].', "category":"Default Category", "position":'.$rowDataForUA['position'].', "list":"browsing"}'; ?>
                        <?php if(($key+1) < $total) {
                            echo ",";
                        } ?>
                    <?php endforeach; ?>
                );
            }
            else {
                <?php $total = count($dataForUA); ?>
                objDataLayer.push(
                    <?php foreach($dataForUA as $key=>$rowDataForUA): ?>
                        <?php echo '{"id":"'.$rowDataForUA['id'].'", "name":"'.$_escape_helper->escapeQuote($rowDataForUA['name']).'", "price":'.$rowDataForUA['price'].', "category":"Default Category", "position":'.$rowDataForUA['position'].', "list":"browsing"}'; ?>
                        <?php if(($key+1) < $total) {
                            echo ",";
                        } ?>
                    <?php endforeach; ?>
                );
                var ecommerceData = {
                    "ecommerce" :
                    {
                        "impressions" : objDataLayer,
                        "currencyCode":"IDR"
                    },
                    'event': 'impression',
                    'eventCategory':'ecommerce',
                    'eventAction':'impression'
                };  
                dataLayer.push(ecommerceData);
            }
        }
    });

    function ecommerceStaticBlockAddToCart(name, sku, price, price_ematic, list, link, imageUrl) {
        dataLayer.push({
          'event': 'addToCart',
          'ecommerce': {
            'currencyCode': 'IDR',
            'add': {                                // 'add' actionFieldObject measures.
              'actionField': {'list': list},
              'products': [{                        //  adding a product to a shopping cart.
                'name': name,
                'id': sku,
                'price': price,
                'quantity': 1,
                'category': '<?php echo (!empty($category)) ? $category : 'Default Category';?>',
                'brandName': 'brand name',
                'imageUrl': imageUrl,
                'link': link
               }]
            }
          }
        });

        // ematics cart - retrieve items from cart
        var temp_cart = [];
        var temp_item = "";
        var index_addeditem = -999;

        for (var itr=0; itr < <?php echo $itemQty ?>; itr++) {
        temp_item = jQuery(".mini-cart span#ematiccart").eq(itr).text();
        temp_cart[itr] = temp_item.split("|");
        if (temp_item.indexOf(sku) > -1) {
                index_addeditem = itr;
            }
        }

        // ematics cart - prepare for logging
        products = [
            <?php for($i=0; $i<$itemQty; $i++) {
                echo "{'name' : temp_cart[".$i."][0],";
                echo "'id' : temp_cart[".$i."][1],";
                echo "'price' : temp_cart[".$i."][3],";
                echo "'quantity' : temp_cart[".$i."][4],";
                echo "'brandName' : 'brand name',";
                echo "'imageUrl' : temp_cart[".$i."][5],";
                echo "'link' : temp_cart[".$i."][6]}";if($i != $itemQty-1) {echo ",";}
            } 
            ?>
        ];

        // ematics added item
        if (index_addeditem != -999) {    // same item exist in cart
            products[index_addeditem].quantity = parseInt(products[index_addeditem].quantity) + 1;
        }
        else {    // no same item
            products.push({
              'id': sku,
              'price': price_ematic,
              'quantity': 1,
              'name': name,
              'brandName': 'brand name',
              'imageUrl': imageUrl,
              'link': link
            });
        }

        // ematics track items in cart to enable pre-abandonded cart overlays
        ematics("log", "product", "cart", products);
    }

    function ecommerceStaticBlockProductClick(name,sku,price,list) {
        // alert("HURRY_PRODUCTCLICK_HOMEPAGE"+name+" "+sku+" "+price);
        dataLayer.push({
        'event': 'productClick',
        'ecommerce': {
          'click': {
            'actionField': {'list': list},      // Optional list property.
            'products': [{
              'name': name,                      // Name or ID is required.
              'id': sku,
              'price': price,
              'category': '<?php echo (!empty($category)) ? $category : 'Default Category';?>'
             }]
           }
         }
      });
    }
</script>
