<script type="text/javascript">
	jQuery(document).ready(function(){
		var pxShow = 20;//height on which the button will show
		var slideUpTime = 500;//how slow/fast you want the button to show
		var slideDownTime = 500;//how slow/fast you want the button to hide
		var scrollSpeed = 400;//how slow/fast you want the button to scroll to top. can be a value, 'slow', 'normal' or 'fast'
		jQuery(window).scroll(function(){
			if(jQuery(window).scrollTop() >= pxShow){
				jQuery("#backtotop").css("visibility","visible");
			}else{
				jQuery("#backtotop").css("visibility","hidden");
			}
		});
		 
		jQuery('#backtotop a').click(function(){
			jQuery('html, body').animate({scrollTop:0}, scrollSpeed); 
			return false; 
		}); 
	});
</script>

<div class="clrb"></div>
<div id="backtotop"><a href="#"> <i class="fa fa-angle-up"></i></a></div>