<?php echo $this->getChildHtml('items_before'); ?>

<style type="text/css">
    .cross-border-fee {
        display: none;
    }
</style>

<div>
  
  <?php echo $this->getChildHtml('agreements') ?>

  <div class="cust-container">
    <div class="cust-row padside50">
      <div class="cg-col-md-12">

        <?php 
        $this->getLocalAndImportItems(); 
        
        $localItems = $this->getLocalItems();
        if (!empty($localItems)) {
        ?>
            <div class="table-wrap">
                <table class="table bs table-bordered">
                    <thead>
                        <tr class="title">
                          <th colspan="5">
                              <?php echo $this->__('Produk Lokal'); ?>
                          </th>
                        </tr>
                        <tr>
                          <th><?php echo $this->__('Produk'); ?></th>
                          <th class="text-center"><?php echo $this->__('Kuantitas'); ?></th>
                          <th class="text-center"><?php echo $this->__('Berat'); ?></th>
                          <th class="text-center"><?php echo $this->__('Harga'); ?></th>
                          <th class="text-center"><?php echo $this->__('Total'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php 
                    foreach($localItems as $localItem) {
                        echo $this->getItemHtml($localItem);    
                    }
                    ?>
                        <tr class="cross-border-fee">
                            <th class="footer-table" colspan="5" id="local-product-fee">
                                <strong>Biaya Pengiriman:&nbsp;</strong>
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>
        <?php
        }

        $importItems = $this->getImportItems();
        if (!empty($importItems)) {
        ?>
            <div class="table-wrap">
                <table class="table bs table-bordered">
                    <thead>
                        <tr class="title">
                          <th colspan="5">
                              <?php echo $this->__('Produk Import'); ?>
                          </th>
                        </tr>
                        <tr>
                          <th><?php echo $this->__('Produk'); ?></th>
                          <th class="text-center"><?php echo $this->__('Kuantitas'); ?></th>
                          <th class="text-center"><?php echo $this->__('Berat'); ?></th>
                          <th class="text-center"><?php echo $this->__('Harga'); ?></th>
                          <th class="text-center"><?php echo $this->__('Total'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php 
                    foreach($importItems as $importItem) {
                        echo $this->getItemHtml($importItem);    
                    }
                    ?>
                        <tr class="cross-border-fee">
                            <th class="footer-table" colspan="5" id="import-product-fee">
                                <strong>Biaya Pengiriman:&nbsp;</strong>
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>
        <?php
        }
        ?>

      </div>    
    </div>
  </div>

  <div class="cust-container" id="review-buttons-container">
    <div class="cust-row padside50">
      <div class="cg-col-md-5">
        <div class="night col-box equal-box vmiddle">
          <div class="discount">
            <div class="label text-left">
              <strong><?php echo $this->__('Memiliki kupon promo atau gift card?'); ?></strong>
            </div>
            <div class="wrap-input-voucher">
              <input type="hidden" name="remove" id="remove-coupone" value="0" />
              <input type="text" placeholder="<?php echo $this->__('Masukkan kode promo / gift card'); ?>" id="coupon_code" name="coupon_code" 
                value="<?php echo $this->escapeHtml($this->getCouponCode()); ?>" />
              <?php $feedbackStyle = 'color: red';?>
              <?php if(strlen($this->getCouponCode())): ?>
                <?php $feedbackStyle = 'color: green';?>
                  <button class="button cancel-voucher" type="button" onclick="return cekCustomVoucher(true)" 
                    title="<?php echo $this->__('Cancel Voucher') ?>" value="<?php echo $this->__('Cancel Voucher'); ?>">
                    <?php echo $this->__('Cancel'); ?>
                  </button>
              <?php else: ?>
                <button class="button apply-voucher" type="button" onclick="return cekCustomVoucher(false)" 
                  title="<?php echo $this->__('Apply Voucher'); ?>" value="<?php echo $this->__('Apply Voucher'); ?>">
                  <?php echo $this->__('Gunakan') ?>
                </button>
              <?php endif;?>
            </div>
            <div id="feedback" style="<?php echo $feedbackStyle;?>"><?php echo $this->getSessionMessage();?></div>
            <div style="clear: both;"></div>
          </div>         
        </div>
      </div>

      <div class="cg-col-md-5 ">
        <div class="night col-box equal-box">
          <table class="table bs grand-total">
            <tbody>
              <?php echo $this->getChildHtml('totals'); ?>
              <tr>
                <th colspan="2">
                    <div class="grandline"></div>
                </th>
              </tr>
              <tr>
                <th scope="row" class="normal text-center" colspan="2">
                  <?php echo $this->__('Ada barang yang tertinggal?');?>&nbsp;
                  <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit keranjang belanja'); ?></a>
                </th>
              </tr>
              <tr>
                <th scope="row" colspan="2">
                  <?php echo $this->getChildHtml('button') ?>
                  <span class="please-wait" id="review-please-wait" style="display:none;">
                      <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
                  </span>
                </th>
              </tr>
            </tbody>
          </table>        
        </div>
      </div>
    </div>
  </div>

  <form name="co-installment-form" id="co-installment-form" action="">
      <?php echo $this->getChildHtml('items_after'); ?>
      <?php echo $this->getChildHtml('items_installment'); ?>
      <?php echo $this->getChildHtml('items_installment_scb'); ?>
  </form>

  <script type="text/javascript">
    //<![CDATA[
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'), $('co-installment-form'));

        /*** BEGIN - Hack to split Shipping Fee ***/
        var extractFee = function(fullText) {
            var fee;
            var regex = /Rp(.*)/g;
            var matches = fullText.match(regex);
            if (matches.length > 0) {
                matches[0] = matches[0].trim();
                fee = matches[0].slice(0, matches[0].indexOf(")"));
            }
            return fee;
        };
        var extractDuration = function(fullText) {
            var duration;
            var regex = /\((.*)kerja\)/g;
            var matches = fullText.match(regex);
            if (matches.length > 0) {
                matches[0] = matches[0].trim();
                duration = matches[0].slice(matches[0].lastIndexOf("("));
            }
            return duration;
        };
        var shippingCol = jQuery('table.grand-total tbody tr:nth-child(2) th:nth-child(1)');
        var shippingText = shippingCol.text().trim();
        var splitShippingText = shippingText.split('+');
        if (splitShippingText.length === 2) {
            var localFee = extractFee(splitShippingText[0]);
            var importFee = extractFee(splitShippingText[1]);
            var localDuration = extractDuration(splitShippingText[0]);
            var importDuration = extractDuration(splitShippingText[1]);
            jQuery('#local-product-fee').append(localFee + '&nbsp;' + localDuration);
            jQuery('#import-product-fee').append(importFee + '&nbsp;' + importDuration);
            jQuery('.cross-border-fee').fadeIn(500);
            jQuery('#review-shipping-label').html('Shipping & Handling');
        }
        /*** END - Hack to split Shipping Fee ***/
    //]]>
  </script> 

</div>

<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>

<div id="threedsecure-popup" class="success-form-popup">
    <div class="popup">
        <form target="_blank" action="" method="post" id="event-form" name="event_form">
        <div class="blockbkg" id="bkg">
            <div class="cont" id="dlg">
                <iframe src=""></iframe>
            </div>
        </div>
        </form>
        <div style="clear: both;"></div>
    </div>
</div>
