<?php echo $this->getChildHtml('items_before'); ?>

<div class="cust-container">
  <div class="cust-row padside50">
    <div class="cg-col-md-12">
      <div class="table-wrap">
        <table class="table bs table-bordered">
          <thead>
            <tr class="title">
                <th colspan="5">
                  Produk Lokal
                </th>
            </tr>
            <tr>
              <th>Produk</th>
              <th class="text-center">Kuantitas</th>
              <th class="text-center">Berat</th>
              <th class="text-center">Harga</th>
              <th class="text-center">Total</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">
                <div class="img-item">
                  <img src="http://thumbnail.image.rakuten.co.jp/@0_mall/prospo/cabinet/adidas-5/adj-s85586-.jpg?_ex=128x128" alt="">
                </div>
                <div class="txt-item">
                  Zeld Doorstep Tiger Yellow
                </div>
              </th>
              <td class="text-center">1</td>
              <td class="text-center">0.2 kg</td>
              <td class="text-center">Rp. 100,000</td>
              <td class="text-center">Rp. 100,000</td>
            </tr>
            <tr>
              <th class="footer-table" colspan="5">
                <strong>Biaya Pengiriman:</strong> Rp 9,000 (3 - 5 hari kerja)
              </th>
            </tr>
          </tbody>
        </table>
      </div> 

      <div class="table-wrap">
        <table class="table bs table-bordered">
          <thead>
            <tr class="title">
                <th colspan="5">
                  Produk Import
                </th>
            </tr>
            <tr>
              <th>Produk</th>
              <th class="text-center">Kuantitas</th>
              <th class="text-center">Berat</th>
              <th class="text-center">Harga</th>
              <th class="text-center">Total</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">
                <div class="img-item">
                  <img src="http://thumbnail.image.rakuten.co.jp/@0_mall/prospo/cabinet/adidas-5/adj-s85586-.jpg?_ex=128x128" alt="">
                </div>
                <div class="txt-item">
                  Zeld Doorstep Tiger Yellow
                </div>
              </th>
              <td class="text-center">1</td>
              <td class="text-center">0.2 kg</td>
              <td class="text-center">Rp. 100,000</td>
              <td class="text-center">Rp. 100,000</td>
            </tr>
            <tr>
              <th class="footer-table" colspan="5">
                <strong>Biaya Pengiriman:</strong> Rp 9,000 (3 - 5 hari kerja)
              </th>
            </tr>
          </tbody>
        </table>
      </div>

        <div class="table-wrap">
            <table class="table bs table-bordered">
                <thead>
                <tr class="title">
                    <th colspan="5">
                        Produk Import
                    </th>
                </tr>
                <tr>
                    <th>Produk</th>
                    <th class="text-center">Kuantitas</th>
                    <th class="text-center">Berat</th>
                    <th class="text-center">Harga</th>
                    <th class="text-center">Total</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item)?>
                <?php endforeach ?>
                <tr>
                    <th class="footer-table" colspan="5">
                        <strong>Biaya Pengiriman:</strong> Rp 9,000 (3 - 5 hari kerja)
                    </th>
                </tr>
                </tbody>
            </table>
        </div>

    </div>    
  </div>
</div>

<div class="cust-container">
  <div class="cust-row padside50">
    <div class="cg-col-md-5">
      <div class="night col-box equal-box vmiddle">
        <div class="discount">
          <div class="label text-left">
            <strong><?php echo $this->__('Memiliki kupon promo atau gift card?'); ?></strong>
          </div>
          <div class="wrap-input-voucher">
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <input type="text" placeholder="<?php echo $this->__('Masukkan kode promo / gift card'); ?>" id="coupon_code" name="coupon_code" 
              value="<?php echo $this->escapeHtml($this->getCouponCode()); ?>" />
            <?php $feedbackStyle = 'color: red';?>
            <?php if(strlen($this->getCouponCode())): ?>
              <?php $feedbackStyle = 'color: green';?>
                <button class="button cancel-voucher" type="button" onclick="return cekCustomVoucher(true)" 
                  title="<?php echo $this->__('Cancel Voucher') ?>" value="<?php echo $this->__('Cancel Voucher'); ?>">
                  <?php echo $this->__('Cancel Voucher'); ?>
                </button>
            <?php else: ?>
              <button class="button apply-voucher" type="button" onclick="return cekCustomVoucher(false)" 
                title="<?php echo $this->__('Apply Voucher'); ?>" value="<?php echo $this->__('Apply Voucher'); ?>">
                <?php echo $this->__('Gunakan') ?>
              </button>
            <?php endif;?>
          </div>
          <div id="feedback" style="<?php echo $feedbackStyle;?>"><?php echo $this->getSessionMessage();?></div>
          <div style="clear: both;"></div>
        </div>         
      </div>
    </div>

    <div class="cg-col-md-5 ">
      <div class="night col-box equal-box">
        <table class="table bs grand-total">
          <tbody>
            <tr>
              <th scope="row">Subtotal</th>
              <td class="text-right">Rp 1,473,750</td>
            </tr>
            <tr>
              <th scope="row">Bilna Credit</th>
              <td class="text-right cuts">- Rp 10.000</td>
            </tr>
            <tr>
              <th scope="row">Kode promo / gift card</th>
              <td class="text-right cuts">- Rp 75,000</td>
            </tr>
            <tr>
              <th scope="row">Biaya Pengiriman (lokal)</th>
              <td class="text-right">Rp 9,000</td>
            </tr>
            <tr>
              <th scope="row">Biaya Pengiriman (impor)</th>
              <td class="text-right">Rp 90,000</td>
            </tr>
            <tr class="uppercase">
              <th scope="row">GRAND TOTAL</th>
              <td class="text-right">Rp  100,408,650</td>
            </tr>
            <tr>
              <th colspan="2">
                  <div class="grandline"></div>
              </th>
            </tr>
            <tr>
              <th scope="row" class="normal text-center" colspan="2">
                <?php echo $this->__('Ada barang yang tertinggal?');?>&nbsp;
                <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit keranjang belanja'); ?></a>
              </th>
            </tr>
            <tr>
              <th scope="row" colspan="2">
                <?php echo $this->getChildHtml('button'); ?>
              </th>
            </tr>
          </tbody>
        </table>        
      </div>
    </div>
  </div>
</div>

<form name="co-installment-form" id="co-installment-form" action="">
    <div id="checkout-review-table-wrapper">
        <table class="data-table" id="checkout-review-table">
            <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <col width="1" />
            <?php endif; ?>
            <thead>
                <tr>
                    <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
                    <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
                    <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                    <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                <?php endif; ?>
            </thead>
            <?php echo $this->getChildHtml('totals'); ?>
            <tbody>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item)?>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>

    <?php echo $this->getChildHtml('items_after'); ?>
    <?php echo $this->getChildHtml('items_installment'); ?>
    <?php echo $this->getChildHtml('items_installment_scb'); ?>

</form>

<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        
          <!-- start add -->  
          
          <div class="discount">
            <h2><?php echo $this->__('Voucher Code') ?></h2>
            <div class="discount-form">
                <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
                <input type="hidden" name="remove" id="remove-coupone" value="0" />
                <div class="input-box">
                    <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
                </div>
                <div class="buttons-set">
                    <button onclick="return cekCustomVoucher(false)" type="button" title="<?php echo $this->__('Apply Voucher') ?>" class="button apply-voucher" value="<?php echo $this->__('Apply Voucher') ?>"><span><span><?php echo $this->__('Apply Voucher') ?></span></span></button>
                    <?php $feedbackStyle = 'color: red';?>
                    <?php if(strlen($this->getCouponCode())): ?>
                        <?php $feedbackStyle = 'color: green';?>
                        &nbsp; <button type="button" title="<?php echo $this->__('Cancel Voucher') ?>" class="button cancel-voucher" onclick="return cekCustomVoucher(true)" value="<?php echo $this->__('Cancel Voucher') ?>"><span><span><?php echo $this->__('Cancel Voucher') ?></span></span></button>
                    <?php endif;?>
                </div>
                <div id="feedback" style="<?php echo $feedbackStyle;?>"><?php echo $this->getSessionMessage();?></div>
            </div>
        </div>
		<div class="f-right">
        <p><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a>
        </p>
        <!-- end add -->
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
		</div>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'), $('co-installment-form'));
    //]]>
    </script>

</div>



<div id="threedsecure-popup" class="success-form-popup">
    <div class="popup">
        <form target="_blank" action="" method="post" id="event-form" name="event_form">
        <div class="blockbkg" id="bkg">
            <div class="cont" id="dlg">
                <iframe src=""></iframe>
            </div>
        </div>
        </form>
        <div style="clear: both;"></div>
    </div>
</div>
