<?php $posts = $this->getCategoriesPosts(); ?>
<!DOCTYPE HTML>
<html>
  <head>
    <meta name="generator"
    content="HTML Tidy for HTML5 (experimental) for Windows https://github.com/w3c/tidy-html5/tree/c63cc39" />
    <div>
      <div class="postWrapper">
        <div style="width: 100%;clear: both;">
    <script>
        jssor_slider1_starter = function (containerId) {
            var options = {
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                $DirectionNavigatorOptions: {                       //[Optional] Options to specify and enable direction navigator or not
                    $Class: $JssorDirectionNavigator$,              //[Requried] Class to create direction navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 0,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
                }
            };

            var jssor_slider1 = new $JssorSlider$(containerId, options);
        };
    </script>
    <!-- Jssor Slider Begin -->
    <!-- You can move inline styles (except 'top', 'left', 'width' and 'height') to css file or css block. -->
    <div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 600px;
        height: 300px; ">

        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 600px; height: 300px;
            overflow: hidden;">
            <div class="slider-blog-jssor"><img u="image" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" /></div>
            <div class="slider-blog-jssor"><img u="image" src="http://192.168.2.31/bilna-baru/media/aw_islider/52c2686f0eb37.jpg" /></div>
            <div class="slider-blog-jssor"><img u="image" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" /></div>
            <div class="slider-blog-jssor"><img u="image" src="http://192.168.2.31/bilna-baru/media/aw_islider/52c2686f0eb37.jpg" /></div>
        </div>
        
        <!-- Direction Navigator Skin Begin -->
        <style>
            /* jssor slider direction navigator skin 03 css */
            /*
            .jssord03l              (normal)
            .jssord03r              (normal)
            .jssord03l:hover        (normal mouseover)
            .jssord03r:hover        (normal mouseover)
            .jssord03ldn            (mousedown)
            .jssord03rdn            (mousedown)
            */
            .jssord03l, .jssord03r, .jssord03ldn, .jssord03rdn
            {
              position: absolute;
              cursor: pointer;
              display: block;
                background: url('http://192.168.2.31/bilna-baru/skin/frontend/default/bilna/images/arrow-menu-mobile.png') no-repeat;
                overflow:hidden;
            }
            .jssord03l { background-position: -3px -33px; }
            .jssord03r { background-position: -63px -33px; }
            .jssord03l:hover { background-position: -123px -33px; }
            .jssord03r:hover { background-position: -183px -33px; }
            .jssord03ldn { background-position: -243px -33px; }
            .jssord03rdn { background-position: -303px -33px; }
        </style>
        <!-- Arrow Left -->
        <span u="arrowleft" class="jssord03l" style="width: 55px; height: 55px; top: 123px; left: 8px;">
        </span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssord03r" style="width: 55px; height: 55px; top: 123px; right: 8px">
        </span>
        <!-- Direction Navigator Skin End -->
        <a style="display: none" href="http://www.jssor.com">jQuery Slideshow</a>
        <!-- Trigger -->
        <script>
            jssor_slider1_starter('slider1_container');
        </script>
    </div>
    <!-- Jssor Slider End -->
    
    </div>
    
        <?php $j=0; foreach ($posts as $key => $post): ?>
            <?php 
                echo $this->getLayout()->createBlock('core/template')
                    ->setTemplate('aw_blog/'.$post['layout'])
                    ->setData('catPosts', array('posts' => $post['post'], 'cat' => $post['catName']) )
                    ->toHtml();
            ?>
        <?php $j++; endforeach; ?> 

      </div>
      
    </div>
  </body>
</html>