<?php $posts = $this->getCategoriesPosts(); ?>

    <div>
		
		<div class="postWrapper">
				<div style="width: 100%;clear: both;">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('blog-islider')->toHtml() ?>
					<div style="clear: both;"></div>
				</div>
		</div>
	<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>		
			<?php $j=0; foreach ($posts as $key => $post): ?>
				<?php 
					echo $this->getLayout()->createBlock('core/template')
						->setTemplate('aw_blog/'.$post['layout'])
						->setData('catPosts', array('posts' => $post['post'], 'cat' => $post['catName'], 'subCat' => $post['subName']) )
						->toHtml();
				?>
			<?php $j++; endforeach; ?> 
	<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
		
    </div>