
<div>
<div class="postWrapper">
    <div>  
        <div class="postContent">
			<div>
				<div class="searchbox">
					<form id="search_mini_form" action="http://rebirth.bilna/baby/blog/search/index/" method="get">
						<div class="form-search blog-form-search">
							<!--<label for="search">Search:</label-->
							<input id="search" type="text" name="q" value="" class="input-text blog-search" maxlength="128" placeholder="Search article">
							<button type="submit" title="Search" class="button blog-submit-search"><img src="<?php echo $this->getSkinUrl('images/search-blog-icon.jpg') ?>"/></button>
							<!--span class="search_text"><a href="http://www.bilna.com/catalogsearch/advanced/">can't find what you're looking for?</a></span-->
							<div id="search_autocomplete" class="search-autocomplete"></div>
							<script type="text/javascript">
							//<![CDATA[
								//var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
								//searchForm.initAutocomplete('', 'search_autocomplete');
							//]]>
							</script>
						</div>
					</form>
				</div>
			</div>
			<div style="clear:both;"></div>
		</div>
	</div>
	
	
	<?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
	<div class="postContent2">
		<div class="cat-title">
			<h2><?php echo Mage::helper('blog')->__('Categories'); ?></h2>
		</div>
		<div class="cat-list">
			<ul style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block;">
				<?php $cats = $this->getCategories(); ?>
				<?php foreach ($cats as $cat): ?>
                    <li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
                <?php endforeach; ?>
			</ul>
		<div>
			
		</div>
	</div>
	<?php endif; ?>

		

    <?php if ($posts = $this->getRecent()): ?>    
	<div style="clear:both;"></div>
	<div class="postContent3">
		<div class="cat-title">
			<h2><?php echo Mage::helper('blog')->__('Recent Posts'); ?></h2>
		</div>
		<div class="bg-greyblog">
			<?php foreach ($posts as $post): ?>
			<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #dadada;">
				<div class="postTitle4">
					<img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?><?php echo $post->getImageName();?>" style="float: left;">
					<div style="float: left;width: 60%;"> 
						<h2 class="post-blog-title-small"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
						<?php $d = new DateTime($post->getCreatedTime());?>
						<h3><?php echo $d->format('l d, F Y h:i:s A'); ?></h3>
					</div>
				</div>
			</div>
			<?php endforeach; ?>
			<div style="clear:both;"></div>
		</div>
	</div>
	<?php endif; ?>
	
	<?php if ($posts = $this->getPopular()): ?>
	<div style="clear:both;"></div>
		<div class="postContent3" style="display: none;">
			<div class="cat-title">
				<h2><?php echo Mage::helper('blog')->__('POPULAR'); ?></h2>
			</div>
			<div class="bg-greyblog">
				<?php foreach ($posts as $post): ?>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #dadada;">
					<div class="postTitle4">
						<img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?><?php echo $post->getImageName();?>" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h2 class="post-blog-title-small"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
							<?php $d = new DateTime($post->getCreatedTime());?>
							<h3><?php echo $d->format('l d, F Y h:i:s A'); ?></h3>
						</div>
					</div>
				</div>
				<?php endforeach; ?>
				<div style="clear:both;"></div>
			</div>
		</div>
		<?php endif; ?>

	<?php if ($comments = $this->getComment()): ?>	
	<div style="clear:both;"></div>
		<div class="postContent3">
			<div class="cat-title">
				<h2><?php echo Mage::helper('blog')->__('Recent Comments'); ?></h2>
			</div>
			<div class="bg-greyblog">
				<?php foreach ($comments as $comment): ?>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #dadada;">
					<div class="postTitle4">
						<img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?><?php echo $comment->getImageName();?>" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h3 class="post-blog-title-small2"><?php echo $comment->getUser(); ?> <label style="font-weight: normal;">on</label><?php echo $comment->getTitle(); ?></h3>
							<?php $d = new DateTime($comment->getCreatedTime());?>
							<h3><?php echo $d->format('l d, F Y h:i:s A'); ?></h3>
						</div>
					</div>
				</div>
				<?php endforeach; ?>
				<div style="clear:both;"></div>
			</div>
		</div>
	<?php endif; ?>
	</div>
</div>



</div>
