<!DOCTYPE HTML>
<html>
<link rel="stylesheet" type="text/css" href="css/styles.css"/>
<link rel="stylesheet" type="text/css" href="css/style.css"/>
<link rel="stylesheet" type="text/css" href="css/general.css" />
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script type="text/javascript" src="lib/jquery-1.10.1.min.js"></script>
	
	
	
<body>

<div>
<div class="postWrapper">
    <div>  
        <div class="postContent">
			<div>
				<div class="searchbox">
					<form id="search_mini_form" action="http://www.bilna.com/catalogsearch/result/" method="get">
						<div class="form-search blog-form-search">
							<!--<label for="search">Search:</label-->
							<input id="search" type="text" name="q" value="" class="input-text blog-search" maxlength="128" placeholder="Search article">
							<button type="submit" title="Search" class="button blog-submit-search"><img src="<?php echo $this->getSkinUrl('images/search-blog-icon.jpg') ?>"/></button>
							<!--span class="search_text"><a href="http://www.bilna.com/catalogsearch/advanced/">can't find what you're looking for?</a></span-->
							<div id="search_autocomplete" class="search-autocomplete"></div>
							<script type="text/javascript">
							//<![CDATA[
								//var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
								//searchForm.initAutocomplete('', 'search_autocomplete');
							//]]>
							</script>
						</div>
					</form>
					  </div>
			</div>
			<div style="clear:both;"></div>
		</div>
	</div>
	
	
	<div class="postContent2">
		<div class="cat-title">
			<h2>Category</h2>
		</div>
		<div class="cat-list">
			<ul style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block;">
				<li><a>Ibu & Kehamilan</a></li>
				<li><a>Balita</a></li>
				<li><a>Ibu</a></li>
				<li><a>Anak</a></li>
				<li><a>Keluarga</a></li>
			</ul>
		<div>
			
		</div>
	</div>
	
	<div style="clear:both;"></div>
		<div class="postContent3">
			<div class="cat-title">
				<h2>Recent Post</h2>
			</div>
			<div class="bg-greyblog">
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
				</div>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;">
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
					
				</div>
				
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
				</div>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;">
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
					
				</div>
				<div style="clear:both;"></div>
			</div>
		</div>
		
	
	<div style="clear:both;"></div>
		<div class="postContent3">
			<div class="cat-title">
				<h2>POPULAR</h2>
			</div>
			<div class="bg-greyblog">
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
				</div>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;">
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
					
				</div>
				
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
				</div>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;">
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
					
				</div>
				<div style="clear:both;"></div>
			</div>
		</div>
		
		
	<div style="clear:both;"></div>
		<div class="postContent3">
			<div class="cat-title">
				<h2>Recent COMMENTS</h2>
			</div>
			<div class="bg-greyblog">
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
				</div>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;">
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
					
				</div>
				
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
				</div>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #666;">
					<div class="postTitle4">
						<img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/Artikel/i-am-image.jpg" style="float: left;">
						<div style="float: left;width: 60%;">
							<h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
							<h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
						</div>
					</div>
					
				</div>
				<div style="clear:both;"></div>
			</div>
		</div>
	
	
	
		
		
	</div>
</div>



</div>

</body>
</html>