
<div>
<div class="postWrapper">
    <div>  
        <div class="postContent">
			<div>
				<div class="searchbox">
					<form id="search_mini_form" action="<?php echo Mage::getUrl('*/search/index');?>" method="get">
						<div class="form-search blog-form-search">
							<!--<label for="search">Search:</label-->
							<input id="search" type="text" name="q" value="" class="input-text blog-search" maxlength="128" placeholder="Search article">
							<button type="submit" title="Search" class="button blog-submit-search"><img src="<?php echo $this->getSkinUrl('images/search-blog-icon.jpg') ?>"/></button>
						</div>
					</form>
				</div>
			</div>
			<div style="clear:both;"></div>
		</div>
	</div>
	
	
	<?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
	<div class="postContent2">
		<div class="cat-title">
			<h2><?php echo Mage::helper('blog')->__('Categories'); ?></h2>
		</div>
		<div class="cat-list">
			<ul style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block;">
				<?php $cats = $this->getCategories(); ?>
				<?php foreach ($cats as $cat): ?>
                    <li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
                <?php endforeach; ?>
			</ul>
		<div>
			
		</div>
	</div>
	<?php endif; ?>
	
	<?php if ($posts = $this->getPopular()): ?>
	<div style="clear:both;"></div>
		<div class="postContent3" style="display: none;">
			<div class="cat-title">
				<h2><?php echo Mage::helper('blog')->__('POPULAR'); ?></h2>
			</div>
			<div class="bg-greyblog">
				<?php foreach ($posts as $post): ?>
				<div style="width: 100%; margin-left:5px 2% 5px 2%;float:left;display: block; border-bottom: 1px solid #dadada;">
					<div class="postTitle4">
						<img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?><?php echo $post->getImageName();?>" style="float: left;">
						<div style="float: left;width: 60%;"> 
							<h2 class="post-blog-title-small"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
							<?php $d = new DateTime($post->getCreatedTime());?>
							<h3><?php echo $d->format('l d, F Y h:i:s A'); ?></h3>
						</div>
					</div>
				</div>
				<?php endforeach; ?>
				<div style="clear:both;"></div>
			</div>
		</div>
		<?php endif; ?>

	</div>
	
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	
	<!--FACEBOOK-->
	<div class="fb-like-box" style="clear: both; display: block; padding: 20px 0;" data-href="http://www.facebook.com/myBilna" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="false" ></div>
	<div style="clear:both;"></div>

	<!--RSS BLOG-->
	<div style="margin: 1px 0 0 !important; display: block; clear: both;" class="block block-rss">
	<div style="text-align: left;" class="block-title">
	<a target="_blank" type="application/rss+xml" rel="alternate" href="<?php echo Mage::getBaseUrl(); ?>blog/rss" style="margin: 0 0 0 10px;">
	<img style="border:0" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/blog/feed-icon32x32.png">
	</a>
	</div>
	<div class="block-content"></div>
	</div>
	<div style="clear:both;"></div>
	
</div>



</div>
