<?php $posts = $this->getPosts(); ?>
<?php if (count($posts)): ?>
 
 <label style="margin: 10px 0"><?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?></label>
    <?php foreach ($posts as $post): ?>
        <div class="postWrapper">
            
            <div class="postContent">
                <img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?><?php echo $post->getImageName();?>" style="padding:0 10px 10px 0; display: blog; float: left;" />
                <p>
                    <div class="postTitle">
                        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                        <h3><?php echo $post->getCreatedTime(); ?></h3>
                    </div>
                </p>
                <?php echo $post->getPostContent(); ?></div>
            <?php echo $this->getBookmarkHtml($post) ?>
            <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
            <div class="postDetails">
                <?php if ($this->getCommentsEnabled()): ?>
                    <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> |
                <?php endif; ?>
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                    <?php echo Mage::helper('blog')->__('Posted in'); ?>
                    <?php foreach ($postCats as $data): ?>
                            <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php echo Mage::helper('blog')->__('Posted'); ?>
                <?php endif; ?><?php echo$this->__("By"); ?> <?php echo $post->getUser(); ?></div>
        </div>
    <?php endforeach; ?>
 <label style="margin: 10px 0"><?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?></label>
<?php else: ?>
    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
<?php endif; ?>