<input type="hidden" id="3rdparty-type" value="cart"/>
<input type="hidden" id="3rdparty-value" value="" />
<script type="text/javascript" src="<?php echo Mage::getStoreConfig('payment/vtdirect/vtdirect_src'); ?>"></script>
<script type="text/javascript">
    var baseUrl = '<?php echo Mage::getBaseUrl(); ?>';
    var bankCheckUrl = '<?php echo Mage::helper('paymethod')->checkHttpsProtocol(Mage::getBaseUrl() . 'paymethod/onepage/bankCheck'); ?>';
    var vtDirectUrl = '<?php echo Mage::getStoreConfig('payment/vtdirect/vtdirect_url'); ?>';
    var vtDirectClientKey = '<?php echo Mage::getStoreConfig('payment/vtdirect/client_key'); ?>';
    var creditCardPayment = '<?php echo Mage::getStoreConfig('bilna_module/success_page/payment_cc'); ?>';
    var creditCardPaymentArr = creditCardPayment.split(',');
    var ccDefaultMessageFailure = '<?php echo Mage::getStoreConfig('payment/vtdirect/default_response_message_failure'); ?>';
</script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/bilna_paymethod.js'); ?>"></script>

<div class="page-title">
    <h1><?php echo $this->__('Checkout'); ?></h1>
</div>

<ol class="opc" id="checkoutSteps">
    <?php $i = 0; foreach ($this->getSteps() as $_stepId => $_stepInfo): ?>
    <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++; ?>
        <li id="opc-<?php echo $_stepId; ?>" class="section<?php echo !empty ($_stepInfo['allow']) ? ' allow' : ''; ?><?php echo !empty ($_stepInfo['complete']) ? ' saved' : ''; ?>">
            <div class="step-title">
                <span class="number"><?php echo $i; ?></span>
                <h2><?php echo $_stepInfo['label']; ?></h2>
                <a href="#"><?php echo $this->__('Edit'); ?></a>
            </div>
            
            <div id="checkout-step-<?php echo $_stepId; ?>" class="step a-item" style="display:none;">
                <?php echo $this->getChildHtml($_stepId); ?>
            </div>
        </li>
    <?php endforeach; ?>
</ol>

<?php $items = $this->getItems();?>
<?php if (!empty($items)){?>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
        <?php $gtmItemIds = $_item->getId().'|'; ?>
    <?php endforeach; ?>
<?php }?>

<?php $cartItems = Mage::getSingleton('checkout/session')->getQuote()->getAllItems(); ?>
<?php $skuCollection = array(); ?>
<?php $productCollection = array(); ?>
<?php $qtyCollection = array(); ?>
<?php $valueCollection = array(); ?>
<?php $totalValue = 0; ?>
<?php foreach($cartItems as $cartItem) : ?>
    <?php $skuCollection[] = $cartItem->getSku(); ?>
    <?php $productCollection[] = $cartItem->getProductId(); ?>
    <?php $qtyCollection[] = $cartItem->getQty(); ?>
    <?php $valueCollection[] = $cartItem->getPrice(); ?>
    <?php $totalValue += ($cartItem->getPrice() * $cartItem->getQty()); ?>
<?php endforeach; ?>
<?php $skuDisplay =  implode("','", $skuCollection); ?>
<?php $productDisplay =  implode("','", $productCollection); ?>
<?php $qtyDisplay =  implode("','", $qtyCollection); ?>
<?php $valueDisplay =  implode("','", $valueCollection); ?>

<script type="text/javascript">
    jQuery(document).ready(function () {
        dataLayer.push({'ecomm_pagetype': 'cart'});
        dataLayer.push({'productid': ['<?php echo $productDisplay; ?>']});
        dataLayer.push({'skuid': ['<?php echo $skuDisplay; ?>']});
        dataLayer.push({'prices': ['<?php echo $valueDisplay; ?>']});
        dataLayer.push({'quantities': ['<?php echo $qtyDisplay; ?>']});
    });
    //<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if ($this->getActiveStep()): ?>
        accordion.openSection('opc-<?php echo $this->getActiveStep(); ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress'); ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review'); ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod'); ?>',
        failure: '<?php echo $this->getUrl('checkout/cart'); ?>'}
    );
    //]]>

    function ecommercePurchases() {
        var temp_grandTotal = jQuery("td#grand_total-onepage span.price").text().replace("Rp","");
        temp_grandTotal = temp_grandTotal.replace(",","");
        dataLayer.push({
          'event': 'purchase',
          'eventCategory':'ecommerce',
          'eventAction':'purchase',
          'ecommerce': {
            'purchase': {
              'actionField': {
                'id' : 'default_id',
                'list' : 'browsing'
              },
              'products' :
                [
                    <?php
                        $itr_name = 0; 
                        for ($itr = 0 ; $itr <= count($productCollection)-1 ; $itr++) {
                        if ($valueCollection[$itr] != 0) {
                            echo '{"id":"'.$skuCollection[$itr].'","name":jQuery("#checkout-review-table tbody tr td h3").eq('.$itr_name.').text() , "price":"'.$valueCollection[$itr].'", "quantity":'.$qtyCollection[$itr].'}';
                            if(($itr+1) < count($productCollection)) {
                                echo ",";
                            }
                            $itr_name++;
                        }
                    }
                    ?>
                ]
            }
          }
        });
    }
</script>

<!-- BEGIN - Moved from app/design/frontend/base/default/template/checkoutpromo/checkoutpromo.phtml -->
<?php
$url = $this->getUrl('checkout/cart/customCheckoutCouponPost');
$url = Mage::helper('paymethod')->checkHttpsProtocol($url);
Mage::getSingleton('core/session')->setSessionCouponMessage('');
$session = Mage::getSingleton('checkout/session');
$points_amount = $session->getData('points_amount');
?>
<script type="text/javascript">
    var usePointWithCoupon = <?php echo Mage::getStoreConfig('points/general/use_with_coupons'); ?>;
    function refreshBlock(){
        new Ajax.Request('<?php echo $this->getCheckoutpromoUrl(); ?>', {
            method:'get',
            onSuccess: function(transport){
                var response = transport.responseText;

                var checkoutpromo_div = $('checkoutpromo');
                checkoutpromo_div.update(response);

            },
            onFailure: function(){
                alert('Something went wrong, please try later...')
            }
        });
    }

    function cekCustomVoucher(isRemove)
    {
        jQuery(".button btn-checkout").attr("disabled", true);
        var remove = 0;
        if(isRemove)
        {
            remove = 1;
        }else{
            remove = 0;
        }
        //alert($('points_amount').value);

        //var url = '<?php echo $this->getUrl('checkout/cart/customCheckoutCouponPost') ?>';
        var url = '<?php echo $url; ?>';
        jQuery.ajax({
            type: "POST",
            url : url,
            data: { coupon_code: jQuery('#coupon_code').val(), remove: remove},
            beforeSend: function( xhr ) {
                $('feedback').setStyle('color: green;').update('Checking Coupon Code ... <img src="<?php echo $this->getSkinUrl("ajaxlogin/ajax-loader-tr.gif")?>" title="Loading..." alt="Loading..." border="0" />');
            },
            success: function(res){
                if(res.status == 1){
                    $('feedback').update(res.desc).setStyle('color: green;');
                    if (usePointWithCoupon != 1) {
                        if($('use_points')){
                            $('use_points').disabled = $('points_amount').disabled = true;
                        }
                    }
                }else{
                    if (usePointWithCoupon != 1) {
                        if($('use_points')){
                            $('use_points').disabled = $('points_amount').disabled = false;
                        }
                    }
                    $('feedback').update(res.desc).setStyle('color: red;');
                }
                setTimeout(function(){
                    jQuery(".button btn-checkout").attr("disabled", false);
                }, 1000);
                payment.save();
            },
            error: function() {
                $('feedback').update(res.desc);
            }
        });

        return false;
    }
</script>
<!-- END  - Moved from app/design/frontend/base/default/template/checkoutpromo/checkoutpromo.phtml -->