<input type="hidden" id="3rdparty-type" value="cart"/>
<input type="hidden" id="3rdparty-value" value="" />
<script type="text/javascript" src="<?php echo Mage::getStoreConfig('payment/vtdirect/vtdirect_src'); ?>"></script>
<script type="text/javascript">
    var baseUrl = '<?php echo Mage::getBaseUrl(); ?>';
    var bankCheckUrl = '<?php echo Mage::helper('paymethod')->checkHttpsProtocol(Mage::getBaseUrl() . 'paymethod/onepage/bankCheck'); ?>';
    var vtDirectUrl = '<?php echo Mage::getStoreConfig('payment/vtdirect/vtdirect_url'); ?>';
    var vtDirectClientKey = '<?php echo Mage::getStoreConfig('payment/vtdirect/client_key'); ?>';
    var creditCardPayment = '<?php echo Mage::getStoreConfig('bilna_module/success_page/payment_cc'); ?>';
    var creditCardPaymentArr = creditCardPayment.split(',');
    var ccDefaultMessageFailure = '<?php echo Mage::getStoreConfig('payment/vtdirect/default_response_message_failure'); ?>';
</script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/bilna_paymethod.js'); ?>"></script>

<div class="page-title">
    <h1><?php echo $this->__('Checkout'); ?></h1>
</div>

<ol class="opc" id="checkoutSteps">
    <?php $i = 0; foreach ($this->getSteps() as $_stepId => $_stepInfo): ?>
    <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++; ?>
        <li id="opc-<?php echo $_stepId; ?>" class="section<?php echo !empty ($_stepInfo['allow']) ? ' allow' : ''; ?><?php echo !empty ($_stepInfo['complete']) ? ' saved' : ''; ?>">
            <div class="step-title">
                <span class="number"><?php echo $i; ?></span>
                <h2><?php echo $_stepInfo['label']; ?></h2>
                <a href="#"><?php echo $this->__('Edit'); ?></a>
            </div>

            <div id="checkout-step-<?php echo $_stepId; ?>" class="step a-item" style="display:none;">
                <?php echo $this->getChildHtml($_stepId); ?>
            </div>
        </li>
    <?php endforeach; ?>
</ol>

<?php $items = $this->getItems();?>
<?php if (!empty($items)){?>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
        <?php $gtmItemIds = $_item->getId().'|'; ?>
    <?php endforeach; ?>
<?php }?>

<?php $cartItems = Mage::getSingleton('checkout/session')->getQuote()->getAllItems(); ?>
<?php $skuCollection = array(); ?>
<?php $productCollection = array(); ?>
<?php $qtyCollection = array(); ?>
<?php $valueCollection = array(); ?>
<?php $totalValue = 0; ?>
<?php $itemQty = 0; ?>
<?php foreach($cartItems as $cartItem) : ?>
    <?php $parentId = $cartItem->getParentItemId(); ?>
    <?php if(empty($parentId)): ?>
        <?php $skuCollection[] = $cartItem->getSku(); ?>
        <?php $productCollection[] = $cartItem->getProductId(); ?>
        <?php $qtyCollection[] = $cartItem->getQty(); ?>
        <?php $valueCollection[] = $cartItem->getPrice(); ?>
        <?php $totalValue += ($cartItem->getPrice() * $cartItem->getQty()); ?>
        <?php $itemQty++; ?>
    <?php endif ?>
<?php endforeach; ?>
<?php $skuDisplay =  implode("','", $skuCollection); ?>
<?php $productDisplay =  implode("','", $productCollection); ?>
<?php $qtyDisplay =  implode("','", $qtyCollection); ?>
<?php $valueDisplay =  implode("','", $valueCollection); ?>

<!-- ematic purchase integration point -->
<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $loggedinCustomerOrder = Mage::getModel('sales/order')->getCollection()
         ->setOrder('created_at','DESC')
         ->addAttributeToFilter('customer_email', Mage::getSingleton('customer/session')->getCustomer()->getEmail())
         ->setPageSize(1)
         ->setCurPage(1);
    $lastOrderDateTime = $loggedinCustomerOrder->getFirstItem()->getCreatedAt();
    $lastOrderDate = new DateTime($lastOrderDateTime);
    $lastOrderDate = $lastOrderDate->format('d-m-Y');
}
else {
    $lastOrderDate = date('d-m-Y');   
}
?>
<!-- END ematic purchase integration point -->

<script type="text/javascript">
    jQuery(document).ready(function () {
        dataLayer.push({'ecomm_pagetype': 'cart'});
        dataLayer.push({'productid': ['<?php echo $productDisplay; ?>']});
        dataLayer.push({'skuid': ['<?php echo $skuDisplay; ?>']});
        dataLayer.push({'prices': ['<?php echo $valueDisplay; ?>']});
        dataLayer.push({'quantities': ['<?php echo $qtyDisplay; ?>']});
    });
    //<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if ($this->getActiveStep()): ?>
        accordion.openSection('opc-<?php echo $this->getActiveStep(); ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress'); ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review'); ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod'); ?>',
        failure: '<?php echo $this->getUrl('checkout/cart'); ?>'}
    );
    //]]>

    /*** ematic purchase integration point ***/
    jQuery("#co-installment-form").submit(function(){
        if (jQuery("#checkout-step-login").length == 0) {   // user logged in and not checkout as guest
            ecommerceNewsletterSubscribe(document.getElementById('ematicuseremail').textContent);
        }
    });

    function ecommerceNewsletterSubscribe(email) {
        var subscribe_payload = {
          'apikey': '62dfde989b5d8d24c61f57fc3e0b42b1-us12',
          'id': '035ca58dc2',
          'email': {
             'email': email
          },
          "merge_vars": {
            "LASTPURCDT": <?php echo $lastOrderDate ?>
          }
        };

        jQuery.ajax({
          type: "POST",
          url: "https://us12.api.mailchimp.com/2.0/lists/update-member",
          dataType: "jsonp",
          data: subscribe_payload
        });
    }
    /*** END ematic purchase integration point ***/

    function ecommercePurchases() {
        var temp_container = {
            'event': 'purchase',
            'ecommerce': {
              'purchase': {
                'actionField': {
                    'shipping' : parseInt(jQuery("#checkout-review-table-wrapper table#checkout-review-table tfoot tr td:contains('Shipping & Handling')").next().text().replace(/[^0-9\.]/g, ""), 10),
                    'coupon' : jQuery("#checkout-review-table-wrapper table#checkout-review-table tfoot tr:contains('Discount') td:first").text().toString().substring(jQuery("#checkout-review-table-wrapper table#checkout-review-table tfoot tr:contains('Discount') td:first").text().indexOf("(")+1,jQuery("#checkout-review-table-wrapper table#checkout-review-table tfoot tr:contains('Discount') td:first").text().indexOf(")")),
                    'list' : 'browsing'
                },
                'products': []
             }
           }
        }

        // ematics cart - retrieve items from cart
        var temp_cart = [];
        var temp_item = "";
        var index_removeditem = "";
        var temp_cartQty = jQuery(".mini-cart span#ematiccart").length;
        for (var itr=0; itr < temp_cartQty; itr++) {
            temp_item = jQuery(".mini-cart span#ematiccart").eq(itr).text();
            temp_cart[itr] = temp_item.split("|");
        }

        // ematics cart - prepare for logging
        products = [
        <?php for($i=0; $i<$itemQty; $i++) {
            echo "{'name' : temp_cart[".$i."][0],";
            echo "'id' : temp_cart[".$i."][1],";
            echo "'price' : temp_cart[".$i."][3],";
            echo "'quantity' : temp_cart[".$i."][4],";
            echo "'brandName' : 'brand name',";
            echo "'imageUrl' : temp_cart[".$i."][5],";
            echo "'link' : temp_cart[".$i."][6]}";if($i != $itemQty-1) {echo ",";}
        } 
        ?>
        ];

        // ematics track convert
        ematics("log", "product", "convert", products);

        // universal analytics
        temp_container.ecommerce.purchase.products.push(
            <?php for($i=0; $i<$itemQty; $i++) {
                echo "{'name' : temp_cart[".$i."][0],";
                echo "'sku' : temp_cart[".$i."][1],";
                echo "'price' : temp_cart[".$i."][2],";
                echo "'quantity' : temp_cart[".$i."][4],";
                echo "'brandName' : 'brand name',";
                echo "'imageUrl' : temp_cart[".$i."][5],";
                echo "'link' : temp_cart[".$i."][6]}";if($i != $itemQty-1) {echo ",";}
            } 
            ?>
        );
        dataLayer.push(temp_container);
    }
</script>

<!-- BEGIN - Moved from app/design/frontend/base/default/template/checkoutpromo/checkoutpromo.phtml -->
<?php
$url = $this->getUrl('checkout/cart/customCheckoutCouponPost');
$url = Mage::helper('paymethod')->checkHttpsProtocol($url);
Mage::getSingleton('core/session')->setSessionCouponMessage('');
$session = Mage::getSingleton('checkout/session');
$points_amount = $session->getData('points_amount');
?>
<script type="text/javascript">
    var usePointWithCoupon = <?php echo Mage::getStoreConfig('points/general/use_with_coupons'); ?>;

    function cekCustomVoucher(isRemove)
    {
        jQuery(".button btn-checkout").attr("disabled", true);
        var remove = 0;
        if(isRemove)
        {
            remove = 1;
        }else{
            remove = 0;
        }
        //alert($('points_amount').value);

        //var url = '<?php echo $this->getUrl('checkout/cart/customCheckoutCouponPost') ?>';
        var url = '<?php echo $url; ?>';
        jQuery.ajax({
            type: "POST",
            url : url,
            data: { coupon_code: jQuery('#coupon_code').val(), remove: remove},
            beforeSend: function( xhr ) {
                $('feedback').setStyle('color: green;').update('Checking Coupon Code ... <img src="<?php echo $this->getSkinUrl("ajaxlogin/ajax-loader-tr.gif")?>" title="Loading..." alt="Loading..." border="0" />');
            },
            success: function(res){
                if(res.status == 1){
                    $('feedback').update(res.desc).setStyle('color: green;');
                    if (usePointWithCoupon != 1) {
                        if($('use_points')){
                            $('use_points').disabled = $('points_amount').disabled = true;
                        }
                    }
                }else{
                    if (usePointWithCoupon != 1) {
                        if($('use_points')){
                            $('use_points').disabled = $('points_amount').disabled = false;
                        }
                    }
                    $('feedback').update(res.desc).setStyle('color: red;');
                }
                setTimeout(function(){
                    jQuery(".button btn-checkout").attr("disabled", false);
                }, 1000);
                payment.save();
            },
            error: function() {
                $('feedback').update(res.desc);
            }
        });

        return false;
    }
</script>
<!-- END  - Moved from app/design/frontend/base/default/template/checkoutpromo/checkoutpromo.phtml -->
