<?php
$x = $this->productsScriptAction();
//print_r($x);
?>
<!DOCTYPE html>
<html>
<head>
    <title>Advertisement</title>
    <meta charset="utf-8">
</head>
<body marginwidth="0" marginheight="0" style="background-color:transparent; width: 100%; text-align: center;" topmargin="0" leftmargin="0">
    <div id="main4b414196be" style="width:320px;height:50px;border: 1px solid #20C5DF;position:relative;padding:0px;background-color:#fff;cursor:pointer;overflow:hidden;margin-left:auto;margin-right:auto;">
        <div id="cto_banner_content">
            <style>
                .thumb {
                    position: relative;
                    width: 84px;
                    height: 80px;
                    border: 1px solid #FF9B42;
                    padding: 0px;
                    margin: 1px;
                    float: left
                }
                .thumb img{
                    padding: 2px ;
                }
                .logo_banner{
                    padding: 0px 0px 0px 0px ;   
                }
                .text {
                    display: none;
                    position: absolute;
                    left: 0;
                    bottom: 0;
                    width: 100%;
                    height: 100%;
                    background: #fff;
                    background: rgba(0,0,0,0.1);
                    text-align: center;
                    font-size: 9px;
                    color: #20C5DF;
                    font-weight: bold;
                }
                .thumb:hover .text {
                    display: block
                }
            </style>
            <div id="cto_banner_content" class="ad">
                <?php foreach($x as $row):?>
                <a href="<?php echo $row['a'];?>" alt="<?php echo $row['name'];?>">
                <div class="thumb">
                    <?php echo $row['img']; ?>
                    <span class="text"><?php echo $row['name'];?><p style="font-size: 9px;"><?php echo $row['price']['old_price'];?></p></span>
                </div>
                </a>
                <?php endforeach; ?>
                <div class="logo_banner">
                    <img src="http://dummyimage.com/150x100/ccc/fff" height="18px"/>
                    <span class="text">text text text text text text text</span>
                </div>
            </div>
        </div>
    </div>
</body>
</html>