<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Collpur
 * @version    1.0.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>

<!--div id="messages_product_view"><?php //echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class>
</div-->

<?php if ($this->isNative()): ?>
<!--<div class="awcp-navigation">
	<ul class="row">
		<?php //foreach($this->getMenus() as $menu): ?>
		   <?php //if($this->_tabIsAllowed($menu)): ?>
				<li <?php //echo $this->checkCurrentTab($menu['key']); ?>><a
				href="<?php //echo $this->getDealTabUrl($menu['key']); ?>"><?php //echo $menu['title']; ?></a></li>
		   <?php //endif; ?>
		<?php //endforeach; ?>
	</ul>
	<div class="clearer"></div>
</div>-->
<?php endif; ?>
<?php if($this->getAvailableDeals()->count() == 0):  ?>
    <h2 id = "awcp-nodeals-available"><?php echo $this->__('No deals available'); ?></h2>
    <?php return; ?>
<?php endif; ?>
<div class="row-list">
	<?php if(is_null($this->getType()) || $this->getType()<>"detail"){ ?>
	<!--slider-->
	<?php echo $this->getLayout()->createBlock('collpur/deals')->setTemplate('aw_collpur/deals/slider.phtml')->toHtml(); ?>
	<!--end slider-->
	<div class="row">
	<?php echo $this->getChildHtml('available_deals_pager'); ?>
	</div>
	</div>
	<?php } ?>
	<ul class="awcp-category-grid medium-block-grid-3 large-block-grid-3">
    <?php $i = 0; foreach($this->getAvailableDeals() as $deal): ?>
	<?php
						$product = $this->getProduct ( $deal );
						$originalProduct = $this->getOriginalProduct ( $deal );
						$dealInfo = $this->getDealPricesSpare ( $originalProduct, $product );
						?>
      <li class="awcp-item <?php /*if(!$i || $i%2 == 0) { echo 'first'; } else { echo 'last'; }*/ ?> column small-12 medium-4 large-4">
			<div class="wrap_li">
				<a class="awcp-product-image small-6 column large-12 medium-12" 
					href="<?php echo $this->getDealPageLink($deal->getId()); ?>"><img
					src="<?php echo $this->getDealImage($deal->getDealImage()); ?>"
					alt="<?php echo $deal->getDealName(); ?>" /></a>
				<div class="awcp-mark-center small-6 column large-12 medium-12">
					<div class="awcp-details inprogress">
						<div class="list_detail_left  column small-12 large-8 medium-7">
							<h2 class="awcp-title-list">
								<a href="<?php echo $this->getDealPageLink($deal->getId()); ?>"><?php echo $deal->getDealName(); ?></a>
							</h2>
							<p class="desc_short_deals"><?php echo $this->filter($deal->getDescription()); ?></p>
							<div class="price_deals_list"><?php echo Mage::helper('core')->currency($deal->getPrice(), true, false); ?></div>
					   <?php //if(!$deal->isClosed()): ?>
							<?php //$container = "awcp_timer_".rand(); ?>
						   <?php //if($deal->isNotRunning() && $deal->getAvailableFrom()): ?>
								<!--<div class="awcp-date" id="<?php //echo $container; ?>"><?php //echo $this->getTimeLeftToBuy($deal,$time = 'available_from'); ?></div>
							<?php //elseif($deal->isRunning() && $deal->getAvailableTo()): ?>
								<div class="awcp-date" id="<?php //echo $container; ?>"><?php //echo $this->getTimeLeftToBuy($deal); ?></div>
							<?php //else: ?>
								 <div class="awcp-date awcp-date-empty"
								id="<?php //echo $container; ?>">&nbsp;</div>
							<?php //endif; ?>
		 
							  <?php //if($data = $this->getJsonConfig($deal->getId())): ?>
								<script type="text/javascript">
									document.observe("dom:loaded", function() {
									   new AwcpCollpur(<?php //echo $this->getJsonConfig($deal->getId()) ; ?>,"<?php //echo $container; ?>");
									});
								</script>-->
							  <?php //endif; ?>
					   <?php //endif; ?>
					</div>
						<div class="list_detail_right small-12 column large-4 medium-5">
							<form id="product_addtocart_form" class="right_detail_deals"
								method="post"
								action="<?php echo Mage::getUrl('checkout/cart/add', array('_secure'=>true,'product' => $deal->getProduct()->getId(), 'deal_id' => $deal->getId(), 'form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>">
								<div
									class="awcp-buy-button <?php if ($this->hasOptions($deal)): ?>awcp-options<?php endif; ?>">
									<!-- POPUP -->
									<div class="awcp-popup awcp-popup-shown" style="display: none;"
										id="awcp-popup-options<?php echo $deal->getId(); ?>">
										<div class="awcp-popup-top-left">
											<div class="awcp-popup-top-right"></div>
										</div>
										<div class="awcp-popup-center-left">
											<div class="awcp-popup-center-right">
												<div class="awcp-popup-content">
											<?php echo $this->getChildHtml('main_collpur_block'); ?>
										</div>
											</div>
										</div>
										<div class="awcp-popup-bottom-left">
											<div class="awcp-popup-bottom-right">
												<button class="button awcp-button">
													<span><span><?php echo $this->__('BUY NOW'); ?></span></span>
												</button>
											</div>
										</div>
										<div class="awcp-popup-tail"></div>
									</div>
									<!-- popup -->
									<button class="button awcp-button"
										<?php if ($this->hasOptions($deal)): ?>
										onclick="Effect.toggle($('awcp-popup-options<?php echo $deal->getId(); ?>'),'appear');return false;"
										<?php endif; ?>>
										<span>
											<?php echo $this->__('BUY NOW'); ?>
									</span>
									</button>
								</div>
							</form>
						<?php if($originalProduct->getPrice() != 0){ ?>
						<p class="product_price"><?php echo Mage::helper('core')->currency($originalProduct->getPrice(), true, false); ?></p>
							<p class="discount"><?php echo $dealInfo->getPercentDiscount(); ?>% OFF</p>
						<?php } ?>
						<form id="product_addtocart_form" class="right_detail_deals_2"
								method="post"
								action="<?php echo Mage::getUrl('checkout/cart/add', array('_secure'=>true,'product' => $deal->getProduct()->getId(), 'deal_id' => $deal->getId(), 'form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>">
								<div
									class="awcp-buy-button <?php if ($this->hasOptions($deal)): ?>awcp-options<?php endif; ?>">
									<!-- POPUP -->
									<div class="awcp-popup awcp-popup-shown" style="display: none;"
										id="awcp-popup-options<?php echo $deal->getId(); ?>">
										<div class="awcp-popup-top-left">
											<div class="awcp-popup-top-right"></div>
										</div>
										<div class="awcp-popup-center-left">
											<div class="awcp-popup-center-right">
												<div class="awcp-popup-content">
													<?php echo $this->getChildHtml('main_collpur_block'); ?>
												</div>
											</div>
										</div>
										<div class="awcp-popup-bottom-left">
											<div class="awcp-popup-bottom-right">
												<button class="button awcp-button">
													<span><span><?php echo $this->__('BUY NOW'); ?></span></span>
												</button>
											</div>
										</div>
										<div class="awcp-popup-tail"></div>
									</div>
									<!-- popup -->
									<button class="button awcp-button"
										<?php if ($this->hasOptions($deal)): ?>
										onclick="Effect.toggle($('awcp-popup-options<?php echo $deal->getId(); ?>'),'appear');return false;"
										<?php endif; ?>
										<span>
												<?php echo $this->__('BUY NOW'); ?>
										</span>
									</button>
								</div>
							</form>
					</div>
						<div class="clearer"></div>
					</div>
				</div>
			</div>
		</li>      
     <?php $i++; endforeach; ?> 
	</ul>
	<?php if(is_null($this->getType()) || $this->getType()<>"detail"){ ?>
	<div class="clearer"></div>
	<div class="row">
	<?php echo $this->getChildHtml('available_deals_pager'); ?>
	</div>
	<?php } ?>
</div>
 <!-- Incorrect view of buttons in catalog -->
 <style>
 button.button span span {height:auto!important;}
 </style>


