<?php $posts = $this->getCategoriesPosts(); 
$slider = $this->getSliderPost();
?>

    <div>
		
		<div class="postWrapper">
				<div style="padding:0 0 55px 0 ;margin: 0 2%; max-width: 762px; clear: both;border: 8px solid #FFFFFF; box-shadow: 0 0 7px rgba(0, 0, 0, 0.22); display: none;">
					
					<!--slide jcobb-->
					
					<div id="banner-slide" style="display: none;">

						<ul class="bjqs">
						  <?php foreach ($slider as $row): ?>
						  <li>
								<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?><?php echo $row->getImageName();?>" /></br>
								<div class="postTitle" style="clear: both;">
									<h2><?php echo $row->getTitle(); ?></h2>
									<p style="padding-right: 10px;">
										<?php echo $row->getShortContent(); ?>
									</p>
									<a class="aw-blog-read-more" href="<?php echo $row->getAddress(); ?>">Read more</a>
								</div>
								<div style="clear: both;"></div>
						  </li>
							<?php endforeach; ?> 
						</ul>
						
					</div>
					
					<script class="secret-source">
						jQuery(document).ready(function($) {
						  
						  $('#banner-slide').bjqs({
							animtype      : 'slide',
							height        : 446,
							width         : 762,
							responsive    : true,
							randomstart   : true,
							responsive 	  : true
						  });
						  
						});
					</script>
					
					<script>
						jQuery(function($) {

							$('.secret-source').secretSource({
								includeTag: false
							});

						});
					</script>
					
					
					
					
					
					<!--END slide jcobb-->
					<div style="clear: both;"></div>
				</div>
		</div>
			<?php $j=0; foreach ($posts as $key => $post): ?>
				<?php 
					echo $this->getLayout()->createBlock('core/template')
						->setTemplate('aw_blog/'.$post['layout'])
						->setData('catPosts', array('posts' => $post['post'], 'cat' => $post['catName'], 'subCat' => $post['subName']) )
						->toHtml();
				?>
			<?php $j++; endforeach; ?> 
		
    </div>