<!DOCTYPE HTML>
<html>

<body>

<div>
<div class="postWrapper">
        <div class="postTitle">
            <h2><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/">Test 2 Image weeewww</a></h2>
            <h3>Friday, January 3, 2014 3:59:57 PM Asia/Bangkok</h3>
        </div>
        <div class="postContent"><p><img alt="" src="http://192.168.2.31/bilna-baru/media/wysiwyg/banner-special/banner-friso.jpg" style="float: left;">Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p><a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/" class="aw-blog-read-more">Read More</a></div>

                <div class="tags"><div style="position:relative; border:1px dotted red; margin:6px 2px; padding:18px 2px 2px 2px; zoom:1;">
<div title="frontend\default\default\template\aw_blog/line_tags.phtml" onmouseout="this.style.zIndex='998'" onmouseover="this.style.zIndex='999'" style="position:absolute; left:0; top:0; padding:2px 5px; background:red; color:white; font:normal 11px Arial;
text-align:left !important; z-index:998;">frontend\default\default\template\aw_blog/line_tags.phtml</div><h4>Tags:</h4><br>
<ul class="tags">
            <li><a href="http://192.168.2.31/bilna-baru/news/tag/weeewww/">weeewww</a></li>
            <li><a href="http://192.168.2.31/bilna-baru/news/tag/oooiiii/">oooiiii</a></li>
    </ul></div></div>
        <div class="postDetails">
                            2 <a href="http://192.168.2.31/bilna-baru/news/test-blog-weeeewww/#commentBox">Comments</a> |
                                                    Posted in                                    <a href="http://192.168.2.31/bilna-baru/news/cat/diaper-blog/">Diaper Blog</a>
                            By bernadus Dodo Putranto</div>
    </div>



</div>

</body>
</html>