<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Islider
 * @version    1.3.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<script type="text/javascript">
	$j(function() {
      $j('#slides').slidesjs({
        width: 750,
        height: 333,
        pagination: {
	      active: true,
	        // [boolean] Create pagination items.
	        // You cannot use your own pagination. Sorry.
	      effect: "slide"
	        // [string] Can be either "slide" or "fade".
	    }
      });
    });
</script>
<?php $helper = Mage::helper('awislider') ?>
<?php if($this->canDisplay() && $this->getSlides()->getSize()) : ?>
<div id="slides">
  <?php $_i = 0 ?>
    <?php foreach($this->getSlides() as $slide) : ?>
 		<?php if($slide->getData('url')) : ?>
        <a href="<?php echo $helper->getUseDirectLinks() ? $slide->getData('url') : $this->getUrl('awislider/link/out', array('sid' => $slide->getData('id'))) ?>"<?php if($slide->getData('new_window')) : ?> onclick="return !window.open(this.href)"<?php endif ?><?php if($slide->getData('nofollow')) : ?> rel="nofollow"<?php endif ?>>
        <?php endif ?>
            <img src="<?php echo ($slide->getUriLocation()) ?>" title="<?php echo htmlspecialchars($slide->getData('title')) ?>" alt="<?php echo htmlspecialchars($slide->getData('title')) ?>" />
        <?php if($slide->getData('url')) : ?>
        </a>
        <?php endif ?>
    <?php $_i++ ?>
    <?php endforeach ?>
    
</div>
<script type="text/javascript">
    new awiSlider('<?php echo $this->getUniqueBlockId() ?>', {
        blockId: '<?php echo $this->getUniqueBlockId() ?>',
        effect: '<?php echo $this->getSwitchEffect() ?>',
        slidesCount: '<?php echo $_i ?>',
        animationSpeed: '<?php echo $this->getAnimationSpeed() ?>',
        firstFrameTimeout: '<?php echo $this->getFirstFrameTimeout() ?>',
        autohideNavigation: '<?php echo $this->getAutohideNavigation() ?>',
        needCalculateWH: <?php echo $this->getWidth() && $this->getHeight() ? '0' : '1' ?>
    });
    
    
</script>
<?php endif ?>
