<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Collpur
 * @version    1.0.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<!--slider 1-->
<?php $dealSliders = $this->getFeaturedSliders(); 
		$i = 0; 
		$max = count($dealSliders); ?>
<div class="row">
    <!-- use jssor.slider.min.js instead for release -->
    <!-- jssor.slider.min.js = (jssor.core.js + jssor.utils.js + jssor.slider.js) -->
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>jssor.core.js"></script>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>jssor.utils.js"></script>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>jssor.slider.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            var options = {
                $SlideDuration: 500,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                $DirectionNavigatorOptions: {
                    $Class: $JssorDirectionNavigator$,              //[Requried] Class to create direction navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
                },
                $ThumbnailNavigatorOptions: {
                    $Class: $JssorThumbnailNavigator$,              //[Required] Class to create thumbnail navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always

                    $AutoCenter: 3,                                 //[Optional] Auto center thumbnail items in the thumbnail navigator container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 3
                    $Lanes: 1,                                      //[Optional] Specify lanes to arrange thumbnails, default value is 1
                    $SpacingX: 2,                                   //[Optional] Horizontal space between each thumbnail in pixel, default value is 0
                    $SpacingY: 2,                                   //[Optional] Vertical space between each thumbnail in pixel, default value is 0
                    $DisplayPieces: 4,                              //[Optional] Number of pieces to display, default value is 1
                    $ParkingPosition: 0,                            //[Optional] The offset position to park thumbnail
                    $Orientation: 2,                                //[Optional] Orientation to arrange thumbnails, 1 horizental, 2 vertical, default value is 1
                    $DisableDrag: false                             //[Optional] Disable drag or not, default value is false
                }
            };

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider1.$SetScaleWidth(parentWidth);
                else
                    window.setTimeout(ScaleSlider, 30);
            }

            //Scale slider immediately
            ScaleSlider();

            if (!navigator.userAgent.match(/(iPhone|iPod|iPad|BlackBerry|IEMobile)/)) {
                $(window).bind('resize', ScaleSlider);
            }
            //responsive code end
        });
    </script>
	<div class="slider_area">
    <!-- Jssor Slider Begin -->
    <!-- You can move inline styles (except 'top', 'left', 'width' and 'height') to css file or css block. -->
    <div id="slider1_container" style="position: relative; width: 1143px; height: 430px; overflow: hidden;">
        <!-- Slides Container -->
        <div class="slider_img" u="slides" style="cursor: move; position: absolute; width: 943px; height: 430px; top: 0px;
            left: 0px; overflow: hidden;">
            <?php 
			$i = 0; 
			foreach($dealSliders as $dealSlider){ 
				$product = $this->getProduct ( $dealSlider );
				$originalProduct = $this->getOriginalProduct ( $dealSlider );
				$dealInfo = $this->getDealPricesSpare ( $originalProduct, $product );
			?>
            <div>
				<? $url = Mage::getBaseUrl('media').'aw_collpur/deals/'.$dealSlider['deal_image_slider']; ?>
            	<img u="image" src="<?php echo $url; ?>" />
                <div u="thumb">
                    <img class="i" src="<?php echo $this->getDealImage($dealSlider->getDealImage()); ?>" />
                    <div class="t"><?php echo $dealSlider->getDealName(); ?></div>
                    <div class="c"><?php if($dealInfo->getPercentDiscount() <> "0") { echo $dealInfo->getPercentDiscount(); ?>% OFF<?php } ?></div>
                </div>
                <div u="caption" t="MCLIP|B" style="position: absolute; bottom: 0px; left: 0px; right: 0px; height: auto; padding:10px 0; background-color: Black; opacity: 0.8; filter: alpha(opacity=80);">
                    <div style="display: block; color: #fff; font-size: 16px; font-weight: bold; ">
						<div class="orbit-caption">
							<div class="column large-5 medium-5">
								<label>TODAY'S DEALS</label>
								<p class="judul_deals_slider"><?php echo $dealSlider->getDealName(); ?></p>
								<div class="price_deals_slider">
									<p><?php echo Mage::helper('core')->currency($dealSlider->getPrice(), true, false); ?></p>
										<div class="after_price">
											<?php if($originalProduct->getFinalPrice() > 0) echo "<p>".Mage::helper('core')->currency($originalProduct->getFinalPrice(), true, false)."</p>"; ?>
											<p><?php if($dealInfo->getPercentDiscount() <> "0") { echo $dealInfo->getPercentDiscount(); ?>% OFF<?php } ?></p>
										</div>
								</div>
							</div>
							<div class="column large-3 medium-3 date_slider_deals">
								<label>PROMO END IN:</label>
								<p><?php echo $this->getTimeLeftToBuy($dealSlider); ?></p>
								<p>hour(s) minute(s) second(s)</p>
								<p>SOLD: <span><?php echo $this->getPurchasesCount($dealSlider->getId()); ?></span></p>
							</div>
							<div class="column large-4 medium-4">
								<form	id="product_addtocart_form" class="right_detail_deals"
										method="post"
										action="<?php echo Mage::getUrl('checkout/cart/add', array('_secure'=>true,'product' => $dealSlider->getProduct()->getId(), 'deal_id' => $dealSlider->getId(), 'form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>">
									<div class="awcp-buy-button <?php if ($this->hasOptions($dealSlider)): ?>awcp-options<?php endif; ?>">
										<!-- POPUP -->
										<div class="awcp-popup awcp-popup-shown" style="display: none;"
										id="awcp-popup-options<?php echo $dealSlider->getId(); ?>">
											<div class="awcp-popup-top-left">
												<div class="awcp-popup-top-right"></div>
											</div>
											<div class="awcp-popup-center-left">
												<div class="awcp-popup-center-right">
													<div class="awcp-popup-content"><?php echo $this->getChildHtml('main_collpur_block'); ?></div>
												</div>
											</div>
											<div class="awcp-popup-bottom-left">
												<div class="awcp-popup-bottom-right">
													<button class="button awcp-button">
														<span><span><?php echo $this->__('BUY NOW'); ?></span></span>
													</button>
												</div>
											</div>
											<div class="awcp-popup-tail"></div>
										</div>
										<!-- popup -->
										<button class="button awcp-buy" <?php if ($this->hasOptions($dealSlider)): ?>onclick="Effect.toggle($('awcp-popup-options<?php echo $dealSlider->getId(); ?>'),'appear');return false;"<?php endif; ?>>
											<span><?php echo $this->__('BUY</br>NOW'); ?></span>
										</button>
									</div>
								</form>
							</div>
						</div>
                    </div>
                </div>
            </div>
			<?php
				$i++;
			}
			?>
        </div>
        <!-- ThumbnailNavigator Skin Begin -->
        <div u="thumbnavigator" class="jssort11" style="position: absolute; width: 200px; height: 430px; right:0px; top: 0px; bottom:0px;">
            <!-- Thumbnail Item Skin Begin -->
            <style>
                /* jssor slider thumbnail navigator skin 11 css */
                /*
                .jssort11 .p            (normal)
                .jssort11 .p:hover      (normal mouseover)
                .jssort11 .pav          (active)
                .jssort11 .pav:hover    (active mouseover)
                .jssort11 .pdn          (mousedown)
                */
                .jssort11
                {
                	font-family: Arial, Helvetica, sans-serif;
                }
                .jssort11 .i, .jssort11 .pav:hover .i
                {
                	position: relative;
                	WIDTH: 60px;
                	HEIGHT: 30px;
					margin:0 0 0 3px;
                }
                * html .jssort11 .i
                {
                	WIDTH /**/: 62px;
                	HEIGHT /**/: 32px;
                }
                .jssort11{
                	background-color: #000;
                }
                .jssort11 .pav .i
                {
                	border: white 1px solid;
                }
                .jssort11 .t, .jssort11 .pav:hover .t
                {
					overflow:hidden;
					text-overflow:ellipsis;
					white-space:nowrap;
                	position: relative;
					margin:24px 0 0 7px;
                	color:#fff;
                	font-size:13px;
                }
				 .jssort11 .pav .t, .jssort11 .pav:hover .t{
					font-size:16px;
				}
                .jssort11 .pav .t, .jssort11 .phv .t, .jssort11 .p:hover .t
                {
                	color:#fff;
                }
                .jssort11 .c, .jssort11 .pav:hover .c
                {
                	position: relative;
                	color:#fff;
					margin:10px 0 0 7px;
                	font-size:17px;
                	font-weight:bold;
                	overflow: hidden;
                }
                .jssort11 .pav .c, .jssort11 .phv .c, .jssort11 .p:hover .c
                {
                	color:#fff;
                }
                .jssort11 .t, .jssort11 .c
                {
                	transition: color 2s;
                    -moz-transition: color 2s;
                    -webkit-transition: color 2s;
                    -o-transition: color 2s;
                }
                .jssort11 .p:hover .t, .jssort11 .phv .t, .jssort11 .pav:hover .t, .jssort11 .p:hover .c, .jssort11 .phv .c, .jssort11 .pav:hover .c
                {
                	transition: none;
                    -moz-transition: none;
                    -webkit-transition: none;
                    -o-transition: none;
                }
                .jssort11 .p
                {
                	background:#181818;
                }
                .jssort11 .pav, .jssort11 .pdn
                {
                	background:#f75a2f;
                }
                .jssort11 .p:hover, .jssort11 .phv, .jssort11 .pav:hover
                {
                	background:#333;
                }
            </style>
            <div u="slides" style="cursor: move; position: absolute; width: 200px; height: 100%;">
                <div u="prototype" class="p" style="position: absolute; width: 200px; height: 100%;">
                    <thumbnailtemplate style=" width: 100%; height: 100%; border: none;position:absolute;"></thumbnailtemplate>
                </div>
            </div>
            <!-- Thumbnail Item Skin End -->
        </div>
        <!-- ThumbnailNavigator Skin End -->
        <!-- Direction Navigator Skin Begin -->
        <style>
		            /* jssor slider direction navigator skin 20 css */
		            /*
		            .jssord20l              (normal)
		            .jssord20r              (normal)
		            .jssord20l:hover        (normal mouseover)
		            .jssord20r:hover        (normal mouseover)
		            .jssord20ldn            (mousedown)
		            .jssord20rdn            (mousedown)
		            */
		            .jssord20l, .jssord20r, .jssord20ldn, .jssord20rdn
		            {
		            	position: absolute;
		            	cursor: pointer;
		            	display: block;
		                background: url(../img/d20.png) no-repeat;
		                overflow:hidden;
		            }
		            .jssord20l { background-position: -3px -33px; }
		            .jssord20r { background-position: -63px -33px; }
		            .jssord20l:hover { background-position: -123px -33px; }
		            .jssord20r:hover { background-position: -183px -33px; }
		            .jssord20ldn { background-position: -243px -33px; }
		            .jssord20rdn { background-position: -303px -33px; }
		            
 	                #slider1_container .i, #slider1_container .i
 	                {
 	                	position: relative;
 	                	margin:3px 3px 0;
 	                }
 	                #slider1_container .i
 	                {
						float:left;
 	                	WIDTH /**/: 94px;
 	                	HEIGHT /**/: 95px;
 	                }
		        </style>
        <!-- Arrow Left -->
        <span u="arrowleft" class="jssord20l" style="width: 55px; height: 55px; top: 123px; left: 8px;">
        </span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssord20r" style="width: 55px; height: 55px; top: 123px; right: 8px">
        </span>
        <!-- Direction Navigator Skin End -->
        <a style="display: none" href="http://www.jssor.com">jQuery Slideshow</a>
    </div>
    <!-- Jssor Slider End -->
	</div>
	
</div>
<!--end slider 1-->


<!--slider 2-->
<!-- it works the same with all jquery version from 1.3.1 to 2.0.3 -->
   
    <script>
        jQuery(document).ready(function ($) {

            var options = {
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                $SlideDuration: 900,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $DirectionNavigatorOptions: {
                    $Class: $JssorDirectionNavigator$,              //[Requried] Class to create direction navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
                }
            };

            var jssor_slider1 = new $JssorSlider$("slider2_container", options);
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider1.$SetScaleWidth(parentWidth);
                else
                    window.setTimeout(ScaleSlider, 30);
            }

            //Scale slider immediately
            ScaleSlider();

            if (!navigator.userAgent.match(/(iPhone|iPod|iPad|BlackBerry|IEMobile)/)) {
                $(window).bind('resize', ScaleSlider);
            }
            //responsive code end
        });
    </script>
    <!-- Jssor Slider Begin -->
    <!-- You can move inline styles (except 'top', 'left', 'width' and 'height') to css file or css block. -->
    <div id="slider2_container" style="position: relative; width: 960px; height: 380px; overflow: hidden;">
        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; width: 960px; height: 380px; top: 0px;
            left: 0px; overflow: hidden;">
            <div><img u="image" src="../img/home/01.jpg" /></div>
            <div><img u="image" src="../img/home/02.jpg" /></div>
            <div><img u="image" src="../img/home/03.jpg" /></div>
        </div>
        <!-- Direction Navigator Skin Begin -->
        <style>
            /* jssor slider direction navigator skin 20 css */
            /*
            .jssord20l              (normal)
            .jssord20r              (normal)
            .jssord20l:hover        (normal mouseover)
            .jssord20r:hover        (normal mouseover)
            .jssord20ldn            (mousedown)
            .jssord20rdn            (mousedown)
            */
            .jssord20l, .jssord20r, .jssord20ldn, .jssord20rdn
            {
            	position: absolute;
            	cursor: pointer;
            	display: block;
                background: url(../img/d20.png) no-repeat;
                overflow:hidden;
            }
            .jssord20l { background-position: -3px -33px; }
            .jssord20r { background-position: -63px -33px; }
            .jssord20l:hover { background-position: -123px -33px; }
            .jssord20r:hover { background-position: -183px -33px; }
            .jssord20ldn { background-position: -243px -33px; }
            .jssord20rdn { background-position: -303px -33px; }
        </style>
        <!-- Arrow Left -->
        <span u="arrowleft" class="jssord20l" style="width: 55px; height: 55px; top: 123px; left: 8px;">
        </span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssord20r" style="width: 55px; height: 55px; top: 123px; right: 8px">
        </span>
        <!-- Direction Navigator Skin End -->
        <a style="display: none" href="http://www.jssor.com">jQuery Slideshow</a>
    </div>
    <!-- Jssor Slider End -->
	
<!--end slider 2-->