<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Collpur
 * @version    1.0.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>

		<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>aw_collpur/jquery.cbpContentSlider.min.js"></script>
	<script>
			jQuery( document ).ready(function() {
				/*
				- how to call the plugin:
				$( selector ).cbpContentSlider( [options] );
				- options:
				{
					// default transition speed (ms)
					speed : 500,
					// default transition easing
					easing : 'ease-in-out',
					// current item's index
					current : 0
				}
				- destroy:
				$( selector ).cbpContentSlider( 'destroy' );
				*/

				console.log(123);
				jQuery( '#cbp-contentslider' ).cbpContentSlider();
			});
		</script>
<!--slider 2-->
	<div class="main">
	<div id="cbp-contentslider" class="cbp-contentslider">
					<ul>
						<li id="slide1">
							<img class="slider_img" src="media/wysiwyg/deals.jpg"/>
							<div>
								<div class="cbp-content">
									
										<div style="display: block; color: #fff; font-size: 16px; font-weight: bold; ">
											<div class="orbit-caption">
												<div class="column large-5 medium-5 small-12 desc_deals_slider2">
													<label>TODAY'S DEALS</label>
													<p class="judul_deals_slider">sdfsd s df s</p>
													<div class="price_deals_slider">
														<p>Rp120</p>
															<div class="after_price">
																<p>Rp700</p>											<p>82.9% OFF</p>
															</div>
													</div>
												</div>
												<div class="column large-4 medium-4 small-7 date_slider_deals">
													<label>PROMO END IN:</label>
													<p>241 : 27 : 32</p>
													<p>hour(s) minute(s) second(s)</p>
													<p>SOLD: <span>0</span></p>
												</div>
												<div class="column large-3 medium-3 small-5">
													<form action="http://localhost/bilna_2014/deals/checkout/cart/add/product/152/deal_id/7/form_key/SWkg5rW12tg72UuK/" method="post" class="right_detail_deals" id="product_addtocart_form">
														<div class="awcp-buy-button ">
															<!-- POPUP -->
															<div id="awcp-popup-options7" style="display: none;" class="awcp-popup awcp-popup-shown">
																<div class="awcp-popup-top-left">
																	<div class="awcp-popup-top-right"></div>
																</div>
																<div class="awcp-popup-center-left">
																	<div class="awcp-popup-center-right">
																		<div class="awcp-popup-content"></div>
																	</div>
																</div>
																<div class="awcp-popup-bottom-left">
																	<div class="awcp-popup-bottom-right">
																		<button class="button awcp-button">
																			<span><span>BUY NOW</span></span>
																		</button>
																	</div>
																</div>
																<div class="awcp-popup-tail"></div>
															</div>
															<!-- popup -->
															<button class="button awcp-buy">
																<span>BUY<br>NOW</span>
															</button>
														</div>
													</form>
												</div>
											</div>
										</div>
								</div>
							</div>
						</li>
						<li id="slide2">
							<img class="slider_img" src="media/wysiwyg/deals.jpg"/>
							<div>
								<div class="cbp-content">
									
										<div style="display: block; color: #fff; font-size: 16px; font-weight: bold; ">
											<div class="orbit-caption">
												<div class="column large-5 medium-5 small-12 desc_deals_slider2">
													<label>TODAY'S DEALS</label>
													<p class="judul_deals_slider">sdfsd s df s</p>
													<div class="price_deals_slider">
														<p>Rp120</p>
															<div class="after_price">
																<p>Rp700</p>											<p>82.9% OFF</p>
															</div>
													</div>
												</div>
												<div class="column large-4 medium-4 small-7 date_slider_deals">
													<label>PROMO END IN:</label>
													<p>241 : 27 : 32</p>
													<p>hour(s) minute(s) second(s)</p>
													<p>SOLD: <span>0</span></p>
												</div>
												<div class="column large-3 medium-3 small-5">
													<form action="http://localhost/bilna_2014/deals/checkout/cart/add/product/152/deal_id/7/form_key/SWkg5rW12tg72UuK/" method="post" class="right_detail_deals" id="product_addtocart_form">
														<div class="awcp-buy-button ">
															<!-- POPUP -->
															<div id="awcp-popup-options7" style="display: none;" class="awcp-popup awcp-popup-shown">
																<div class="awcp-popup-top-left">
																	<div class="awcp-popup-top-right"></div>
																</div>
																<div class="awcp-popup-center-left">
																	<div class="awcp-popup-center-right">
																		<div class="awcp-popup-content"></div>
																	</div>
																</div>
																<div class="awcp-popup-bottom-left">
																	<div class="awcp-popup-bottom-right">
																		<button class="button awcp-button">
																			<span><span>BUY NOW</span></span>
																		</button>
																	</div>
																</div>
																<div class="awcp-popup-tail"></div>
															</div>
															<!-- popup -->
															<button class="button awcp-buy">
																<span>BUY<br>NOW</span>
															</button>
														</div>
													</form>
												</div>
											</div>
										</div>
								</div>
							</div>
						</li>
						<li id="slide3">
							<img class="slider_img" src="media/wysiwyg/deals.jpg"/>
							<div>
								<div class="cbp-content">
									
										<div style="display: block; color: #fff; font-size: 16px; font-weight: bold; ">
											<div class="orbit-caption">
												<div class="column large-5 medium-5 small-12 desc_deals_slider2">
													<label>TODAY'S DEALS</label>
													<p class="judul_deals_slider">sdfsd s df s</p>
													<div class="price_deals_slider">
														<p>Rp120</p>
															<div class="after_price">
																<p>Rp700</p>											<p>82.9% OFF</p>
															</div>
													</div>
												</div>
												<div class="column large-4 medium-4 small-7 date_slider_deals">
													<label>PROMO END IN:</label>
													<p>241 : 27 : 32</p>
													<p>hour(s) minute(s) second(s)</p>
													<p>SOLD: <span>0</span></p>
												</div>
												<div class="column large-3 medium-3 small-5">
													<form action="http://localhost/bilna_2014/deals/checkout/cart/add/product/152/deal_id/7/form_key/SWkg5rW12tg72UuK/" method="post" class="right_detail_deals" id="product_addtocart_form">
														<div class="awcp-buy-button ">
															<!-- POPUP -->
															<div id="awcp-popup-options7" style="display: none;" class="awcp-popup awcp-popup-shown">
																<div class="awcp-popup-top-left">
																	<div class="awcp-popup-top-right"></div>
																</div>
																<div class="awcp-popup-center-left">
																	<div class="awcp-popup-center-right">
																		<div class="awcp-popup-content"></div>
																	</div>
																</div>
																<div class="awcp-popup-bottom-left">
																	<div class="awcp-popup-bottom-right">
																		<button class="button awcp-button">
																			<span><span>BUY NOW</span></span>
																		</button>
																	</div>
																</div>
																<div class="awcp-popup-tail"></div>
															</div>
															<!-- popup -->
															<button class="button awcp-buy">
																<span>BUY<br>NOW</span>
															</button>
														</div>
													</form>
												</div>
											</div>
										</div>
								</div>
							</div>
						</li>
						<li id="slide4">
							<img class="slider_img" src="media/wysiwyg/deals.jpg"/>
							<div>
								<div class="cbp-content">
									
										<div style="display: block; color: #fff; font-size: 16px; font-weight: bold; ">
											<div class="orbit-caption">
												<div class="column large-5 medium-5 small-12 desc_deals_slider2">
													<label>TODAY'S DEALS</label>
													<p class="judul_deals_slider">sdfsd s df s</p>
													<div class="price_deals_slider">
														<p>Rp120</p>
															<div class="after_price">
																<p>Rp700</p>											<p>82.9% OFF</p>
															</div>
													</div>
												</div>
												<div class="column large-4 medium-4 small-7 date_slider_deals">
													<label>PROMO END IN:</label>
													<p>241 : 27 : 32</p>
													<p>hour(s) minute(s) second(s)</p>
													<p>SOLD: <span>0</span></p>
												</div>
												<div class="column large-3 medium-3 small-5">
													<form action="http://localhost/bilna_2014/deals/checkout/cart/add/product/152/deal_id/7/form_key/SWkg5rW12tg72UuK/" method="post" class="right_detail_deals" id="product_addtocart_form">
														<div class="awcp-buy-button ">
															<!-- POPUP -->
															<div id="awcp-popup-options7" style="display: none;" class="awcp-popup awcp-popup-shown">
																<div class="awcp-popup-top-left">
																	<div class="awcp-popup-top-right"></div>
																</div>
																<div class="awcp-popup-center-left">
																	<div class="awcp-popup-center-right">
																		<div class="awcp-popup-content"></div>
																	</div>
																</div>
																<div class="awcp-popup-bottom-left">
																	<div class="awcp-popup-bottom-right">
																		<button class="button awcp-button">
																			<span><span>BUY NOW</span></span>
																		</button>
																	</div>
																</div>
																<div class="awcp-popup-tail"></div>
															</div>
															<!-- popup -->
															<button class="button awcp-buy">
																<span>BUY<br>NOW</span>
															</button>
														</div>
													</form>
												</div>
											</div>
										</div>
								</div>
							</div>
						</li>
						
					</ul>
					<nav>
						<a href="#slide1" class="thumb_image">
							<div u="thumb" class="slider_thumb_large" style="width: 100%; height: 100%; border: medium none; position: absolute;">
								<img src="http://www.stejing.com/media/catalog/product/placeholder/default/BILNAIMGPLACEHOLDER_1.jpg" class="i">
								<div class="t">sdfjgs hshsdfh osdfhos ols </div>
								<div class="c">69.4% OFF</div>
							</div>
						</a>
						<a href="#slide2" class="thumb_image">
							<div u="thumb" class="slider_thumb_large" style="width: 100%; height: 100%; border: medium none; position: absolute;">
								<img src="http://www.stejing.com/media/catalog/product/placeholder/default/BILNAIMGPLACEHOLDER_1.jpg" class="i">
								<div class="t">sdfjgs hshsdfh osdfhos ols </div>
								<div class="c">69.4% OFF</div>
							</div>
						</a>
						<a href="#slide3" class="thumb_image">
							<div u="thumb" class="slider_thumb_large" style="width: 100%; height: 100%; border: medium none; position: absolute;">
								<img src="http://www.stejing.com/media/catalog/product/placeholder/default/BILNAIMGPLACEHOLDER_1.jpg" class="i">
								<div class="t">sdfjgs hshsdfh osdfhos ols </div>
								<div class="c">69.4% OFF</div>
							</div>
						</a>
						<a href="#slide4" class="thumb_image">
							<div u="thumb" class="slider_thumb_large" style="width: 100%; height: 100%; border: medium none; position: absolute;">
								<img src="http://www.stejing.com/media/catalog/product/placeholder/default/BILNAIMGPLACEHOLDER_1.jpg" class="i">
								<div class="t">sdfjgs hshsdfh osdfhos ols </div>
								<div class="c">69.4% OFF</div>
							</div>
						</a>
						
					</nav>
					<div class="thumb_angka_area">
						<a href="#slide1" class="thumb_angka">
						1
						</a>
						<a href="#slide2" class="thumb_angka active">
						2
						</a>
						<a href="#slide3" class="thumb_angka">
						3
						</a>
						<a href="#slide4" class="thumb_angka">
						4
						</a>
						</div>
				</div>
				</div>
				
			
<!--end slider 2-->