<?php
/**
 * Class Me_Gravity_Block_Js_Gravity
 *
 * @category  Me
 * @package   Me_Gravity
 * @author    Attila Sági <sagi.attila@magevolve.com>
 * @copyright 2014 Magevolve Ltd. (http://magevolve.com)
 * @license   http://magevolve.com/terms-and-conditions Magevolve Ltd. License
 * @link      http://magevolve.com
 */
?>
<?php
/**
 * Gravity initialization script
 *
 * var $this Me_Gravity_Block_Page_Js_Gravity
 * @see Me_Gravity_Block_Page_Js_Gravity
 */
?>
<?php
$store				=Mage::app()->getStore();
$collection = Mage::getResourceModel('catalog/category_collection')
                ->setStoreId($store->getId())
                ->addNameToResult();
$layer = Mage::getSingleton('catalog/layer');
if(isset($layer)){
$_category = $layer->getCurrentCategory();
$currentCategoryId= $_category->getId();
$_cat = Mage::getModel('catalog/category')->load($currentCategoryId);
$structure = preg_split('#/+#', $_cat->getPath());
for($j=0; $j<count($structure); $j=$j+1){
	$structure[$j]=$collection->getItemById($structure[$j])->getName();
}
$currentCategoryPath = implode("/", $structure);

?>
		<script>
	var _gravity = _gravity || [];
	_gravity.push({type: 'set', categoryPath: '<?=$currentCategoryPath?>'});
</script>
<?php } ?>
<?php if ($this->isEnabled() && $this->getGravityCustomerId()) : ?>
    <?php $gravityHelper = $this->getGravityHelper(); ?>
    <?php if ($this->isCustomJsEnabled()) : ?>
        <?php echo $this->getCustomJsContent(); ?>
    <?php else : ?>
        <script type="text/javascript">
        //<![CDATA[
            <?php if ($gravityHelper->useBulkRecommendation() && $gravityHelper->useGravityTemplate()) : ?>
            window.gravityGroupSeq = 1;
            window.gravityGroupSize = 0;
            <?php endif; ?>
            var _gravity = _gravity || [];
           (function(g,r,a,v,i,t,y){
				g[a]=g[a]||[],y=r.createElement(v),
				g=r.getElementsByTagName(v)[0];y.async=1;
				y.src='//'+i+'/js/'+t+'/gr_reco5.min.js';
				g.parentNode.insertBefore(y,g);y=r.createElement(v),y.async=1;
				y.src='//'+i+'/grrec-'+t+'-war/JSServlet4?cc=1';
				g.parentNode.insertBefore(y,g);
			})(window, document, '_gravity','script', "<?php echo $this->getGravityCustomerId() ?>.yusp.com", "<?php echo $this->getGravityCustomerId() ?>");
        //]]>
        </script>
    <?php endif; ?>
<?php endif; ?>
