<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="al-authorizationform-login">
	
<!---------------- LOGIN start -------------------->
	
	<div class="al-authorizationform-login-custom" style="float:left; margin: 0 30px 0 0;">
	<form action="<?php echo $this->getLoginActionUrl() ?>" method="post" id="login-form">
        <ul class="form-list">
            <?php foreach ($this->getChildren() as $__childBlock): ?>
                <li>
                    <?php echo $__childBlock->toHtml() ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </form>
    <form action="<?php echo $this->getLogoutActionUrl() ?>" method="get" id="logout-form"></form>
	</div>
	

	
	
</div>