<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->getParentBlock()->shouldDisplayNewsletterSubscriptionSection()): ?>
    <input
        type="checkbox"
        name="is_subscribed"
        title="<?php echo $this->__('Sign Up for Newsletter') ?>"
        value="1"
        id="<?php if ( $this->getHtmlId() ): ?><?php echo $this->getHtmlId() ?><?php else: ?><?php echo $this->getNameInLayout() ?><?php endif; ?>"
        <?php if ( $this->getParentBlock()->getFormData()->getIsSubscribed() ): ?>
            checked="checked"
        <?php endif; ?>
        class="checkbox"
    />
    <label class="newsletter" for="is_subscribed"><?php echo $this->__('Sign Up for special offers from Bilna.com') ?></label>
    <?php echo $this->getParentBlock()->getChildHtml('customer.form.register.newsletter')?>
<?php endif ?>