<?php

$wishlists = $this->getWishlists(); // Array
$curPage = $this->getCurPage();
$lastPageNumber = $this->getLastPageNumber();

?>


<div class="cg-container nomargin">

 <div class="cg-col-sm-12 in-block" style="padding:13px;" id="top-banner">
  <div class="cg-col-sm-12 cg-col-xs-12 collection-top-banner">
    <div class="cg-col-sm-6 cg-col-xs-12">
      <div class="cg-col-sm-12 title-banner-collection">
        Koleksi Produk Terbaik Untuk Inspirasi Belanja Anda
      </div>
      <div class="cg-col-sm-11 subtext-banner-collection opensans" style="">
        Buat KOLEKSI dan kumpulkan produk favorit anda sesuai tema atau mood. Berikan inspirasi belanja untuk lorem ipsum sir dolor amit
      </div>
      <div class="cg-col-sm-12">
        <a href="javascript:;" class="btn-lightgreen cg-col-xs-8 cg-col-sm-4 cg-col-md-3 cg-col-lg-5 btn-margin bottom-spacer-container" <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>onclick="newShowAddCollectionDialog()"<?php else: ?>onclick="openLogin()"<?php endif; ?>>PELAJARI LEBIH LANJUT</a>
      </div>
    </div>
    <div class="cg-col-sm-12 cg-col-xs-12 cg-col-md-6 cg-col-lg-6 closer-top-banner">
     <a href="javascript:;" onclick="closeTopBanner()" style="" class="closer-right"><i class="fa fa-times"></i></a>
   </div>
 </div>
</div>

<!-- 
  <div class="cg-row bordering" style="margin-top:20px;">
    <div class="normal-padding cg-col-xs-12 text-center bolder collections-head" style="">COLLECTIONS</div>
  </div> -->

<!-- Modify collection query to show only collection with minimum of 4 items harcoded temporarily-->
<?php 
foreach ($wishlists as $wishlist) { 

  ?>
  <?php $user = Mage::helper('socialcommerce')->getProfileInformation($wishlist['customer_id']); 

  ?> 

  <div class="cg-col-lg-3 cg-col-md-3 cg-col-sm-6 cg-col-xs-6 bottom-spacer-container">
    <div class="cg-col-lg-12 nopadding">
      <a href="<?php echo $this->getUrl('collections/' . $wishlist['id'] . '-' . $wishlist['slug']); ?>">
        <?php if ($wishlist['cover'] && strpos($wishlist['cover'],'socialcommerce') == true) : ?>
        <img src="<?php echo str_replace('en/', '', $wishlist['cover']); ?>" width="275" height ="275" class="img-collection collection-img">
      <?php elseif ($wishlist['cover'] && strpos($wishlist['cover'],'socialcommerce') == false) : ?>
      <img src="<?php echo str_replace('en/', '', $this->getUrl('media/collection-cover').$wishlist['cover']); ?>" width="275" height ="275" class="img-collection collection-img">
    <?php elseif ($wishlist['cloud_cover']) : ?>
    <?php echo cl_image_tag($wishlist['cloud_cover'], ['class' => 'img-collection collection-img', 'alt' => $user['display_name'], 'secure' => true, 'width' => 275, 'height' => 275, 'crop' => 'fill', 'format' => 'jpg']); ?>
  <?php else : ?>
  <img src="<?php echo $wishlist['product_image']; ?>" width="275" height ="275"class="img-collection collection-img">
<?php endif; ?>
</a>
<div class="cg-col-xs-12 collection-title">
  <div class="cg-col-lg-2 cg-col-md-2 cg-col-sm-2 cg-col-xs-2 nopadding framePhotoUser">
    <img src="<?php echo $user['profile_image']; ?>" title="<?php echo $user['display_name']; ?>" alt="<?php echo $user['display_name']; ?>" width="100%" >
  </div>
  <div class="cg-col-lg-10 cg-col-md-10 cg-col-sm-10 cg-col-xs-8" style="">
   <?php if ($user['url']) : ?>
   <a class="display-name-coll link-pink-hover" href="<?php echo $user['url']; ?>" style="text-decoration: none;color:#bbb;"><?php echo $user['display_name']; ?></a>
 <?php else : ?>
 <?php echo $user['display_name']; ?>
<?php endif; ?>
<br>
<a class="ddisplay-title-coll link-pink-hover nameOfList" href="<?php echo $this->getUrl('collections/' . $wishlist['id'] . '-' . $wishlist['slug']); ?>" style="text-decoration: none;color:#3c3d41;"><?php echo $wishlist['name']; ?></a>
</div>
</div>
</div>
</div>

<?php } ?>

</div>
</div>

<div class="cg-col-lg-12 cg-col-xs-12 text-center collection-top-intro nopadding">
  <div class="cg-col-lg-2 cg-col-md-2 cg-col-sm-12 cg-col-xs-12" style="display:none;">
    <div class="btn btn-how-create" onclick="showHowTo()" style="text-align: center;background-color: #ee5191;    border-radius: 4px;    text-transform: uppercase;    padding: 5px;    font-weight: bold;    font-family: 'Montserrat',sans-serif;    color: #fff;">How to create</div>
  </div>
  <?php if ($lastPageNumber > 1 ) : ?>
  <div class="cg-col-lg-6 cg-col-md-6 cg-col-sm-12 cg-col-xs-12 pull-right cg-col-xs-12">
    <nav class="middle-nav">
      <ul class="pagination general pull-right">
        <?php $prevUrl = ($curPage == 1) ? 'javascript:;' : $this->getUrl('collections') . '?p=' . ($curPage - 1) ; ?>
        <?php $nextUrl = ($curPage == $lastPageNumber) ? 'javascript:;' : $this->getUrl('collections') . '?p=' . ($curPage + 1) ; ?>

        <li<?php if ($curPage == 1) : ?> class="disabled"<?php endif; ?>><a href="<?php echo $prevUrl; ?>" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>

        <?php for ($i=1; $i <= $lastPageNumber ; $i++ ) : ?>
        <li<?php if ($i == $curPage) : ?> class="active"<?php endif; ?>><a href="<?php echo $this->getUrl('collections') . '?p=' . $i ?>"><?php echo $i; ?></a></li>
      <?php endfor; ?>

      <li<?php if ($curPage == $lastPageNumber) : ?> class="disabled"<?php endif; ?>><a href="<?php echo $nextUrl; ?>" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
    </ul>
  </nav>
</div>
<?php endif; ?>
</div>
</div>
</div>
</div>
<div class="cg-row nomargin">

  <div class="cg-col-lg-12 cg-col-xs-12 in-block nopadding">
            <!--
            <div class="cg-col-lg-12 cg-col-xs-12 text-center collection-top-intro nopadding">
                <div class="cg-col-lg-2 cg-col-md-2 cg-col-sm-12 cg-col-xs-12">
                    <div class="btn btn-how-create" onclick="showHowTo()" style="">How to create</div>
                </div>
            </div>
          -->

          <!-- Tab panes -->
          <div class="tab-content">
            <div class="cg-col-lg-12 nopadding">
              <div class="cg-col-xs-12 bottom-spacer-container"></div>
              <div class="cg-col-sm-12 less-normal-padding">
                <div class="cg-col-sm-12 in-block full-width bottom-spacer-container opensans collection-header-title">
                  Koleksi Favorite Minggu Ini
                </div>
              </div>

                <div class="cg-container">
              <?php 
                  //Mage::getModel('socialcommerce/weekly')->getWeekly();
              $rows = Mage::getModel('wishlist/wishlist')->getCollection()->addFieldToFilter('visibility','1')->setOrder('counter', 'DESC')->setPageSize(4);

              foreach ($rows as $wishlist) { 
                $collectionName = $wishlist['name'];
                /*$slug = strtolower(ucwords(str_replace(" ","-",$wishlist['name'])));*/
                $slug = Mage::getModel('catalog/product_url')->formatUrlKey($collectionName);

                $productId = $wishlist['product_id'];
                $product = Mage::getModel('catalog/product')->load($productId);
                $product_image = Mage::helper('catalog/image')->init($product, 'small_image')->resize(320 , 320);
                
                ?>

                <?php $user = Mage::helper('socialcommerce')->getProfileInformation($wishlist['customer_id']); ?> 
                  <div class="cg-col-lg-3 cg-col-md-3 cg-col-sm-6 cg-col-xs-6 bottom-spacer-container">
                    <div class="cg-col-xs-12 nopadding collection-shade">
                      <a href="<?php echo $this->getUrl('collections/' . $wishlist['wishlist_id'] . '-' . $slug); ?>">
                        <?php if ($wishlist['cover'] && strpos($wishlist['cover'],'socialcommerce') == true) : ?>
                        <img src="<?php echo str_replace('en/', '', $wishlist['cover']); ?>" width="275" height ="275" class="img-collection collection-img">
                      <?php elseif ($wishlist['cover'] && strpos($wishlist['cover'],'socialcommerce') == false) : ?>
                      <img src="<?php echo str_replace('en/', '', $this->getUrl('media/collection-cover').$wishlist['cover']); ?>" width="275" height ="275" class="img-collection collection-img">
                    <?php elseif ($wishlist['cloud_cover']) : ?>
                    <?php echo cl_image_tag($wishlist['cloud_cover'], ['class' => 'img-collection collection-img', 'alt' => $user['display_name'], 'secure' => true, 'width' => 275, 'height' => 275, 'crop' => 'fill', 'format' => 'jpg']); ?>
                  <?php else : ?>
                  <img src="<?php echo $product_image; ?>" width = "100%" class="img-collection">
                <?php endif; ?>
              </a>
              <div class="cg-col-xs-12 collection-title">
                <div class="cg-col-lg-12 cg-col-md-10 cg-col-sm-10 cg-col-xs-8 take-left" style="">
                 <a class="display-title-coll link-pink-hover nameOfList uppercase opensans" href="<?php echo $this->getUrl('collections/' . $wishlist['wishlist_id'] . '-' . $slug); ?>" style=""><?php echo $wishlist['name']; ?></a>
                 <?php if ($user['url']) : ?>
                 <span class="opensans hidden-xs">oleh</span> <a class="display-name-coll link-pink-hover opensans" href="<?php echo $user['url']; ?>" style=""><?php echo $user['display_name']; ?></a>
               <?php else : ?>
               <?php echo $user['display_name']; ?>
             <?php endif; ?>
             <span class="pull-right opensans hidden-xs"><a href="<?php echo $this->getUrl('collections/' . $wishlist['wishlist_id'] . '-' . $slug); ?>">Lihat Koleksi ></a> </span>
           </div>
         </div>
       </div>
     </div>
   
   <?php } ?>
   
   </div>
   <div class="cg-row nomargin">

    <div class="cg-col-lg-12 cg-col-xs-12 in-block nopadding">
            <!--
            <div class="cg-col-lg-12 cg-col-xs-12 text-center collection-top-intro nopadding">
                <div class="cg-col-lg-2 cg-col-md-2 cg-col-sm-12 cg-col-xs-12">
                    <div class="btn btn-how-create" onclick="showHowTo()" style="">How to create</div>
                </div>
            </div>
          -->

          <!-- Tab panes -->
          <div class="tab-content white-back">
            <div class="cg-col-lg-12 nopadding">
              <div class="cg-col-xs-12 bottom-spacer-container"></div>
              <div class="cg-col-sm-12 less-normal-padding">
                <div class="cg-col-sm-12 in-block full-width bottom-spacer-more collection-header-title">
                  Masukkan Produk Dalam Koleksi Anda
                </div>
                <div class="cg-col-xs-12 bottom-spacer-more">
                  <div class="cg-col-xs-12 cg-col-lg-4">
                    <img src="<?php echo $this->getSkinUrl('images/step-1.png'); ?>" width="30%"> <br>
                    <p class="exp-three-col">Cari produk favorit sesuai <br>tema / mood koleksi anda</p>
                  </div>
                  <div class="cg-col-xs-12 cg-col-lg-4">
                    <img src="<?php echo $this->getSkinUrl('images/step-2.png'); ?>" width="30%"> <br>
                    <p class="exp-three-col">Masukkan produk tsb dalam koleksi <br>baru atau tambahkan dalam halaman <br> koleksi yang sudah dibuat sebelumnya</p>
                  </div>
                  <div class="cg-col-xs-12 cg-col-lg-4">
                    <img src="<?php echo $this->getSkinUrl('images/step-3.png'); ?>" width="30%"> <br>
                    <p class="exp-three-col">Cek profil anda untuk melihat & <br>mengedit halaman koleksi</p>
                  </div>
                </div>
                <div class="cg-col-sm-6 cg-col-sm-offset-3">
                  <a href="javascript:;" class="btn-lightgreen cg-col-xs-12 btn-margin bottom-spacer-container" <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>onclick="newShowAddCollectionDialog()"<?php else: ?>onclick="openLogin()"<?php endif; ?>>CARI PRODUK FAVORIT DI BILNA.COM</a>
                </div>
                <div class="cg-col-sm-6 cg-col-sm-offset-3">
                  <a href="javascript:;" class="cg-col-xs-12 btn-margin bottom-spacer-container new-page" onclick="newShowAddCollectionDialog()">
                    Saya ingin membuat halaman koleksi baru
                  </a>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="cg-row nomargin">

  <div class="cg-col-lg-12 cg-col-xs-12 in-block nopadding">
            <!--
            <div class="cg-col-lg-12 cg-col-xs-12 text-center collection-top-intro nopadding">
                <div class="cg-col-lg-2 cg-col-md-2 cg-col-sm-12 cg-col-xs-12">
                    <div class="btn btn-how-create" onclick="showHowTo()" style="">How to create</div>
                </div>
            </div>
          -->

          <!-- Tab panes -->
          <div class="tab-content">
            <div class="cg-col-lg-12 nopadding">
              <div class="cg-col-xs-12 bottom-spacer-container"></div>
              <div class="cg-col-sm-12 less-normal-padding">
                <div class="cg-col-sm-12 in-block full-width bottom-spacer-container collection-header-title">
                  Koleksi Terbaru
                </div>
              </div>

                <div class="cg-container">
              <?php 
                  //Mage::getModel('socialcommerce/weekly')->getWeekly();
              $rows = Mage::getModel('wishlist/wishlist')->getCollection()->addFieldToFilter('visibility','1')->setOrder('counter', 'DESC')->setPageSize(4);

              foreach ($rows as $wishlist) { 
                $collectionName = $wishlist['name'];
                /*$slug = strtolower(ucwords(str_replace(" ","-",$wishlist['name'])));*/
                $slug = Mage::getModel('catalog/product_url')->formatUrlKey($collectionName);

                $productId = $wishlist['product_id'];
                $product = Mage::getModel('catalog/product')->load($productId);
                $product_image = Mage::helper('catalog/image')->init($product, 'small_image')->resize(320 , 320);
                
                ?>

                <?php $user = Mage::helper('socialcommerce')->getProfileInformation($wishlist['customer_id']); ?> 
                  <div class="cg-col-lg-3 cg-col-md-3 cg-col-sm-6 cg-col-xs-6 bottom-spacer-container">
                    <div class="cg-col-xs-12 nopadding collection-shade">
                      <a href="<?php echo $this->getUrl('collections/' . $wishlist['wishlist_id'] . '-' . $slug); ?>">
                        <?php if ($wishlist['cover'] && strpos($wishlist['cover'],'socialcommerce') == true) : ?>
                        <img src="<?php echo str_replace('en/', '', $wishlist['cover']); ?>" width="275" height ="275" class="img-collection collection-img">
                      <?php elseif ($wishlist['cover'] && strpos($wishlist['cover'],'socialcommerce') == false) : ?>
                      <img src="<?php echo str_replace('en/', '', $this->getUrl('media/collection-cover').$wishlist['cover']); ?>" width="275" height ="275" class="img-collection collection-img">
                    <?php elseif ($wishlist['cloud_cover']) : ?>
                    <?php echo cl_image_tag($wishlist['cloud_cover'], ['class' => 'img-collection collection-img', 'alt' => $user['display_name'], 'secure' => true, 'width' => 275, 'height' => 275, 'crop' => 'fill', 'format' => 'jpg']); ?>
                  <?php else : ?>
                  <img src="<?php echo $product_image; ?>" width = "100%" class="img-collection">
                <?php endif; ?>
              </a>
              <div class="cg-col-xs-12 collection-title">
                <div class="cg-col-lg-12 cg-col-md-10 cg-col-sm-10 cg-col-xs-8 take-left" style="">
                 <a class="display-title-coll link-pink-hover nameOfList uppercase opensans" href="<?php echo $this->getUrl('collections/' . $wishlist['wishlist_id'] . '-' . $slug); ?>" style=""><?php echo $wishlist['name']; ?></a>
                 <?php if ($user['url']) : ?>
                 <span class="opensans hidden-xs">oleh</span> <a class="display-name-coll link-pink-hover opensans" href="<?php echo $user['url']; ?>" style=""><?php echo $user['display_name']; ?></a>
               <?php else : ?>
               <?php echo $user['display_name']; ?>
             <?php endif; ?>
             <span class="pull-right opensans hidden-xs"><a href="<?php echo $this->getUrl('collections/' . $wishlist['wishlist_id'] . '-' . $slug); ?>">Lihat Koleksi ></a> </span>
           </div>
         </div>
       </div>
     </div>
   
   <?php } ?>
<!-- 
     <div class="cg-col-xs-12">
     <ul class="pagination pull-right">
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
  </ul>
  </div> -->

   </div>
      <script>
      function showHowTo() {
        jQuery('#howto').fadeIn('fast');
      }

      function closeTo() {
        jQuery('#howto').fadeOut('fast');
      }
      </script>

