<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.6.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>

<div class="aw_points-coupon-box">
	
	<div class="box-ribbon-allwrapp">
		<div class="box-coint">
			<h4><?php echo $this->__('Gift Voucher Activation') ?></h4>

			<div class="box-ribbon-wrapp">
			<div class="box1-ribbon"></div>
			<div class="box-ribbon">
			<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
				<div>
					<label for="aw_points-coupon" style="color:#D1542D;">
						<?php echo $this->__('Gift Voucher Code:') ?>
					</label>
					<input  type="text" id="aw_points-coupon" class="aw_points-coupon" name="coupon_code" value=""/>
					<button type="submit" title="<?php echo $this->__('Activate Coupon') ?>" class="button">
						<span>
							<span>
								<?php echo $this->__('Activate Coupon') ?>
							</span>
						</span>
					</button>
				</div>
			</form>
			</div>
			<div class="box2-ribbon"></div>
			</div>
		</div>
	</div>

</div>

