<style type="text/css">
    .redirect_area{font-family:arial;display:block}.redirect_area .title_payment h3{color:#4ec7da;font-size:21px}.redirect_area .title_payment h3,.redirect_area .title_payment p{margin:3px 0}.redirect_area p{font-size:14px;color:#ffba5a}.redirect_area .redirect_button{margin:20px 0;background:#ffba5a;font-size:21px;color:#fff;border:0;padding:10px 20px}
</style>

<div class="redirect_area">
    <div class="title_payment">
        <br/>
        <h3><?php echo $this->__('BCA KlikPay redirect page'); ?></h3>
    </div>
    
    <br/><br/><br/>
    
    <p><?php echo $this->__('This page will be redirect to BCA KlikPay page in ' . $this->getRedirectTimeout() . ' seconds.'); ?></p>
    
    <br/><br/>

    <?php $data = $this->getFormData(); ?>

    <form id="form_auto_post" name="form_auto_post" action="<?php echo $this->getKlikpaySubmitUrl(); ?>" method="post">
        <input type="hidden" id="klikPayCode" name="klikPayCode" value="<?php echo $data['klikPayCode']; ?>" />
        <input type="hidden" id="transactionNo" name="transactionNo" value="<?php echo $data['transactionNo']; ?>" />
        <input type="hidden" id="totalAmount" name="totalAmount" value="<?php echo $data['totalAmount']; ?>" />
        <input type="hidden" id="currency" name="currency" value="<?php echo $data['currency']; ?>" />
        <input type="hidden" id="payType" name="payType" value="<?php echo $data['payType']; ?>" />
        <input type="hidden" id="callback" name="callback" value="<?php echo $data['callback']; ?>" />
        <input type="hidden" id="transactionDate" name="transactionDate" value="<?php echo $data['transactionDate']; ?>" />
        <input type="hidden" id="descp" name="descp" value="<?php echo $data['descp']; ?>" />
        <input type="hidden" id="miscFee" name="miscFee" value="<?php echo $data['miscFee']; ?>" />
        <input type="hidden" id="signature" name="signature" value="<?php echo $data['signature']; ?>" />

        <div id="checkoutSteps">
            <button class="redirect_button" onclick="do_submit();" title="<?php echo $this->__('Confirm redirect'); ?>" type="button">
                <span>
                    <span><?php echo $this->__('Confirm redirect'); ?></span>
                </span>
            </button>
        </div>	
    </form>
</div>

<script language="javascript" type="text/javascript">
    //<![CDATA[
    var redirectTimeout = <?php echo $this->getRedirectTimeout(); ?>;
    setTimeout('do_submit()', redirectTimeout * 1000);

    function do_submit() {
        document.form_auto_post.submit();
    }
    //]]>
</script>
