<?php /** @var $this Mage_Adminhtml_Block_Sales_Order_Create_Shipping_Method_Form */ ?>
<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if ($_shippingRateGroups): ?>
    <div id="order-shipping-method-choose" style="display: none;">
    <dl class="shipment-methods">
    <?php $_checked = ''; $_codeChecked = ''; ?>
    <?php $disableOption = false; ?>
    <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
        <dt><strong><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></strong></dt>
        <dd>
            <ul>
            <?php foreach ($_rates as $_rate): ?>
                <?php 
                // if current shipping method is Express, check whether all the items can be express-shipped
                if ( (strpos(strtolower($_rate->getCode()), 'express') !== false) || (strpos(strtolower($_rate->getCode()), 'ekspres') !== false) ):
                    if (!$this->showExpressShippingMethod())
                        $disableOption = true;
                    else
                    if (!$this->checkExpressShippingSalesCount())
                        $disableOption = true;
                ?>
                <?php endif ?>
                <?php $_code = $_rate->getCode() ?>
                <?php $_radioProperty = 'name="order[shipping_method]" class="shipping-method" type="radio" onclick="order.setShippingMethod(this.value)"' ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages">
                            <li class="error-msg"><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li>
                        </ul>
                   <?php else: ?>
                        <?php
                            if ($this->isMethodActive($_code)):
                            //if ($_code == $_rateChecked->getCode()):
                                $_checked = 'checked="checked"';
                                $_codeChecked = $_code;
                            else:
                                $_checked = '';
                                $_codeChecked = '';
                            endif;
                            //$_checked = $this->isMethodActive($_code) ? 'checked="checked"' : '';
                            //$_codeChecked = $this->isMethodActive($_code) ? $_code : '';
                        ?>
                        <?php if($disableOption): ?>
                            <input type="radio" disabled="disabled" class="radio shipping-type disabled"/>
                        <?php else: ?>
                            <input <?php echo $_radioProperty ?> value="<?php echo $_code ?>" id="s_method_<?php echo $_code ?>" <?php echo $_checked ?> datatype="<?php echo $_rate->getDeliveryId(); ?>" datatext="<?php echo $_rate->getMethodTitle(); ?>" />
                        <?php endif; ?>
                        <label class="normal" for="s_method_<?php echo $_code ?>">
                            <?php echo $this->escapeHtml($_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?> -
                            <strong>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                            </strong>
                        </label>
                   <?php endif ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
    <?php endforeach; ?>
    </dl>
    </div>
    <?php if ($_rate = $this->getActiveMethodRate()): ?>
        <div id="order-shipping-method-info">
            <strong><?php echo $this->escapeHtml($this->getCarrierName($_rate->getCarrier())) ?></strong><br/>
            <?php echo $this->escapeHtml($_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?> -
            <strong>
                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                <?php echo $_excl; ?>
                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>
            </strong>
            <!--input type="text" class="input-text" style="width:70px"/-->
            <br/>
            <a href="#" onclick="$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();return false">
                <?php echo Mage::helper('sales')->__('Click to change shipping method') ?>
            </a>
        </div>
    <?php else: ?>
        <script type="text/javascript">$('order-shipping-method-choose').show();</script>
    <?php endif; ?>
<?php elseif($this->getIsRateRequest()): ?>
    <strong><?php echo Mage::helper('sales')->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
    <div id="order-shipping-method-summary">
        <a href="#" onclick="order.loadShippingRates();return false">
            <?php echo Mage::helper('sales')->__('Get shipping methods and rates') ?>
        </a>
        <input type="hidden" name="order[has_shipping]" value="" class="required-entry" />
    </div>
<?php endif; ?>
<div style="display:none;" id="shipping-method-overlay" class="overlay"><span><?php echo $this->__('Shipping method selection is not applicable') ?></span></div>

<?php
$wrappingEvent = $this->getUseWrapping();
$wrappinggiftData = $this->getWrappinggiftData();
$useWrappinggift = $wrappinggiftData['use_wrappinggift'];
$wrappinggiftAmount = $wrappinggiftData['wrappinggift_amount'];
?>

<ul>
    <li class="fields">
        <div class="field">
            <div class="input-box">
                <label>
                    <input id="wrapping_for_gift" name="wrapping_for_gift" type="checkbox" value="1" class="radio" <?php if (isset ($useWrappinggift) && $useWrappinggift == 1): ?>checked="checked"<?php endif; ?> />
                    <?php echo $this->__('This is a Gift') ?>
                </label>
            </div>
        </div>
    </li>
    
    <div id="gift_list_event" style="display:none;margin-left:18px;">
        <?php foreach ($this->getWrappingGiftEvent() as $list): ?>
            <li>
                <div class="field">
                    <div class="input-box">
                        <label>
                            <input type="radio" name="wrapping_gift" id="wrapping_<?php echo $list['id'] . '_' . $list['wrapping_price']; ?>" value="<?php echo $this->escapeHtml($list['id'] . '_' . $list['wrapping_price']); ?>" <?php if (isset ($wrappinggiftAmount) && $wrappinggiftAmount == $list['id'] . '_' . $list['wrapping_price']): ?>checked="checked"<?php endif; ?> onchange="order.setWrappinggiftChange('<?php echo $this->urlToWrappinggiftSave(); ?>');" />
                            <?php echo $this->escapeHtml($list['wrapping_name']); ?> - <strong><?php echo $this->formatPrice($list['wrapping_price']); ?></strong>
                        </label>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </div>
</ul>
<script type="text/javascript">
    order.overlay('shipping-method-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
    order.overlay('address-shipping-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
    
    $('wrapping_for_gift').observe('click', function(e) {
        if (this.checked) {
            <?php if (!isset ($wrappingAmount)): ?>
                $('gift_list_event').select('input[type="radio"]:first').invoke('setValue', true);
            <?php endif; ?>
            
            $('gift_list_event').show();
            order.setWrappinggiftChange('<?php echo $this->urlToWrappinggiftSave(); ?>');
        }
        else {
            $('gift_list_event').hide();
            $('gift_list_event').select('input[type="radio"]:checked').invoke('setValue', false);
            order.setWrappinggiftChange('<?php echo $this->urlToWrappinggiftSave(); ?>');
        }
    });
    
    
    if ($('wrapping_for_gift').checked == true) {
        $('gift_list_event').show();
    }
</script>