<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ( $this->getParentBlock()->shouldDisplayTermsAndConditions() ): ?>
    <?php if ( count($this->getAgreements()) > 0 ): ?>
        <ol class="checkout-agreements">
            <?php foreach ($this->getAgreements() as $_a): ?>
                <li>
                    <div class="agreement-content" style="<?php echo ($_a->getContentHeight() ? 'height: ' . $_a->getContentHeight() : '')?>; display: none;">
                        <?php if ($_a->getIsHtml()):?>
                            <?php echo $_a->getContent() ?>
                        <?php else:?>
                            <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
                        <?php endif; ?>
                    </div>
                    <p class="agree">
                        <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox required-entry" />
                        <label class="required" for="agreement-<?php echo $_a->getId()?>"><em>*</em><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->htmlEscape($_a->getCheckboxText()) ?></label>
                    </p>
                </li>
            <?php endforeach ?>
        </ol>
        
        <script type="text/javascript">
            $$('.al-authorization .agree').each(
                function(agreementNode) {
                    agreementNode.observe(
                        'mouseenter',
                        function(event) {
                            var __candidate = this.previousSibling;
                            while ( (__candidate) && (__candidate.tagName != 'DIV') ) {
                                __candidate = __candidate.previousSibling;
                            }
                            
                            if ( (__candidate) && (__candidate.tagName == 'DIV') ) {
                                __candidate.style.display = '';
                            }
                        }
                    );
                    agreementNode.observe(
                        'mouseleave',
                        function(event) {
                            var __candidate = this.previousSibling;
                            while ( (__candidate) && (__candidate.tagName != 'DIV') ) {
                                __candidate = __candidate.previousSibling;
                            }
                            
                            if ( (__candidate) && (__candidate.tagName == 'DIV') ) {
                                __candidate.style.display = 'none';
                            }
                        }
                    );
                }
            );
        </script>
    <?php endif; ?>
<?php endif; ?>