<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><ul class="messages Shaddy" style="display: none;">
    <li class="error-msg">&nbsp;</li>
</ul>
        
    <?php if ( $this->shouldDisplayCreateaccountbutton() ): ?>
<p class="popuplogin-footer">Belum punya akun bilna? <a href="<?php echo $this->getParentBlock()->getCreateAccountUrl() ?>" ><label id="<?php echo $this->getCreateaccountbuttonHtmlId() ?>" for="responsiveformregister"><?php echo $this->__('Daftar disini') ?></label></a></p>
    <?php endif; ?>

<script type="text/javascript">
    Event.observe(
        window,
        'load',
        function() {
            var __node;
            
            __node = $('<?php echo $this->getForgotpasswordbuttonHtmlId() ?>');
            if ( __node ) __node.observe(
                'click',
                function(event) {
                    AjaxLogin.Authorization.__getInstanceByChildnode(this).switchToFrame('recovery');
                    if (window.event) window.event.cancelBubble = true;
                    if (window.event) window.event.returnValue = false;
                    event.preventDefault();
                    event.stopPropagation();
                    return false;
                }
            );
            
            __node = $('<?php echo $this->getCreateaccountbuttonHtmlId() ?>')
            if ( __node ) __node.observe(
                'click',
                function(event) {
                    // hide first and last name input label for pop up Login
                    jQuery('form#register-form div.field.name-firstname div.input-box label').addClass('hidden');
                    jQuery('form#register-form div.field.name-lastname div.input-box label').addClass('hidden');

                    AjaxLogin.Authorization.__getInstanceByChildnode(this).switchToFrame('register');
                    if (window.event) window.event.cancelBubble = true;
                    // if (window.event) window.event.returnValue = false;
                    // event.preventDefault();
                    event.stopPropagation();
                    return false;
                }
            );
        }
    );
</script>