<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<div class="input-box ajaxlogin-customer-dob"><label for="<?php echo $this->getFieldId('month')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Date of Birth') ?></label>
<?php
    $this->setDateInput('d',
        '<span class="dob-day">
             <input type="text" id="ajaxlogin-day" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" placeholder="' . $this->__('DD') . '" title="' . $this->__('Day') . '" class="input-text validate-custom" ' . $this->getFieldParams() . ' />
             
         </span>'
    );

    $this->setDateInput('m',
        '<span class="dob-month">
             <input type="text" id="ajaxlogin-month" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" placeholder="' . $this->__('MM') . '" title="' . $this->__('Month')  . '" class="input-text validate-custom" ' . $this->getFieldParams()  . ' />
         </span>'
    );

    $this->setDateInput('y',
        '<span class="dob-year">
             <input type="text" id="ajaxlogin-year" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" placeholder="' . $this->__('YY') . '" title="' . $this->__('Year')  . '" class="input-text validate-custom" ' . $this->getFieldParams()  . ' />
            
         </span>'
    );
?>
    <?php echo $this->getSortedDateInputs() ?>
    <span class="dob-full" style="display:none;">
        <input type="hidden" id="ajaxlogin-full" name="<?php echo $this->getFieldName('dob')?>" />
    </span>
    <div class="validation-advice" id="ajaxlogin-advice" style="display:none;"></div>
</div>
<script type="text/javascript">
    new AjaxLogin.DOB('<?php if ($this->getFormBlock()): ?>#<?php echo $this->getFormBlock()->getHtmlId() ?> <?php endif; ?>.ajaxlogin-customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
    if (typeof AjaxLogin != 'undefined') AjaxLogin.DATE_FORMAT = '<?php echo $this->getDateFormat() ?>';
</script>