<?php
$_storeCategories = $this->getMegamenuData();
$_categoryActive = $this->getCurrentMainCategoryIdActive();
?>
<div class="arrow_megamenu"></div>
<div class="megamenu-container">
    <div class="first-level">
        <ul>
            <?php if (count($_storeCategories) > 0): ?>
               <?php foreach ($_storeCategories as $_storeCategory): ?>
                    <?php
                    $_id = $_storeCategory['id'];
                    $_urlKey = $_storeCategory['url_key'];
                    $_name = $_storeCategory['name'];
                    $_url = $_storeCategory['url'];

                    $_storeCategoryClass = ($_id == $_categoryActive) ? "default" : "";
                    ?>

                    <li class="first-level-cat">
                        <div class="first-level-url" data-href="<?php echo $_url; ?>">
                            <?php echo $_name; ?>
                            <div class="arrow-megamenu"><i class="fa fa-caret-right"></i></div>
                        </div>

                        <?php
                        $_storeCategoriesChild = array ();

                        if ($_storeCategory['child'] && count($_storeCategory['child'] > 0)):
                            $_storeCategoriesChild = $_storeCategory['child'];
                        endif;
                        ?>

                        <?php if (count($_storeCategoriesChild) > 0): ?>
                            <div class="second-level">
                                <div class="wrap-second-cat">
                                    <?php foreach ($_storeCategoriesChild as $_storeCategoryChild): ?>
                                        <?php
                                        $_id2 = $_storeCategoryChild['id'];
                                        $_name2 = $_storeCategoryChild['name'];
                                        $_url2 = $_storeCategoryChild['url'];
                                        $_urlKey2 = $_storeCategoryChild['url_key'];
                                        ?>

                                        <ul>
                                            <li>
                                                <p>
                                                    <a href="<?php echo $_url2; ?>"><?php echo $_name2; ?></a>
                                                </p>
                                            </li>
                                            <?php
                                            $_storeCategoriesChildChild = array ();

                                            if ($_storeCategoryChild['child'] && count($_storeCategoryChild['child'] > 0)):
                                                $_storeCategoriesChildChild = $_storeCategoryChild['child'];
                                            endif;
                                            ?>

                                            <?php if (count($_storeCategoriesChildChild) > 0): ?>
                                                <?php foreach ($_storeCategoriesChildChild as $_storeCategoryChildChild): ?>
                                                    <?php
                                                    $_id3 = $_storeCategoryChildChild['id'];
                                                    $_name3 = $_storeCategoryChildChild['name'];
                                                    $_url3 = $_storeCategoryChildChild['url'];
                                                    $_urlKey3 = $_storeCategoryChildChild['url_key'];
                                                    ?>

                                                    <li>
                                                        <a href="<?php echo $_url3; ?>"><?php echo $_name3; ?></a>
                                                    </li>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </ul>
                                    <?php endforeach; ?>
                                </div>

                                <div class="wrap-banner">
                                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('menu-' . $_urlKey . '-block')->toHtml(); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </div>
</div>