<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><h2>How to create Google project with API service</h2>
<p>In order to use the Google login feature you need to create your project with <b>Google Cloud Console</b>.</p>
<p>The first step is to visit the <a target="_blank" href="https://cloud.google.com/console">Google Cloud Console</a>. It is necessary to sign in to your Google account at this moment.</p>
<center><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/doc') ?>/google-project-1.jpg" /></center>
<p>Cloud console is new product from Google and it goes as a kind of replacement to APIs Console, it provides almost the same functionality but has more friendly interface and it is pretty simple to operate even for unexperienced user.</p>
<p>As soon as you're in, you probably see there's no any projects created. Click <b>+&nbsp;New&nbsp;Project</b> button to add one:</p>
<center><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/doc') ?>/google-project-2.jpg" /></center>
<p>Give your project a name and a unique ID:</p>
<center><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/doc') ?>/google-project-3.png" /></center>
<p>After you click <b>Create</b> the project takes some time to get created and then the project overview page opens:</p>
<center><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/doc') ?>/google-project-4.png" /></center>
<p>The next step is to navigate to <b>APIs&nbsp;&amp;&nbsp;auth</b> &rarr; <b>Registered&nbsp;apps</b> section of your project details and click <b>Register&nbsp;App</b> button:</p>
<center><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/doc') ?>/google-project-5.png" /></center>
<p>Select <b>Web Application</b> as the type, and give it a relative name:</p>
<center><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/doc') ?>/google-project-6.png" /></center>
<p>After you click <b>Register</b> a new application is registered within your project. It takes you to the application details page and you can see it is almost ready to go. Now toggle the <b>OAuth&nbsp;2.0&nbsp;Client&nbsp;ID</b> section to see the most important options of your application:</p>
<center><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/doc') ?>/google-project-7.png" /></center>
<p>You can see the application already has <b>Client&nbsp;ID</b> and <b>Client&nbsp;Secret</b> values pregenerated and specified in this section. This is exactly where they are taken from to fulfill corresponding Magento backend options. But the application isn't going to work until you do one more thing - specify the <b>Redirect&nbsp;URI</b>.</p>
<p>Generally the <b>Redirect&nbsp;URI</b> value goes as the base URL of your Magento store concatenated with the following string: <b>ajaxlogin/oauth/acceptToken/network/google/</b>. For example:</p>
<p class="Example">
    <tt><?php echo Mage::getStoreConfig('web/unsecure/base_url') ?>ajaxlogin/oauth/acceptToken/network/google/</tt><br />
</p>
<p>But there is a couple of things for you to note:<br />&nbsp;-&nbsp;if you run several stores with different base URLs on your Magento, you may need to specify as many redirect URIs as many stores you have<br />&nbsp;-&nbsp;if you somehow use secure URLs for the entire webstore, you may need to change the URL scheme of your redirect URIs from <b>http</b> to <b>https</b></p>
<p>As soon as you finish specifying redirect URIs, click <b>Generate</b> button at the bottom of the section. This will make Google to apply changes and probably regenerate <b>Client&nbsp;Secret</b> value (most likely won't change).</p>
<center><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/doc') ?>/google-project-8.png" /></center>
<p>Time to put both <b>Client&nbsp;ID</b> and <b>Client&nbsp;Secret</b> values to corresponding inputs in the Google login configuration options.</p>
<p>Now you're all set and ready to use login with Google account feature.</p>
<p>As a friendly advice, it is also recommended to visit the <b>APIs&nbsp;&amp;&nbsp;auth</b> &rarr; <b>Consent&nbsp;screen</b> section of the project details. You may want to play around the visual options of your project to make sure it looks beautiful since title and logo appear to your customers when the application requests permissions from them upon loggin via Google.</p>
<p>Find more information about authentication with Google in the <a target="_blank" href="https://developers.google.com/accounts/docs/OAuth2Login">official documentation</a>.</p>