<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <div>
    <?php //echo $this->getMethod()->getConfigData('message');?>
    </div>
    <?php /* ?>
    <li>
        <label for="klikpay_userid" class="required"><em>*</em><?php echo $this->__('User ID Klikpay:') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('User ID Klikpay:') ?>" class="input-text required-entry" id="klikpay_user_id" name="payment[klikpay_user_id]" value="<?php echo $this->htmlEscape($this->getInfoData('klikpay_user_id')) ?>" />
        </span>
    </li>
    <?php */ ?>
</ul>
