<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="al-socialnets">
	<span><?php echo $this->__('Or, signup/login with') ?></span>
    <ul>
        <?php foreach ( $this->getNetworks() as $__network ): ?>
            <?php if ( $this->isProperlyConfigured($__network) ): ?>
                <li>
                    <img id="<?php echo $__network->getButtonHtmlId() ?>" class="ThumbnailImage" title="<?php echo $__network->getTitle() ?>" src="<?php echo $this->getThumbnailImageURL($__network->getThumbnailImagePath()) ?>" />
                    <?php echo $this->getButtonInitializationHtml($__network) ?>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>
<div class="orange-dash">
</div>