<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="alProgressBar" style="display: none;">
    <div class="Shadow"></div>
    <div class="loading-mask">
        <p class="loader" id="loading_mask_loader"><img src="<?php echo Mage::getDesign()->getSkinUrl('ajaxlogin/ajax-loader-tr.gif') ?>" alt="Loading..." /><br />Please wait...</p>
    </div>
</div>

<div class="al-authorization-container-overlap" id="<?php echo $this->getHtmlId() ?>" style="display: none;">
    <div class="Shadow"></div>
    <div class="Canvas">
        <div class="Shadowed">
            <div class="Wrapper">
                <?php echo $this->getChildHtml('authorization') ?>
            </div>
            <div class="Close"><a href="" title="<?php echo $this->__('Close window') ?>"><?php echo $this->__('Close') ?>&nbsp;[X]</a></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    Event.observe(
        window,
        'load',
        function() {
            var __overlapRootNode = $('<?php echo $this->getHtmlId() ?>');
            var __closeLinkNode = __overlapRootNode.select('.Close a')[0];
            var __shadowAreaNode = __overlapRootNode.select('.Shadow')[0];
            var __canvasAreaNode = __overlapRootNode.select('.Canvas')[0];
            var __authorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode($('<?php echo $this->getChild('authorization')->getHtmlId() ?>'));
            
            __authorizationInstance.__setProgressBar( $$('.alProgressBar')[0] );
            
            __closeLinkNode.observe(
                'click',
                function(overlapRootNode, authorizationInstance) {
                    return function(event) {
                        overlapRootNode.style.display = 'none';
                        authorizationInstance.switchToFrame(0);
                        
                        if (window.event) window.event.cancelBubble = true;
                        if (window.event) window.event.returnValue = false;
                        event.preventDefault();
                        event.stopPropagation();
                        return false;
                    };
                }
                (__overlapRootNode, __authorizationInstance)
            );
            
            __shadowAreaNode.observe(
                'click',
                function(overlapRootNode) {
                    return function(event) {
                        overlapRootNode.style.display = 'none';
                    };
                }
                (__overlapRootNode)
            );
            
            __canvasAreaNode.observe(
                'click',
                function(overlapRootNode) {
                    return function(event) {
                        if (event.target == this) {
                            overlapRootNode.style.display = 'none';
                        }
                    };
                }
                (__overlapRootNode)
            );
            
            __authorizationInstance.addHandler(
                AjaxLogin.Authorization.EVENTTYPE_LOGINSUCCESS,
                function(eventData) {
                    var __overlapNode = $('<?php echo $this->getHtmlId() ?>');
                    __overlapNode.style.display = 'none';
                }
            );
            
            __authorizationInstance.addHandler(
                AjaxLogin.Authorization.EVENTTYPE_REGISTERSUCCESS,
                function(eventData) {
                    if ( (typeof eventData.loggedIn == 'undefined') || (eventData.loggedIn != 0) ) {
                        var __overlapNode = $('<?php echo $this->getHtmlId() ?>');
                        __overlapNode.style.display = 'none';
                    }
                }
            );
            
            __authorizationInstance.addHandler(
                AjaxLogin.Authorization.EVENTTYPE_REQUIREDENTRIES,
                function(eventData) {
                    var __overlapNode = $('<?php echo $this->getHtmlId() ?>');
                    __overlapNode.style.display = '';
                }
            );
        }
    );
</script>