<?php 
	$collection = Mage::getModel('cms/block')->getCollection()
    ->addFieldToFilter('identifier', array('like'=>'testimonial'.'%'))
    ->addFieldToFilter('is_active', 1);
    ?>
<div class="testimonial-wrapper">
	<div class="image-testimonial">
		<img src="<?php echo $this->getSkinUrl('images/testimonials-image.jpg');?>">
	</div>
	<div class="wrap-slider-testi">
	<div id="slides">
	<?php  
	    $blockNum = 1;
	    $_blockId = $this->getIdentifier();
	    foreach($collection as $value){
		    $block_ID = $_blockId . $blockNum;
		    $blockNum++;    
		
		    $_block = $this->getLayout()->createBlock('cms/block')->setBlockId($block_ID);
		
		    if ($_block) : 
			     ?>
			     <div>
			     	<div class="testimonial">
			     <?php echo $_block->toHtml();   ?>
			     	</div>
			     </div>
		<?php
		    endif;
		}
	?>
		<a class="slidesjs-previous slidesjs-navigation" href="#"><?php echo $this->__('Prev') ?></a>
		<a class="slidesjs-next slidesjs-navigation" href="#"><?php echo $this->__('Next') ?></a>
	</div>
	<p class="view_all"><a href="<?php echo Mage::getBaseUrl(); ?>testimonials">MORE TESTIMONIALS</a></p>
	</div>
</div>
<script type="text/javascript">// <![CDATA[
jQuery(window).load(function() {
jQuery('#slides').slidesjs({
width: 376,
navigation: false,
pagination: false,
play: {
		     auto: true,
		     interval: 10000,
	     },
effect: {
		      slide: {
		      		speed : 1500
		      		}
		      }
});
});
// ]]>
</script>