<style type="text/css">
    .page-title span {
        font-family: 'tin_doghouseregular',Calibri,Arial,Helvetica,sans-serif;
        letter-spacing: 0;
        color: #666666;
        font-size: 20px;
        font-weight: normal;
        margin: 0;
        line-height: 1.35;
        text-transform: uppercase;
    }

    .container-paymentconfirmationbox {
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
        -moz-border-top-colors: none;
        border-bottom-color: #CCAA83;
        border-bottom-style: dashed;
        border-bottom-width: 1px;
        border-image-outset: 0 0 0 0;
        border-image-repeat: stretch stretch;
        border-image-slice: 100% 100% 100% 100%;
        border-image-source: none;
        border-image-width: 1 1 1 1;
        border-left-color-ltr-source: physical;
        border-left-color-rtl-source: physical;
        border-left-color-value: #CCAA83;
        border-left-style-ltr-source: physical;
        border-left-style-rtl-source: physical;
        border-left-style-value: dashed;
        border-left-width-ltr-source: physical;
        border-left-width-rtl-source: physical;
        border-left-width-value: 1px;
        border-right-color-ltr-source: physical;
        border-right-color-rtl-source: physical;
        border-right-color-value: #CCAA83;
        border-right-style-ltr-source: physical;
        border-right-style-rtl-source: physical;
        border-right-style-value: dashed;
        border-right-width-ltr-source: physical;
        border-right-width-rtl-source: physical;
        border-right-width-value: 1px;
        border-color: #CCAA83;
        border-style: dashed;
        border-width: 1px;
        font-family: 'TinDoghouse';
        margin-bottom: auto;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
    }
    .container-paymentconfirmationbox .content h2 {
        background-attachment: scroll;
        background-clip: border-box;
        background-color: rgba(0, 0, 0, 0);
        background-origin: padding-box;
        background-position: 0 0;
        background-repeat: repeat-x;
        background-size: auto auto;
        border-bottom-color: #CCAA83;
        border-bottom-style: dashed;
        border-bottom-width: 1px;
        color: #C65C4F;
        font-family: 'tin_doghouseregular';
        font-size: 14px;
        font-weight: normal;
        margin-bottom: 30px;
        margin-left: 0;
        margin-right: 0;
        margin-top: 0;
        padding-bottom: 10px;
        padding-left: 35px;
        padding-right: 35px;
        padding-top: 10px;
        text-transform: uppercase;
    }
    .clearfix {
        clear: both;
    }
</style>

<div class="">
    <div class="page-title">
        <span><?php echo $this->__('Konfirmasi Pembayaran'); ?></span>
    </div>
    
    <div class="container-paymentconfirmationbox" style="border:0">
        <form id="paymentconfirmationForm" method="post" action="<?php echo $this->getFormActionUrl(); ?>">
            <div class="registered-users">
                <div class="content" style="text-align:center;">
                    <h2 style="border:0"><?php echo $this->message; ?></h2>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    document.forms.paymentconfirmationForm.email.focus();
    var dataForm = new VarienForm('paymentconfirmationForm', true);
    //]]>
</script>



