<div class="page-title">
    <h1><?php echo $this->__('BCA KlikPay'); ?></h1>
</div>

<?php $data = $this->getFormData(); ?>

<form id="form_auto_post" name="form_auto_post" action="<?php echo $this->getKlikpaySubmitUrl(); ?>" method="post">
    <br/><input type="hidden" id="klikPayCode" name="klikPayCode" value="<?php echo $data['klikPayCode']; ?>" />
    <br/><input type="hidden" id="transactionNo" name="transactionNo" value="<?php echo $data['transactionNo']; ?>" />
    <br/><input type="hidden" id="totalAmount" name="totalAmount" value="<?php echo $data['totalAmount']; ?>" />
    <br/><input type="hidden" id="currency" name="currency" value="<?php echo $data['currency']; ?>" />
    <br/><input type="hidden" id="payType" name="payType" value="<?php echo $data['payType']; ?>" />
    <br/><input type="hidden" id="callback" name="callback" value="<?php echo $data['callback']; ?>" />
    <br/><input type="hidden" id="transactionDate" name="transactionDate" value="<?php echo $data['transactionDate']; ?>" />
    <br/><input type="hidden" id="descp" name="descp" value="<?php echo $data['descp']; ?>" />
    <br/><input type="hidden" id="miscFee" name="miscFee" value="<?php echo $data['miscFee']; ?>" />
    <br/><input type="hidden" id="signature" name="signature" value="<?php echo $data['signature']; ?>" />
	
    <div id="checkoutSteps">
        <button class="button" onclick="do_submit();" title="<?php echo $this->__('Confirm redirect'); ?>" type="button">
            <span>
                <span><?php echo $this->__('Confirm redirect'); ?></span>
            </span>
        </button>
    </div>	
</form>
<br /><br />
<p><?php echo $this->__('This page will be redirected to BCA KlikPay page in ' . $this->getRedirectTimeout() . ' seconds.'); ?></p>

<script language="javascript" type="text/javascript">
    //<![CDATA[
    var redirectTimeout = <?php echo $this->getRedirectTimeout(); ?>;
    setTimeout('do_submit()', redirectTimeout * 1000);

    function do_submit() {
        document.form_auto_post.submit();
    }
    //]]>
</script>
