<script type="text/javascript">
	$j(document).ready(function(){
		$j('.wrap-button-shortcut a[href^="#"]').on('click',function (e) {
			e.preventDefault();
			var target = this.hash,
				targetx = jQuery(target);
			$j('html, body').stop().animate({
				'scrollTop': targetx.offset().top
			}, 500, 'swing', function () {
				window.location.hash = target;
			});
		});
	});
	
</script>

<?php $items = $this->getItems() ?>
<div class="page-head">
<h3><?php echo $this->getHeader()?></h3>
</div>
<div class="wrap-button-shortcut">
    <?php foreach ($items as $letters): ?>
        <?php foreach ($letters as $letter => $options): ?>
            <a class="button-shortcut" href="#<?php echo $letter ?>">
                <?php echo $letter?>
            </a>
        <?php endforeach ?>
    <?php endforeach ?>
</div>

<div class="content-list">
<?php if ($items): ?>
<?php $width = floor(100/count($items)) ?>
<?php foreach ($items as $letters): ?>
    <div style="float:left; width:<?php echo $width ?>%">
    <?php foreach ($letters as $letter => $options): ?>
    <dl id="<?php echo $letter ?>">
        <dt><?php echo $letter ?></dt>
        <dd>
            <ul class="bare-list">
            <?php foreach ($options as $o): ?>
                <li>
                    <a href="<?php echo $o['url'] ?>"><?php echo $this->htmlEscape($o['label']) ?></a> <?php if ($this->getShowCounts()) { echo '('.$o['cnt'].')'; } ?>
                </li>
            <?php endforeach ?>
            </ul>
        </dd>
    </dl>
    <?php endforeach ?>
    </div>
<?php endforeach ?>
<?php endif ?>
</div>