<?php

?>
<div class="contactForm-leftbox">
<!--<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>-->

<form action="<?php echo Mage::getBaseUrl().$this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="fieldsets">
        <h3><?php echo Mage::helper('tanyadokter')->__('TANYA DOKTER') ?></h3>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><?php echo Mage::helper('tanyadokter')->__('Name') ?><em>*</em></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('tanyadokter')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('tanyadokter')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><?php echo Mage::helper('tanyadokter')->__('Email') ?><em>*</em></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('tanyadokter')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('tanyadokter')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li class="fields">
             	<div class="field">
                    <label for="telephone"><?php echo Mage::helper('tanyadokter')->__('Telephone') ?></label>
                    <div class="input-box">
                        <input name="telephone" id="telephone" title="<?php echo Mage::helper('tanyadokter')->__('Telephone') ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
            </li>
            <li class="fields">
            	<div class="field">
                    <label for="comment" class="required"><?php echo Mage::helper('tanyadokter')->__('Comment') ?><em>*</em></label>
                    <div class="input-box">
                        <textarea name="comment" id="comment" title="<?php echo Mage::helper('tanyadokter')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('tanyadokter')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('tanyadokter')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('tanyadokter')->__('Submit') ?></span></span></button>
    </div>
</form>
</div>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
