<?php echo $this->getChildHtml('items_before'); ?>
<form name="co-installment-form" id="co-installment-form" action="">
    <div id="checkout-review-table-wrapper">
        <table class="data-table" id="checkout-review-table">
            <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <col width="1" />
            <?php endif; ?>
            <thead>
                <tr>
                    <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
                    <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
                    <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                    <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                <?php endif; ?>
            </thead>
            <?php echo $this->getChildHtml('totals'); ?>
            <tbody>
            <?php print_r($this->getItems()); ?>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item)?>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>

    <?php echo $this->getChildHtml('items_after'); ?>
    <?php echo $this->getChildHtml('items_installment'); ?>
    <?php echo $this->getChildHtml('items_installment_scb'); ?>

</form>

<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();

//]]>
</script>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        
          <!-- start add -->  
          
          <div class="discount">
            <h2><?php echo $this->__('Voucher Code') ?></h2>
            <div class="discount-form">
                <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
                <input type="hidden" name="remove" id="remove-coupone" value="0" />
                <div class="input-box">
                    <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
                </div>
                <div class="buttons-set">
                    <button onclick="return cekCustomVoucher(false)" type="button" title="<?php echo $this->__('Apply Voucher') ?>" class="button apply-voucher" value="<?php echo $this->__('Apply Voucher') ?>"><span><span><?php echo $this->__('Apply Voucher') ?></span></span></button>
                    <?php if(strlen($this->getCouponCode())): ?>
                        &nbsp; <button type="button" title="<?php echo $this->__('Cancel Voucher') ?>" class="button cancel-voucher" onclick="return cekCustomVoucher(true)" value="<?php echo $this->__('Cancel Voucher') ?>"><span><span><?php echo $this->__('Cancel Voucher') ?></span></span></button>
                    <?php endif;?>
                </div>
                <div id="feedback" style="color: red"><?php echo $this->getSessionMessage();?></div>
            </div>
        </div>
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a>
        </p>
        <!-- end add -->
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'), $('co-installment-form'));
    //]]>
    </script>

</div>



<div id="threedsecure-popup" class="success-form-popup">
    <div class="popup">
        <form target="_blank" action="" method="post" id="event-form" name="event_form">
        <div class="blockbkg" id="bkg">
            <div class="cont" id="dlg">
                <iframe src=""></iframe>
            </div>
        </div>
        </form>
        <div style="clear: both;"></div>
    </div>
</div>
