<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit/Debit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit/Debit Card Number') ?>" class="input-text required-entry validate-number validate-length minimum-length-16 maximum-length-16 card-number cc-issuer-check" value="" maxlength="16" autocomplete="off" />
        </div>
    </li>
    
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->getNameOnCard(); ?>" />
        </div>
    </li>
    
    <!-- credit card type box -->
    <input type="hidden" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" />
    <input type="hidden" id="<?php echo $_code ?>_cc_bank" name="payment[cc_bank]" />
    <input type="hidden" id="<?php echo $_code ?>_cc_bins" name="payment[cc_bins]" />
    <input type="hidden" id="<?php echo $_code ?>_acquired_bank" name="payment[acquired_bank]" />
    <input type="hidden" id="<?php echo $_code ?>_secure" name="payment[secure]" />
    <input type="hidden" id="<?php echo $_code ?>_secure_min" name="payment[secure_min]" />
    <input type="hidden" id="<?php echo $_code ?>_installment_process" name="payment[installment_process]" />
    
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry card-expiry-month">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k => $v): ?>
                    <?php $val = (strlen($k) == 1 && $k != 0) ? '0' . $k : $k; ?>
                    <option value="<?php echo $val ? $val : ''; ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry card-expiry-year">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    
    <?php echo $this->getChildHtml(); ?>
    <?php if ($this->hasVerification()): ?>
        <li>
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="password" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-number card-cvv" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" maxlength="4" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>
    <?php endif; ?>
    <?php if ($this->hasSsCardType()): ?>
        <li id="<?php echo $_code ?>_cc_type_ss_div">
            <ul class="inner-form">
                <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
                <li>
                    <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                    <span class="input-box">
                        <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
                    </span>
                </li>

                <li>
                    <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if ($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                            <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if ($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </li>
                <li class="adv-container">&nbsp;</li>
            </ul>
            <script type="text/javascript">
            //<![CDATA[
            var SSChecked<?php echo $_code ?> = function() {
                var elm = $('<?php echo $_code ?>_cc_type');
                if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                    $('<?php echo $_code ?>_cc_type_ss_div').show();
                } else {
                    $('<?php echo $_code ?>_cc_type_ss_div').hide();
                }
            };

            Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
            SSChecked<?php echo $_code ?>();
            //]]>
            </script>
        </li>
    <?php endif; ?>
        
    <?php if ($this->checkZipCode() === false): ?>
        <li>
            <label for="<?php echo $_code ?>_cc_zipcode"><?php echo $this->__('ZIP/Postal Code'); ?> <em>*</em></label>
            <span class="input-box">
                <input type="text" title="<?php echo $this->__('Postal Code') ?>" class="input-text required-entry validate-number validate-zip" id="<?php echo $_code ?>_cc_zipcode" name="payment[cc_zipcode]" style="width:100px;" />
            </span>
        </li>
    <?php endif; ?>
</ul>
