<?php $order = $this->getItem()->getOrder(); ?>
<?php $payCode = $order->getPayment()->getMethodInstance()->getCode(); ?>

<?php if ($items = $this->getItem()): ?>
    <h5 class="title">
        <span id="order_item_<?php echo $items->getId() ?>_title">
            <?php echo $this->htmlEscape($items->getName()); ?>
        </span>
    </h5>

    <div>
        <strong><?php echo $this->helper('sales')->__('SKU'); ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->htmlEscape($this->getSku()))); ?>
    </div>

    <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($this->getOrderOptions() as $option): ?>
                <dt><?php echo $option['label'] ?></dt>
                <dd>
                    <?php if (isset ($option['custom_view']) && $option['custom_view']): ?>
                        <?php echo $this->getCustomizedOptionValue($option); ?>
                    <?php else: ?>
                        <?php $option = $this->getFormattedOption($option['value']); ?>
                        <?php echo $option['value']; ?>
                        <?php if (isset ($option['remainder']) && $option['remainder']): ?>
                            <span id="<?php echo $_dots = 'dots' . uniqid()?>"> ...</span>
                            <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $option['remainder']; ?></span>
                            <script type="text/javascript">
                                $('<?php echo $_id ?>').hide();
                                $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                                $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_dots?>').hide();});
                                $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                                $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_dots ?>').show();});
                            </script>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>

    <!-- showing installment option -->
    <?php if ($items->getInstallment()): ?>
        <div>
            <strong><?php echo $this->helper('sales')->__('Installment tenor:') ?></strong>
            <?php echo $items->getInstallmentType(); ?>
        </div>
    <?php endif; ?>
    
    <?php echo $this->htmlEscape($items->getDescription()); ?>
<?php endif; ?>
