<form id="formbuilder-<?php echo $this->blockId; ?>" action="/baby/formbuilder/index/submit" method="post">
	<input id="form_id" type="hidden" name="form_id" value="<?php echo $this->blockId; ?>">
	<div class="formbuilder-header"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->block->static_info)->toHtml(); ?></div>
	<div class="formbuilder-form">
		<ul>
		<?php 
		foreach($this->inputs->getData() as $input){
		?>
		<li>
			<div>
				<label class="required" for="<?php echo $input["name"]; ?>"><?php echo $input["title"]; ?><em><?php if($input["required"] == true) echo '*'; ?></em></label>
			</div>
			<div>:</div>
			<div>
			<?php if($input["type"] == "text"){ ?>
				<input id="<?php echo $input["name"]; ?>" class="formbuilder-input" title="<?php echo $input["title"]; ?>" name="inputs[<?php echo $input["group"]; ?>]" />
			<?php }else if($input["type"] == "textarea"){ ?>
				<textarea id="<?php echo $input["name"]; ?>" class="formbuilder-textarea" title="<?php echo $input["title"]; ?>" name="inputs[<?php echo $input["group"]; ?>]"></textarea>
			<?php } ?>
			</div>
		</li>
		<?php 
		}
		?>
		</ul>
	</div>
	<div class="formbuilder-info">
		<p class="required">*Required Fields</p>
	</div>
	<div class="formbuilder-submit">
		<button class="button" title="" type="submit">Submit</button>
	</div>
</form>

<div class="formbuilder-success"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->block->static_success)->toHtml(); ?></div>
