<script type="text/javascript">
jQuery(function(){
	var x = '<?php echo Mage::getSingleton('core/session')->getStatusForm(); ?>';
console.log(x);
	if(x=='Saved')
	{
		document.getElementById("formbuilder-form").style.display="none";
	}else{
		document.getElementById("formbuilder-form").style.display="block";
	}
});
</script>

<form id="formbuilder-<?php echo $this->blockId; ?>" action="/baby/formbuilder/index/submit" method="post">
	<input id="form_id" type="hidden" name="form_id" value="<?php echo $this->blockId; ?>">
	<div class="formbuilder-header"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->block->static_info)->toHtml(); ?></div>
	<div class="formbuilder-form" id="formbuilder-form" style="margin: 0 15%; width: 60%;">
		<ul>

		<?php 
		foreach($this->inputs->getData() as $input){
		?>
		<li style="list-style-type: none;">
			<div style="clear: both; margin-bottom: 20px;">
				<label class="required" style="float: left; width: 140px;" for="<?php echo $input["name"]; ?>"><?php echo $input["title"]; ?><em><?php if($input["required"] == true) echo '*'; ?></em></label>
			<?php if($input["type"] == "text"){ ?>
				<input id="<?php echo $input["name"]; ?>" class="input-text required-entry validate-digits" min="1" max="2" style="height: 26px !important; width: 40% !important; background: none repeat scroll 0 0 #F9F9F9; border: none; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1) inset; color: #666666; padding: 7px 5px; float: left; margin-right: 60px;" title="<?php echo $input["title"]; ?>" name="inputs[<?php echo $input["group"]; ?>]" />
			<?php }else if($input["type"] == "textarea"){ ?>
				<textarea id="<?php echo $input["name"]; ?>" class="required-entry input-text" style="height: 100px !important; width: 40% !important; background: none repeat scroll 0 0 #F9F9F9; border: none; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1) inset; color: #666666; padding: 7px 5px; float: left; margin-right: 60px;" rows="3" cols="5" title="<?php echo $input["title"]; ?>" name="inputs[<?php echo $input["group"]; ?>]"></textarea>
			<?php } ?>
			</div>
			<div style="clear: both;">
			</div>
		</li>

		<?php 
		}
		?>
		</ul>
	<div style="clear: both;"></div>
<p class="required" style="float: left; color: #eb340a; margin-left: 160px;">*Required Fields</p>
<input id="hideit" style="display: none !important;" type="text" name="hideit" /><br /><button onclick="formbuilder(1)" class="button" title="" type="submit" style="margin-left: -80px !important;"> <span class="fb-bebas fb-15" style="padding: 10px 20px; border: none; background: #ffa01b; font-weight: normal;">Submit</span></button>
	</div>
<div style="padding-left: 40em; margin-top: -30px; clear: both; width: 60%; padding: 0 15%;">
</div>

</form>

<div class="formbuilder-success" style="margin-left: 270px !important;"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->block->static_success)->toHtml(); ?></div>
