<?php echo $this->getChildHtml('global_messages'); ?>



<div class="share-social-media">Bagikan:
    <!--<a href="https://www.facebook.com/sharer/sharer.php?u=<?php // echo $this->getShareUrl(); ?>" target="_blank"><img src="<?php // echo $this->getMediaUrl() . 'wysiwyg/static-page-img/referall/fb-share.jpg'; ?>" alt="facebook share"/></a>
   
    <a href="https://twitter.com/home?status=<?php // echo $this->getShareUrl(); ?>" target="_blank"><img src="<?php // echo $this->getMediaUrl() . 'wysiwyg/static-page-img/referall/twitter-share.jpg'; ?>" alt="facebook share"/></a>-->
</div>
    <div class="wrap-form">
        <form id="share-form" method="post" action="<?php echo $this->getBaseUrl(); ?>formbuilder/index/share">
            <input type="hidden" name="form_id" value="<?php echo $this->getFormId(); ?>" />
            <input type="hidden" name="record_id" value="<?php echo $this->getRecordId(); ?>" />
            <input type="hidden" name="ref" value="<?php echo $this->getRef(); ?>" />
            <input type="hidden" name="url_ref" value="<?php echo $this->getRefUrl(); ?>" />
            <input type="hidden" name="url_share" value="<?php echo $this->getShareUrl(); ?>" />
            
            <?php for ($i = 1; $i <= 5; $i++): ?>
                <div class="input-box">
                    <?php
                    $requiredIcon = '';
                    $requiredClass = '';

                    if ($i == 1):
                        $requiredIcon = '<em>*</em>';
                        $requiredClass = 'required-entry';
                    endif;
                    ?>

                    <label for="email_<?php echo $i; ?>" class="">
                        Email <?php echo $requiredIcon; ?>
                    </label>

                    <input type="text" name="email[]" title="Email" class="<?php echo $requiredClass; ?> validate-email" id="email_<?php echo $i; ?>" placeholder="join@youremail.com" />
                </div>
            <?php endfor; ?>
            
            <div class="input-box">
                <label>Subject:</label>
                <input type="text" name="subject" id="subject" placeholder="Daftar & dapatkan diskon langsung 25%" />
            </div>
            
            <div class="textarea-box">
                <textarea type="text" name="content" id="content" placeholder="Ayo daftarkan E-mail di Bilna.com untukmendapatkan promo dan diskon menarik untuk kebutuhan keluarga Anda"></textarea>
            </div>
            
            <button type="submit" class="button">
                Send
            </button>
        </form>
    </div>


<script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('share-form');
    //]]>
</script>
