<?php
/**
 *
 * @category    Bilna
 * @package     Bilna_Wrappinggiftevent
 * @copyright   Copyright (c) 2014 PT Bilna. (http://www.bilna.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * One page checkout 
 *
 * @category   Bilna
 * @category   Bilna
 * @package    Bilna_Wrappinggiftevent
 * @author     Bilna Development Team <development@bilna.com>
 */
?>
<?php if ($this->getTotal()->getValue()): ?>
    <tr>    
        <td class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getTotal()->getTitle(); ?>
        </td>
        <td class="a-right">
            <?php echo Mage::helper('checkout')->formatPrice($this->getTotal()->getValue()); ?>
        </td>
    </tr>
<?php endif; ?>