<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <div>
        <?php echo $this->getMethod()->getConfigData('instructions'); ?>
    </div>
    <br/>
    <li>
        <label for="cc_bins" class="required"><em>*</em><?php echo $this->__('Input 6 first digit number of your credit card:') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Input 6 first digit number of your credit card:') ?>" class="input-text required-entry cc-issuer-check" id="cc_bins" name="payment[cc_bins]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_bins')); ?>" data-bank="<?php echo $this->getDataBankIssuer(); ?>" maxlength="6" />
            <input type="hidden" id="bin_code" name="bin_code" />
        </span>
    </li>
</ul>
