<?php
/**
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    design
 * @package     rtb
 * @copyright   Copyright (c) 2013 Guidance Solutions (http://www.guidance.com)
 */
?>
<?php
echo $this->getLayout()->createBlock('adminhtml/catalog_category_tab_attributes', '')
    ->setGroup($this->getGroup())
    ->setAttributes($this->getAttributes())
    ->setAddHiddenFields(false)
    ->toHtml();

echo $this->getLayout()->createBlock('adminhtml/catalog_category_tab_product', 'category.product.grid')->toHtml();
?>
