<style type="text/css">
    .page-title span {
        font-family: 'tin_doghouseregular',Calibri,Arial,Helvetica,sans-serif;
        letter-spacing: 0;
        color: #666666;
        font-size: 20px;
        font-weight: normal;
        margin: 0;
        line-height: 1.35;
        text-transform: uppercase;
    }
    .link-reorder {
        background-color: #FF6839;
        padding: 6px 10px;
    }   
    .link-reorder span {
        color: #ffffff;
    }
</style>

<div class="">
    <?php
    $order = $this->getOrder();
    
    if ($order):
        $orderStatus = $order->getStatus();
        $orderStatusTitle = $this->getOrderStatusTitle($order->getStatus());
        $checkEmail = $this->checkOrderEmail($order->getCustomerEmail());
        $checkEmailMessage = $checkEmail ? $orderStatusTitle : $this->__('Invalid Email');
        $paymentMethod = $order->getPayment()->getMethodInstance()->getCode();
    else:
        $checkEmailMessage = $this->__('Invalid Order');
    endif;
    ?>

    <div class="page-title">
        <span>
            <?php echo $this->__('Order'); ?> #<?php echo $this->getOrderId(); ?> - <?php echo $checkEmailMessage; ?>
        </span>
    </div><br /><br />

    <?php if ($checkEmail): ?>
        <div class="title-buttons">
            <h3 class="table-caption"><?php echo $this->__('Items Ordered'); ?></h3>
            
            <?php if ($orderStatus == 'pending' && $paymentMethod == 'klikpay'): ?>
                <span style="font-size:16px;margin-right:5px;">
                    <a class="link-reorder" href="<?php echo $this->getPayUrl($this->getOrderId()); ?>"><span><?php echo $this->__('Pay'); ?></span></a>
                </span>
            <?php endif; ?>
        </div>
    
        <table summary="Items Ordered" id="my-orders-table" class="data-table">
            <thead>
                <tr class="first last">
                    <th style="background: none repeat scroll 0 0 #9DCA33; border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF; color: #FFFFFF; font-size: 14px; text-align: center;"><?php echo $this->__('Description'); ?></th>
                    <th style="background: none repeat scroll 0 0 #9DCA33; border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF; color: #FFFFFF; font-size: 14px; text-align: center;"><?php echo $this->__('SKU'); ?></th>
                    <th style="background: none repeat scroll 0 0 #9DCA33; border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF; color: #FFFFFF; font-size: 14px; text-align: center;"><?php echo $this->__('Price per Unit'); ?></th>
                    <th style="background: none repeat scroll 0 0 #9DCA33; border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF; color: #FFFFFF; font-size: 14px; text-align: center;"><?php echo $this->__('Qty'); ?></th>
                    <th style="background: none repeat scroll 0 0 #9DCA33; border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF; color: #FFFFFF; font-size: 14px; text-align: center;"><?php echo $this->__('Total'); ?></th>
                </tr>
            </thead>
       
            <tbody class="odd">
                <?php if ($order->getAllItems()): ?>
                    <?php foreach ($order->getAllItems() as $item): ?>
                        <?php if ($item->getParentItem()) continue; ?>

                        <tr class="border first last">
                            <td style="font-size:14px;">
                                <h3 class="product-name"><?php echo $this->htmlEscape($item->getName()); ?></h3>
                                <!--div><strong>Payment Option:</strong> Full Payment</div-->
                            </td>

                            <td style="font-size:14px;"><?php echo $this->htmlEscape($item->getSku()); ?></td>

                            <td class="a-right" style="font-size:14px;">
                                <span class="price-excl-tax">
                                    <span class="cart-price">
                                        <span class="price"><?php echo $order->formatPrice($item->getPrice()); ?></span>                    
                                    </span>
                                </span>
                                <br>
                            </td>
                            
                            <td class="a-right" style="font-size:14px;">
                                <span class="nobr">
                                    <?php if ($item->getQtyOrdered() > 0): ?>
                                        <?php echo $this->__('Ordered'); ?>: <strong><?php echo ($item->getQtyOrdered() * 1); ?></strong><br />
                                    <?php endif; ?>

                                    <?php if ($item->getQtyShipped() > 0): ?>
                                        <?php echo $this->__('Shipped'); ?>: <strong><?php echo ($item->getQtyShipped() * 1); ?></strong><br />
                                    <?php endif; ?>
                                    
                                    <?php if ($item->getQtyCanceled() > 0): ?>
                                        <?php echo $this->__('Canceled'); ?>: <strong><?php echo ($item->getQtyCanceled() * 1); ?></strong><br />
                                    <?php endif; ?>

                                    <?php if ($item->getQtyRefunded() > 0): ?>
                                        <?php echo $this->__('Refunded'); ?>: <strong><?php echo ($item->getQtyRefunded() * 1); ?></strong><br />
                                    <?php endif; ?>
                                </span>
                            </td>

                            <td class="a-right last" style="font-size:14px;">
                                <span class="price-excl-tax">
                                    <span class="cart-price">
                                        <span class="price"><?php echo $order->formatPrice($item->getRowTotal()); ?></span>
                                    </span>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                    <tr>
                        <td colspan="3" class="a-right" style="font-size:14px;">
                            <?php echo $this->__('Subtotal'); ?>
                        </td>

                        <td colspan="2" class="a-right last" style="font-size:14px;">
                            <span class="price">
                                <?php echo $order->formatPrice($order->getSubtotal()); ?>
                            </span>
                        </td>
                    </tr>

                    <tr>
                        <td colspan="3" class="a-right" style="font-size:14px;">
                            <?php echo $this->__('Shipping & Handling'); ?>
                        </td>

                        <td colspan="2" class="a-right last" style="font-size:14px;">
                            <span class="price">
                                <?php echo $order->formatPrice($order->getShippingAmount()); ?>
                            </span>
                        </td>
                    </tr>

                    <?php if ($order->getWrappinggiftevent()): ?>
                    <tr>
                        <td colspan="3" class="a-right" style="font-size:14px;">
                            <?php echo $this->__('Wrapping Fee'); ?>
                        </td>

                        <td colspan="2" class="a-right last" style="font-size:14px;">
                            <span class="price">
                                <?php echo $order->formatPrice($order->getWrappinggiftevent()); ?>
                            </span>
                        </td>
                    </tr>
                    <?php endif; ?>
                    
                    <?php if ($order->getDiscountAmount() && $order->getDiscountAmount() > 0): ?>
                        <tr>
                            <td colspan="3" class="a-right" style="font-size:14px;">
                                <?php echo $this->__('Discount'); ?>
                            </td>

                            <td colspan="2" class="a-right last" style="font-size:14px;">
                                <span class="price">
                                    <?php echo $order->formatPrice($order->getDiscountAmount()); ?>
                                </span>
                            </td>
                        </tr>
                    <?php endif; ?>
                    
                    <?php if ($order->getMoneyForPoints()): ?>
                        <tr>
                            <td colspan="3" class="a-right" style="font-size:14px;">
                                <?php echo $this->__('Reward point(s)'); ?>
                            </td>

                            <td colspan="2" class="a-right last" style="font-size:14px;">
                                <span class="price">
                                    <?php echo $order->formatPrice($order->getMoneyForPoints()); ?>
                                </span>
                            </td>
                        </tr>
                    <?php endif; ?>

                    <tr>
                        <td colspan="3" class="a-right" style="font-size:14px;">
                            <strong><?php echo $this->__('Grand Total'); ?></strong>
                        </td>

                        <td colspan="2" class="a-right last" style="font-size:14px;">
                            <span class="price">
                                <strong><?php echo $order->formatPrice($order->getGrandTotal()); ?></strong>
                            </span>
                        </td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    <?php endif; ?>

    <?php if ($checkEmail): ?>
        <?php if (!$order->getIsVirtual()): ?>
            <div class="col2-set order-info-box">
                <div class="col-1">
                    <div class="box">
                        <div class="box-title">
                            <h2><?php echo $this->__('Shipping Address'); ?></h2>
                        </div>

                        <div>
                            <span><a href="<?php echo $this->getLoginRegisterUrl(); ?>"><?php echo $this->__('Please login or register'); ?></a>
                        </div>
                    </div>
                </div>

                <div class="col-2">
                    <div class="box">
                        <div class="box-title">
                            <h2><?php echo $this->__('Billing Address'); ?></h2>
                        </div>

                        <div>
                            <span><a href="<?php echo $this->getLoginRegisterUrl(); ?>"><?php echo $this->__('Please login or register'); ?></a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    
        <div class="col2-set order-info-box">
            <div class="col-1">
                <div class="box">
                    <div class="box-title">
                        <h2><?php echo $this->__('Shipping Method') ?></h2>
                    </div>
                    
                    <div class="box-content">
                        <?php if ($order->getShippingDescription()): ?>
                            <h4><?php echo $this->escapeHtml($order->getShippingDescription()) ?></h4>
                        <?php else: ?>
                            <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <div class="box box-payment">
                    <div class="box-title">
                        <h2><?php echo $this->__('Payment Method'); ?></h2>
                    </div>
                    <div class="box-content">
                        <h4><?php echo $this->escapeHtml($order->getPayment()->getMethodInstance()->getTitle()); ?></h4>
                            
                        <?php if ($order->getPayment()->getMethodInstance()->getConfigData('message')): ?>
                            <table>
                                <tbody>
                                    <tr>
                                        <td><?php echo nl2br($order->getPayment()->getMethodInstance()->getConfigData('message')); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <div class="buttons-set">
        <p class="back-link">
            <a href="<?php echo $this->getGuestOrderFormUrl(); ?>"><small>«</small> <?php echo $this->__('Back to Guest Order Form'); ?></a>
        </p>
    </div>
</div>
