<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.6.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>

<?php if ($this->isEnabled()): ?>
    <div  id="aw_points-history-box" style="margin-bottom:30px;">
        <?php $transactions = $this->getTransactions(); ?>
        <?php if ($transactions->getSize()): ?>
            <h4 style="font-size:17px;"><?php echo $this->__('CREDITS HISTORY') ?></h4>
            <?php //echo $this->getPagerHtml(); ?>
			<div class="toolbar"><?php echo $this->getPagerHtml(); ?></div>
            <table class="data-table" id="points-history-table" style="border-bottom:1px dashed #ccaa83;padding-bottom: 10px;">
                <col class="id" />
                <col class="points" />
                <col class="comment" />
                <col class="date" />
                <thead>
                    <tr>
                        <!--<th style="background: none repeat scroll 0 0 #9DCA33;
							border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF;
							color: #FFFFFF;
							font-size: 14px;
							text-align: center;"><?php //echo $this->__('ID') ?></th>-->
                        <th style="background: none repeat scroll 0 0 #9DCA33;
							border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF;
							color: #FFFFFF;
							font-size: 14px;
							text-align: center;"><?php echo $this->__('Credits') ?></th>
                        <th style="background: none repeat scroll 0 0 #9DCA33;
							border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF;
							color: #FFFFFF;
							font-size: 14px;
							text-align: center;width: 75%;"><?php echo $this->__('Comment') ?></th>
                        <th style="background: none repeat scroll 0 0 #9DCA33;
							border-right: 1px solid #FFFFFF; border-top:1px solid #FFF; border-bottom:1px solid #FFF;
							color: #FFFFFF;
							font-size: 14px;
							text-align: center;width: 100%;"><?php echo $this->__('Date') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($transactions as $transaction): ?>
                        <?php $balanceChange = $transaction->getBalanceChange(); ?>
                        <tr>
                            <!--<td><?php //echo $transaction->getId(); ?></td>-->
                            <td style="text-align: right;"><?php echo ($balanceChange > 0 ? "+" . $balanceChange : $balanceChange); ?></td>
                            <td><?php echo $this->__($transaction->getActionInstance()->getCommentHtml(AW_Points_Model_Actions_Abstract::FRONTEND)); ?></td>
                            <td>
                                <?php echo $this->formatDate($transaction->getChangeDate(), 'short', true); ?>
                                <div class="aw-expiration-in-table">
                                    <?php if ($transaction->getExpirationDate())
                                        echo $this->__('Expires on %s', $this->formatDate($transaction->getExpirationDate(), 'short', true)) ?>
                                </div>
                            </td>
                        </tr>
        <?php endforeach; ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('points-history-table');</script>
            <?php //echo $this->getPagerHtml(); ?>
    <?php endif ?>
    </div>
    <?php
 endif ?>