<div class="mobile-left-menu">
    <div class="wrap-left-menu">
        <div class="back-button back-top">
            Hide Menu
        </div>	
        <div class="title-mobile-menu">
			shop by category :
		</div>
        <?php
        $_helper = Mage::helper('megamenu');
        $_storeCategories = $_helper->getMegamenuData();
        $_storeCurrentCategory = Mage::registry('current_category');
        $_categoryActive = $this->getCurrentMainCategoryIdActive();
        ?>

        <?php if (count($_storeCategories) > 0): ?>
            <div class="wrap-menu-cat">
                <ul>
                    <?php foreach ($_storeCategories as $_storeCategory): ?>
                        <?php
                        $_id = $_storeCategory['id'];
                        $_name = $_storeCategory['name'];
                        $_url = $_storeCategory['url'];
                        $_urlKey = $_storeCategory['url_key'];
                        $_storeCategoryClass = ($_id == $_categoryActive) ? "active-category menu-active" : "";
                        ?>
                    
                        <li class="<?php echo $_storeCategoryClass; ?> <?php echo $_id; ?>">
                            <p class="first-level" data-left-menu="<?php echo $_id; ?>"><?php echo $_name; ?></p>
                            
                            <?php
                            $_storeCategoriesChild = array ();
            
                            if ($_storeCategory['child'] && count($_storeCategory['child'] > 0)):
                                $_storeCategoriesChild = $_storeCategory['child'];
                            endif;
                            ?>
                            
                            <?php if (count($_storeCategoriesChild) > 0): ?>
                                <div class="wrap-first-level">
                                    <ul>
                                        <?php foreach ($_storeCategoriesChild as $_storeCategoryChild): ?>
                                            <?php
                                            $_id2 = $_storeCategoryChild['id'];
                                            $_name2 = $_storeCategoryChild['name'];
                                            $_url2 = $_storeCategoryChild['url'];
                                            $_urlKey2 = $_storeCategoryChild['url_key'];
                                            ?>
                                        
                                            <li class="second-level"><a href="<?php echo $_url2; ?>"><?php echo $_name2; ?></a></li>
                                            
                                            <?php
                                            $_storeCategoriesChildChild = array ();
            
                                            if ($_storeCategoryChild['child'] && count($_storeCategoryChild['child'] > 0)):
                                                $_storeCategoriesChildChild = $_storeCategoryChild['child'];
                                            endif;
                                            ?>
                                            
                                            <?php if (count($_storeCategoriesChildChild) > 0): ?>
                                                <?php foreach ($_storeCategoriesChildChild as $_storeCategoryChildChild): ?>
                                                    <?php
                                                    $_id3 = $_storeCategoryChildChild['id'];
                                                    $_name3 = $_storeCategoryChildChild['name'];
                                                    $_url3 = $_storeCategoryChildChild['url'];
                                                    $_urlKey3 = $_storeCategoryChildChild['url_key'];
                                                    ?>
                                            
                                                    <li>
                                                        <a href="<?php echo $_url3; ?>"><?php echo $_name3; ?></a>
                                                    </li>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    </div>
    
    <div class="back-button back-left"></div>	
</div>

<script type="text/javascript">
    $j(document).ready(function() {
        $j('.nav-container-mobile .store-category > a').live('click', function() {
            if (!$j(this).next().is(':visible')) {
                if ($j(this).parent().hasClass('inactive')) {
                    window.location.href = $j(this).attr('href');
                }
                else {
                    if ($j(this).next().length > 0) {
                        $j('.nav-container-mobile .store-category > ul').hide();
                        $j('.nav-container-mobile .store-category2 > ul').hide();
                        $j(this).next().show();
                        $j(this).addClass('active');
                        
                        $j('.nav-container-mobile-left .store-category > ul').hide();
                        $j('.nav-container-mobile-left .store-category2 > ul').hide();
                        $j('.nav-container-mobile-left .store-category > ul#ul-' + $j(this).attr('id')).show();
                    }
                    
                    return false;
                }
            }
            else {
                window.location.href = $j(this).attr('href');
            }
        });
        
        $j('.nav-container-mobile .store-category2 > a').live('click', function() {
            if (!$j(this).next().is(':visible')) {
                if ($j(this).next().length > 0) {
                    $j('.nav-container-mobile .store-category2 > ul').hide();
                    $j(this).next().show();
                    $j(this).addClass('active');

                    $j('.nav-container-mobile-left .store-category > ul').hide();
                    $j('.nav-container-mobile-left .store-category > ul#ul-' + $j(this).attr('parent')).show();
                    $j('.nav-container-mobile-left .store-category2 > ul').hide();
                    $j('.nav-container-mobile-left .store-category2 > a#' + $j(this).attr('id')).next().show();
                    $j('.nav-container-mobile-left .store-category2 > a#' + $j(this).attr('id')).addClass('active');
                    
                    return false;
                }
            }
            
            window.location.href = $j(this).attr('href');
        });
        
        $j('.nav-container-mobile-left .store-category > a').live('click', function() {
            if (!$j(this).next().is(':visible')) {
                if ($j(this).parent().hasClass('inactive')) {
                    window.location.href = $j(this).attr('href');
                }
                else {
                    if ($j(this).next().length > 0) {
                        $j('.nav-container-mobile-left .store-category > ul').hide();
                        $j('.nav-container-mobile-left .store-category2 > ul').hide();
                        $j(this).next().show();
                        $j(this).addClass('active');
                        
                        $j('.nav-container-mobile .store-category > ul').hide();
                        $j('.nav-container-mobile .store-category2 > ul').hide();
                        $j('.nav-container-mobile .store-category > ul#ul-' + $j(this).attr('id')).show();
                    }
                }
                
                return false;
            }
            
            window.location.href = $j(this).attr('href');
        });
        
        $j('.nav-container-mobile-left .store-category2 > a').live('click', function() {
            if (!$j(this).next().is(':visible')) {
                if ($j(this).next().length > 0) {
                    $j('.nav-container-mobile-left .store-category > ul').hide();
                    $j('.nav-container-mobile-left .store-category2 > ul').hide();
                    $j('.nav-container-mobile-left .store-category > ul#ul-' + $j(this).attr('parent')).show();
                    $j(this).next().show();
                    $j(this).addClass('active');
                    
                    if (!$j('.nav-container-mobile .store-category > ul#ul-' + $j(this).attr('parent')).parent().hasClass('inactive')) {
                        $j('.nav-container-mobile .store-category > ul').hide();
                        $j('.nav-container-mobile .store-category2 > ul').hide();
                        $j('.nav-container-mobile .store-category > ul#ul-' + $j(this).attr('parent')).show();
                        $j('.nav-container-mobile .store-category2 > ul#ul-' + $j(this).attr('id')).show();
                        $j('.nav-container-mobile .store-category2 > a#' + $j(this).attr('id')).addClass('active');
                    }
                    else {
                        $j('.nav-container-mobile .store-category2 > ul').hide();
                    }
                    
                    return false;
                }
                else  {
                    window.location.href = $j(this).attr('href');
                }
            }
            else {
                window.location.href = $j(this).attr('href');
            }
        });
    });
</script>
