<div class="mobile-left-menu">
    <div class="wrap-left-menu">
        <div class="back-button back-top">
            BACK
        </div>	
        
        <?php
        $_helper = Mage::helper('megamenu');
        $_storeCategories = $_helper->getMegamenuData();
        $_storeCurrentCategory = Mage::registry('current_category');
        ?>

        <?php if (count($_storeCategories) > 0): ?>
            <div class="nav-container-mobile-left">
                <ul>
                    <?php $_currentMainCategory = $_helper->getCurrentMainCategory(); ?>
                    <?php foreach ($_storeCategories as $_storeCategory): ?>
                        <?php
                        $_storeCategoryDisplay = '';
                        $_storeCategoryClass = '';
                        
                        $_id = $_storeCategory['id'];
                        $_name = $_storeCategory['name'];
                        $_url = $_storeCategory['url'];
                        $_urlKey = $_storeCategory['url_key'];
                        
                        if ($_currentMainCategory != '' || !empty ($_currentMainCategory)):
                            if ($_id != $_currentMainCategory):
                                $_storeCategoryDisplay = 'style="display:none;"';
                                $_storeCategoryClass = 'inactive';
                            endif;
                        endif;
                        ?>
                    
                        <li class="cat-leveltop store-category <?php echo 'cat-leveltop-' . $_id; ?> <?php echo $_storeCategoryClass; ?>">
                            <a id="<?php echo $_id; ?>" class="categories <?php echo strtolower(str_replace(array ("&"," ","'"), "", $_name)); ?>" href="<?php echo $_url; ?>">
                                <?php echo $_name; ?>
                            </a>
                                
                            <?php
                            $_storeCategoriesChild = array ();
            
                            if ($_storeCategory['child'] && count($_storeCategory['child'] > 0)):
                                $_storeCategoriesChild = $_storeCategory['child'];
                            endif;
                            ?>
                            
                            <?php if (count($_storeCategoriesChild) > 0): ?>
                                <ul id="ul-<?php echo $_id; ?>" class="store-category-child category-child" <?php echo $_storeCategoryDisplay; ?>>
                                    <?php foreach ($_storeCategoriesChild as $_storeCategoryChild): ?>
                                        <?php
                                        $_storeCategoryDisplay2 = '';
                                        $_storeCategoryClass2 = '';
                                        
                                        $_id2 = $_storeCategoryChild['id'];
                                        $_name2 = $_storeCategoryChild['name'];
                                        $_url2 = $_storeCategoryChild['url'];
                                        $_urlKey2 = $_storeCategoryChild['url_key'];
                                        
                                        if ($_currentMainCategory != '' || !empty ($_currentMainCategory)):
                                            if ($_id2 == $_storeCurrentCategory->getId() || $_id2 == $_storeCurrentCategory->getParentId()):
                                                $_storeCategoryDisplay2 = 'style="display:block;"';
                                            endif;
                                        endif;
                                        ?>
                        
                                        <li class="store-category2">
                                            <a id="<?php echo $_id2; ?>" parent="<?php echo $_id; ?>" class="subcategories" href="<?php echo $_url2; ?>">
                                                <?php echo $_name2; ?>
                                            </a>
                                                
                                            <?php
                                            $_storeCategoriesChildChild = array ();
            
                                            if ($_storeCategoryChild['child'] && count($_storeCategoryChild['child'] > 0)):
                                                $_storeCategoriesChildChild = $_storeCategoryChild['child'];
                                            endif;
                                            ?>
                                            
                                            <?php if (count($_storeCategoriesChildChild) > 0): ?>
                                                <ul id="ul-<?php echo $_id2; ?>" class="store-category2-child category-child" <?php echo $_storeCategoryDisplay2; ?>>
                                                    <?php foreach ($_storeCategoriesChildChild as $_storeCategoryChildChild): ?>
                                                        <?php
                                                        $_id3 = $_storeCategoryChildChild['id'];
                                                        $_name3 = $_storeCategoryChildChild['name'];
                                                        $_url3 = $_storeCategoryChildChild['url'];
                                                        $_urlKey3 = $_storeCategoryChildChild['url_key'];
                                                        ?>
                                                    
                                                        <li class="store-category3">
                                                            <a class="subcategories <?php echo $_helper->getCategoryClass($_id3); ?>" href="<?php echo $_url3; ?>">
                                                                <?php echo $_name3; ?>
                                                            </a>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            <?php endif; ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    </div>
    
    <div class="back-button back-left"></div>	
</div>

<script type="text/javascript">
    $j(document).ready(function() {
        $j('.nav-container-mobile .store-category > a').live('click', function() {
            if (!$j(this).next().is(':visible')) {
                if ($j(this).parent().hasClass('inactive')) {
                    window.location.href = $j(this).attr('href');
                }
                else {
                    if ($j(this).next().length > 0) {
                        $j('.nav-container-mobile .store-category > ul').hide();
                        $j('.nav-container-mobile .store-category2 > ul').hide();
                        $j(this).next().show();
                        $j(this).addClass('active');
                        
                        $j('.nav-container-mobile-left .store-category > ul').hide();
                        $j('.nav-container-mobile-left .store-category2 > ul').hide();
                        $j('.nav-container-mobile-left .store-category > ul#ul-' + $j(this).attr('id')).show();
                    }
                    
                    return false;
                }
            }
            else {
                window.location.href = $j(this).attr('href');
            }
        });
        
        $j('.nav-container-mobile .store-category2 > a').live('click', function() {
            if (!$j(this).next().is(':visible')) {
                if ($j(this).next().length > 0) {
                    $j('.nav-container-mobile .store-category2 > ul').hide();
                    $j(this).next().show();
                    $j(this).addClass('active');

                    $j('.nav-container-mobile-left .store-category > ul').hide();
                    $j('.nav-container-mobile-left .store-category > ul#ul-' + $j(this).attr('parent')).show();
                    $j('.nav-container-mobile-left .store-category2 > ul').hide();
                    $j('.nav-container-mobile-left .store-category2 > a#' + $j(this).attr('id')).next().show();
                    $j('.nav-container-mobile-left .store-category2 > a#' + $j(this).attr('id')).addClass('active');
                    
                    return false;
                }
            }
            
            window.location.href = $j(this).attr('href');
        });
        
        $j('.nav-container-mobile-left .store-category > a').live('click', function() {
            if (!$j(this).next().is(':visible')) {
                if ($j(this).parent().hasClass('inactive')) {
                    window.location.href = $j(this).attr('href');
                }
                else {
                    if ($j(this).next().length > 0) {
                        $j('.nav-container-mobile-left .store-category > ul').hide();
                        $j('.nav-container-mobile-left .store-category2 > ul').hide();
                        $j(this).next().show();
                        $j(this).addClass('active');
                        
                        $j('.nav-container-mobile .store-category > ul').hide();
                        $j('.nav-container-mobile .store-category2 > ul').hide();
                        $j('.nav-container-mobile .store-category > ul#ul-' + $j(this).attr('id')).show();
                    }
                }
                
                return false;
            }
            
            window.location.href = $j(this).attr('href');
        });
        
        $j('.nav-container-mobile-left .store-category2 > a').live('click', function() {
            if (!$j(this).next().is(':visible')) {
                if ($j(this).next().length > 0) {
                    $j('.nav-container-mobile-left .store-category > ul').hide();
                    $j('.nav-container-mobile-left .store-category2 > ul').hide();
                    $j('.nav-container-mobile-left .store-category > ul#ul-' + $j(this).attr('parent')).show();
                    $j(this).next().show();
                    $j(this).addClass('active');
                    
                    if (!$j('.nav-container-mobile .store-category > ul#ul-' + $j(this).attr('parent')).parent().hasClass('inactive')) {
                        $j('.nav-container-mobile .store-category > ul').hide();
                        $j('.nav-container-mobile .store-category2 > ul').hide();
                        $j('.nav-container-mobile .store-category > ul#ul-' + $j(this).attr('parent')).show();
                        $j('.nav-container-mobile .store-category2 > ul#ul-' + $j(this).attr('id')).show();
                        $j('.nav-container-mobile .store-category2 > a#' + $j(this).attr('id')).addClass('active');
                    }
                    else {
                        $j('.nav-container-mobile .store-category2 > ul').hide();
                    }
                    
                    return false;
                }
                else  {
                    window.location.href = $j(this).attr('href');
                }
            }
            else {
                window.location.href = $j(this).attr('href');
            }
        });
    });
</script>
