<?php
/**
 * Magento Enterprise Edition
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    design
 * @package     enterprise_rtb
 * @copyright   Copyright (c) 2013 Guidance Solutions (http://www.guidance.com)
 *
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>

<?php
$_helper = Mage::helper('megamenu');
$_storeCategories = $_helper->getMegamenuData();
$_categoryActive = $this->getCategoryActive();
?>

<?php if (count($_storeCategories) > 0): ?>
    <?php foreach ($_storeCategories as $_storeCategory): ?>
        <?php
        $_id = $_storeCategory['id'];
        $_name = $_storeCategory['name'];
        $_url = $_storeCategory['url'];
        $_urlKey = $_storeCategory['url_key'];
        
        $_currentMainCategory = $_helper->getCurrentMainCategory();
        $_storeCategorySubClass = $_id == $_categoryActive['subcategory'] ? "sub-active" : "";
        ?>

        <div id="nav-<?php echo $_id; ?>" class="nav-container container nav-<?php echo $_urlKey; ?> <?php echo $_storeCategorySubClass; ?>" style="display:none;">
            <?php
            $_storeCategoriesChild = array ();
            
            if ($_storeCategory['child'] && count($_storeCategory['child'] > 0)):
                $_storeCategoriesChild = $_storeCategory['child'];
            endif;
            
            ?>
            <?php if (count($_storeCategoriesChild) > 0): ?>
                <ul id="nav" class="nav">
                    <li class="level0 level-top shop-by">
                        <span>Shop by</span>
                        <a class="level-top link-shopby" href="#">Shop by</a>
                        <?php echo $_storeCategory['shopby']; ?>
                    </li>
                    
                   <?php foreach ($_storeCategoriesChild as $_storeCategoryChild): ?>
                        <?php
                        $_id2 = $_storeCategoryChild['id'];
                        $_name2 = $_storeCategoryChild['name'];
                        $_url2 = $_storeCategoryChild['url'];
                        $_urlKey2 = $_storeCategoryChild['url_key'];
                        ?>
                    
                        <li id="<?php echo $_urlKey2; ?>" data-category="category<?php echo $_id2; ?>" class="level level-top parent-<?php echo $_id; ?> parent nav-<?php echo $_urlKey2; ?>">
                            <a href="<?php echo $_url2; ?>" data-category="category<?php echo $_id2; ?>" class="level-top parent-<?php echo $_id2; ?>">
                                <span>
                                    <span>
                                        <?php echo $this->__($_helper->replaceCategoryName($_name2)); ?>
                                    </span>
                                </span>
                            </a>
                            
                            <?php
                            $_storeCategoriesChildChild = array ();
            
                            if ($_storeCategoryChild['child'] && count($_storeCategoryChild['child'] > 0)):
                                $_storeCategoriesChildChild = $_storeCategoryChild['child'];
                            endif;
                            ?>
                            <?php if (count($_storeCategoriesChildChild) > 0): ?>
                                <ul class="level-hover 0">
                                    <li class="">
                                        <div class="left-columns">
                                            <h2><?php echo $_name2; ?></h2>
                                            <div class="view-box">
                                                <ul>
                                                    <?php foreach ($_storeCategoriesChildChild as $_storeCategoryChildChild): ?>
                                                        <?php
                                                        $_id3 = $_storeCategoryChildChild['id'];
                                                        $_name3 = $_storeCategoryChildChild['name'];
                                                        $_url3 = $_storeCategoryChildChild['url'];
                                                        $_urlKey3 = $_storeCategoryChildChild['url_key'];
                                                        ?>
                                                    
                                                        <li class="nav-<?php echo $_urlKey3; ?>">
                                                            <a href="<?php echo $_url3; ?>" class="<?php echo $_urlKey3; ?>">
                                                                <span>
                                                                    <?php echo $_name3; ?>
                                                                </span>
                                                            </a>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </div>
                                        </div>
                                        
                                        <div class="right-columns">
                                            <?php echo $_storeCategoryChild['megamenu_staticblock']; ?>
                                            
                                            <div class="megamenu-product">
                                                <a href="#" class="megamenu-image">
                                                    <img alt="" src="<?php echo $_storeCategoryChild['megamenu_image']; ?>">
                                                </a>
                                            </div>
                                        </div>
                                        
                                        <div class="clear"></div>
                                        
                                        <a class="browse-all" href="<?php echo $_url2; ?>">Browse All</a>
                                    </li>
                                </ul>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('giftideas_menu')->toHtml(); ?>

<script>
    jQuery(document).ready(function() {
        jQuery(".giftideas").mouseover(function() {
            jQuery(".nav-10").addClass("hover");
            jQuery(".nav-10>a").addClass("color_a");
            jQuery(".gift-menu-wrapp").show();
        });	
  
        jQuery(".giftideas").mouseleave(function() {
            jQuery(".nav-10").removeClass("hover");
            jQuery(".nav-10>a").removeClass("color_a");
            jQuery(".gift-menu-wrapp").hide();
        });
  
        jQuery(".gift-menu-wrapp").mouseover(function() {
            jQuery(".gift-menu-wrapp").show();
            jQuery(".parent-10").addClass("over");
        });
    
        jQuery(".gift-menu-wrapp").mouseleave(function() {
            jQuery(".gift-menu-wrapp").hide();
            jQuery(".parent-10").removeClass("over");
        });
    });
</script>
