<?php
/**
 *
 *
 * @category   AW
 * @package    AW_Affiliate
 * @version    1.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>

<div class="generate-link fieldset">
    <h2 class="legend"><?php echo $this->__("Tracking Link for Products"); ?></h2>
    <!-- <div class="row"><?php //echo $this->getInputTitleField();?></div> -->
    <div class="row"><?php echo $this->getTrafficSourceLinkField();?></div>
    <div class="row"><?php echo $this->getWidthCampaignField();?></div>
    <!-- <div class="row"><?php echo $this->getNumberOfProductsField();?></div> -->
    <div class="row"><?php echo $this->getCategoryOfProductsField();?></div>
    <div class="row" id="category_option"><?php echo $this->getCategoriesField();?></div>
    <div class="row">
        <div id="preview">
            <iframe src="#" scrolling="no" frameborder="0"id="frameDemo"></iframe>   
        </div>
    </div>
            <div class="button-set">
                <button class="button" id="generate-link-btn">
                    <span><span><?php echo $this->__('Generate Link'); ?></span></span>
                </button>
            </div>
            <div class="row"><?php echo $this->getResultLinkField();?></div>
        </div>

<script type="text/javascript">
    
    var campaignId = '<?php echo $this->getCampaignId();?>';
    var affiliateId = '<?php echo $this->getAffiliateId();?>';
    var widthToGenerate = jQuery('select[name=width_to_generate] option:selected').val();
    var categoryToGenerate = jQuery('input[name=category_to_generate]:checked').val();
    var trafficSourceGenerate = jQuery('input[name=traffic_source_generate]').val();
    var categoryOptionToGenerate = null;
    var storeId = '<?php echo Mage::app()->getStore()->getStoreId();?>';

    var config = {
        url: '<?php echo $this->getUrlProductsScriptRequest();?>',
        msg: {'generateLink' : '<?php echo $this->__('Link generation...');?>'},
        cat: categoryToGenerate,
        catOpt: categoryOptionToGenerate,
        wh: widthToGenerate,
        storeId: storeId
    };
    jQuery('#category_option').hide();

    if(widthToGenerate != ''){
        var WH = widthToGenerate.split('x');
        jQuery('#frameDemo').css({'width': parseInt(WH[0])+10+'px', 'height' : parseInt(WH[1])+10+'px'});
    }

    jQuery('select[name=width_to_generate]').change(function() {      
        var _x = jQuery(this).val();
        widthToGenerate = _x;
        var WH = _x.split('x');
        jQuery('#frameDemo').css({'width': WH[0]+'px', 'height' : WH[1]+'px'});
    });

    jQuery('input[name=category_to_generate]').bind('keyup keydown blur change',function(){
        categoryToGenerate = parseInt(jQuery(this).val());
        if(categoryToGenerate == 3){
            jQuery('#category_option').show();
        }else{
            jQuery('#category_option').hide();
        }
    });

    jQuery('select[name=categories_to_generate]').change(function() {
        categoryOptionToGenerate = parseInt(jQuery(this).val());
    });

    jQuery('input[name=traffic_source_generate]').bind('keyup keydown blur change',function(){
        trafficSourceGenerate = jQuery(this).val();
    });

    jQuery(':input').change(function(){
        config["url"] = '<?php echo $this->getUrlProductsScriptRequest();?>';
        config["cat"] = categoryToGenerate;
        config["catOpt"] = categoryOptionToGenerate;
        config["wh"]  = widthToGenerate;
        config["storeId"] = storeId;
        
        jQuery('#frameDemo').attr('src', '<?php echo Mage::getBaseUrl();?>affiliate/customer_affiliate/productsScript/campaign_id/'+campaignId+'/affiliate_id/'+affiliateId+'/traffic_source_generate/'+trafficSourceGenerate+'/width_to_generate/'+widthToGenerate+'/category_to_generate/'+categoryToGenerate+'/store_id/'+storeId+'/category_option_to_generate/'+categoryOptionToGenerate);

        AWGenerateLinkProducts.initialize(config);
    });

    jQuery('#frameDemo').attr('src', '<?php echo Mage::getBaseUrl();?>affiliate/customer_affiliate/productsScript/campaign_id/'+campaignId+'/affiliate_id/'+affiliateId+'/traffic_source_generate/'+trafficSourceGenerate+'/width_to_generate/'+widthToGenerate+'/category_to_generate/'+categoryToGenerate+'/store_id/'+storeId+'/category_option_to_generate/'+categoryOptionToGenerate);
    
    AWGenerateLinkProducts.initialize(config);

/*function requestAffiliate(categoryToGenerate)
{
    jQuery.ajax({
        type: "POST",
        url: '<?php echo $this->getUrlProductsToRequest();?>',
        dataType: 'json',
        data: 'categoryToGenerate='+categoryToGenerate+'&traffic_source_generate='+trafficSourceGenerate
    }).done(function( response ) {
       
        if(response.error == 0)
        {
            var list ='';
            jQuery.each( response.result, function( key, value ) {
                list += '<div class="preview-item">' + value.a + '<p class="item-price"><span class="price">'+value.price+'</span></p></div>';
            });
            jQuery('#preview_item_list').html(list);
        }else{

        }
    }).fail(function(response) {
console.log('fail');        
    });
} */   

    
</script>