<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.6.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>


<div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<div class="aw-points-referral">
	<div style="padding:5px;">
		<p>
		<?php echo $this->__("You can get Bilna Credit by sending invitation to your friends and relatives. Your credit will be added only after you had transaction on Bilna.com.");?> <a href="http://www.bilna.com/bilna-credits" style="font-weight: bold; color:#ff5719;text-decoration:none;"><?php echo $this->__("Click here");?></a> <?php echo $this->__("for more information on Bilna Credit.");?>
		</p>
	</div>
   <span style="font-size:15px;padding-left: 5px;"><?php echo Mage::helper('points')->__('Use this link to share your invitation:'); ?></span><br/>
   <div style="margin: 0 auto;">
	<a onclick="window.location.href='<?php echo $this->getInvitationFormUrl(); ?>'" target="_blank">
    	<input style="padding:20px;" type="image" onmouseover="this.src='http://assets.bilna.com/media/wysiwyg/landing/send-invitation-on.png'" onmouseout="this.src='http://assets.bilna.com/media/wysiwyg/landing/send-invitation.png'" src="http://assets.bilna.com/media/wysiwyg/landing/send-invitation.png" name="button" id="button" value="">
    </a>
    <a href="http://www.twitter.com/share?text=Ayo+belanja+di+Bilna.com,+online+baby+shop+terbesar+di+Indonesia&amp;url=<?php echo $this->tinyurl(Mage::helper('points')->getInvitationLink()); ?>&amp;via=bilnaID" target="_blank">
    	<input style="padding:20px;" type="image" onmouseover="this.src='http://assets.bilna.com/media/wysiwyg/landing/son-twitter-on2.png'" onmouseout="this.src='http://assets.bilna.com/media/wysiwyg/landing/son-twitter-normal2.png'" src="http://assets.bilna.com/media/wysiwyg/landing/son-twitter-normal2.png" name="button" id="button" value="">
    </a>
    <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->tinyurl(Mage::helper('points')->getInvitationLink()); ?>" target="_blank">
    	<input style="padding:20px;" type="image" onmouseover="this.src='http://assets.bilna.com/media/wysiwyg/landing/son-fb-on2.png'" onmouseout="this.src='http://assets.bilna.com/media/wysiwyg/landing/son-fb-nomal2.png'" src="http://assets.bilna.com/media/wysiwyg/landing/son-fb-nomal2.png" name="button" id="button" value="">
    </a>
	</div>
</div>
<br />
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if ($this->hasInvitees()): ?>  
    <fieldset>      
        <table class="data-table" id="invitelist-table">
            <thead>
                <tr>
                    <th style="background:#9dca33; border-right:1px solid #FFF; color:#FFF; font-weight:bold;text-align:center;font-size:16px;"><?php echo $this->__('E-mail') ?></th>
                    <th style="background:#9dca33; border-right:1px solid #FFF; color:#FFF; font-weight:bold;text-align:center;font-size:16px;"><?php echo $this->__('Status') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->getCollection() as $item): ?>
                    <tr>
                        <td style="border-right:1px solid #FFF;">
                            <span class="nobr"><?php echo $item->getEmail() ?></span>
                        </td>
                        <td>
                            <span class="nobr"><?php echo $item->getStatus() ?></span>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('invitelist-table')</script>            
    </fieldset>
<?php else: ?>
    <p><?php echo $this->__("You haven't sent any invitation yet") ?></p>
<?php endif ?>


<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getBackUrl(); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
