<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Demo: Effortless jQuery Floating Back-To-Top Script V2 | TypicalWhiner.com</title>

<!-- efforless script below -->
<script type="text/javascript">
	jQuery(document).ready(function(){
		var pxShow = 20;//height on which the button will show
		var slideUpTime = 500;//how slow/fast you want the button to show
		var slideDownTime = 500;//how slow/fast you want the button to hide
		var scrollSpeed = 400;//how slow/fast you want the button to scroll to top. can be a value, 'slow', 'normal' or 'fast'
		jQuery(window).scroll(function(){
			if(jQuery(window).scrollTop() >= pxShow){
				jQuery("#backtotop").slideDown(slideDownTime);
			}else{
				jQuery("#backtotop").slideUp(slideUpTime);
			}
		});
		 
		jQuery('#backtotop a').click(function(){
			jQuery('html, body').animate({scrollTop:0}, scrollSpeed); 
			return false; 
		}); 
	});
</script>
</head>
<body>
<div class="clrb"></div>
<div id="backtotop"><a href="#">Back to</br>Top ▲</a></div>
</body>
</html>
