<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.3.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<?php
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
 
$collection = $this->getCollection();

if ($this->getPosition() == AW_Autorelated_Model_Source_Position::INSTEAD_NATIVE_RELATED_BLOCK) {

    $this->iterateBlock();

    if ($collection && $collection->getSize()) {
        $this->markAsShowed();
    } elseif ($this->showNativeBlock()) {
        echo $this->getParent()->getChildHtml('catalog-product-related');
    }
}
?>
<?php if ($collection && $collection->getSize()) : ?>
    <?php if (Mage::helper('awautorelated')->checkVersion('1.4')): ?>
        <div class="block block-related aw-arp-block aw-arp-block-<?php echo $this->getData('id') ?>">
            <hr/>
            <div class="block-title">
                <span><?php echo $this->htmlEscape($this->getData('name')) ?></span>
            </div>
            <div class="block-content aw-arp-block-content">
            <?php else: ?>
                <div class="box base-mini mini-related-items aw-arp-block aw-arp-block-<?php echo $this->getData('id') ?>">
                    <div class="head">
                        <h4><?php echo $this->htmlEscape($this->getData('name')) ?></h4>
                    </div>
                    <div class="content aw-arp-block-content">
                    <?php endif; ?>
                    <ul>
                        <?php foreach ($collection as $product) : ?>
                            <li class="aw-arp-item">
								<div class="top_thumb_list_product">
                                    <a href="<?php echo $abstractBlock->getProductUrl($product) ?>"><img class="lazy" data-src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(152) ?>" alt="<?php echo $this->htmlEscape($product->getName()) ?>" width="75" height="75" /></a>
								</div>
                                <div class="aw-arp-item-right">
                                    <div class="aw-arp-product-name-wrap">
                                        <a class="aw-arp-product-name" href="<?php echo $abstractBlock->getProductUrl($product) ?>"><?php echo $this->htmlEscape($product->getName()) ?></a>
                                    </div>
                                    <?php echo $abstractBlock->getPriceHtml($product, true, '-related') ?>
                                    <?php echo $abstractBlock->getReviewsSummaryHtml($product, 'short')?>
                                </div>
								<div class="bottom_thumb_list_product">
									<div class="aw-arp-addtocart">
									<?php if ($product->isSaleable()) : ?>
										<p>
										   <?php if(!$this->isLocationLink($product)): ?>
												<a class="link-cart" href="<?php echo $abstractBlock->getAddToCartUrl($product) ?>"><i class="fa fa-cart-plus"></i><?php echo $this->__('Tambah ke troli') ?></a>
											<?php else : ?>
												<a class="link-cart" href="javascript:setLocation('<?php echo $abstractBlock->getAddToCartUrl($product) ?>');"><i class="fa fa-cart-plus"></i><?php echo $this->__('Tambah ke troli') ?></a>                                            
											<?php endif; ?>                                       
										</p>
									</div>
								</div>
                                <?php else : ?>
                                    <p class="availability out-of-stock"><span><a href="<?php echo $abstractBlock->getProductUrl($product) ?>"><?php echo $this->__('Kabari bila tersedia') ?></a></span></p>
                                <?php endif ?>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
