<?php
/**
 * Magento Enterprise Edition
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    design
 * @package     enterprise_rtb
 * @copyright   Copyright (c) 2013 Guidance Solutions (http://www.guidance.com)
 *
 */
?>
<?php $child = $this->getData('child'); ?>
<?php $name = ($child->getData('shortname'))?$child->getData('shortname'):$child->getData('name') ?>
<li>
    <div>
        <div class="left-columns">
            <h2><?php echo $name ?></h2>
            <div class="view-box">
                <?php
                $children = $child->getChildren();
                $counter = 0;
                $limCounter = ceil($children->count()/4);
                $catCounter =$children->count();
                ?>
                <?php foreach ($children as $submenu): ?>
                    <?php if($counter == 0):?>
                        <div class="three columns alpha">
                            <div class="column inside">
                    <?php endif;?>
                    <?php if($counter % $limCounter == 0 && $counter != 0 && $counter != ($limCounter*2)):?>
                            </div>
                            <div class="column inside">
                    <?php endif;?>
                    <?php if($counter == ($limCounter*2)):?>
                        </div>
                        </div>
                        <div class="three columns omega">
                            <div class="column inside">
                    <?php endif;?>
                    <a href="<?php echo $submenu->getUrl()?>">
                        <span>
                            <?php echo $this->escapeHtml($submenu->getName())?>
                        </span>
                    </a>
                    <?php if($counter == $catCounter-1):?>
                        </div>
                        </div>
                    <?php endif;?>
                    <?php $counter++;?>
                <?php endforeach; ?>
                <div class="clear"></div>
            </div>
            <a href="<?php echo $child->getUrl()?>" class="browse-all">
                <?php echo $this->__('BROWSE ALL')?> <?php echo strtoupper($name) ?>
            </a>
            <div class="devider"></div>
        </div>
        <div class="right-columns">
            <?php $productData = $child->getFeaturedProduct(); ?>
            <?php if($productData): ?>
                <div>
                	<?php 
                		$product =  Mage::getModel('catalog/product')->load($productData['product_id']); 
	                	$_imageUrl =  Mage::helper('catalog/image')->init($product, 'small_image')->resize(200, 200);
                	?>
                    <?php if ($_imageUrl): ?>
                        <a href="<?php echo $product->getProductUrl(); ?>"
                           class="text-none image-cat">
                            <img src="<?php echo $_imageUrl; ?>"/>
                        </a>
                    <?php endif; ?>
                    <h4 class="feature-title"><?php echo $productData['product_name']; ?></h4>
                    <p><?php echo $productData['product_short_description']; ?></p>
                    <a class="button"
                       href="<?php echo $product->getProductUrl(); ?>">
                        <?php echo $this->__('Shop Now')?>
                    </a>
                </div>
            <?php else: ?>
                <?php echo $this->__('Featured Products Not Available')?>
            <?php endif;?>
        </div>
        <div class="clear"></div>
    </div>
</li>