<?php
/**
 * Magento Enterprise Edition
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    design
 * @package     enterprise_rtb
 * @copyright   Copyright (c) 2013 Guidance Solutions (http://www.guidance.com)
 *
 */
?>
<?php $child = $this->getData('child'); ?>
<?php $name = ($child->getData('shortname'))?$child->getData('shortname'):$child->getData('name') ?>
<li>
    <div class="left-columns">
        <h2><?php echo $name ?></h2>
        <div class="view-box">
            <?php
            $children = $child->getChildren();
            $counter = 0;
            $limCounter = ceil($children->count()/4);
            $catCounter =$children->count();
            ?>
            <ul>
            <?php foreach ($children as $submenu): ?>
                <li>
                	<a href="<?php echo $submenu->getUrl()?>"><span><?php echo $this->escapeHtml($submenu->getName())?></span></a>
                </li>
                <?php $counter++;?>
            <?php endforeach; ?>
            </ul>
            <ul class="added-menu">
	            <li><a href="#" class="link-bestseller"><?php echo $this->__('Best Seller')?></a></li>
        		<li><a href="#" class="link-whatsnew"><?php echo $this->__('Whats New?')?></a></li>
        		<li><a href="#" class="link-onsale"><?php echo $this->__('On Sale!')?></a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="devider"></div>
    </div>
    <div class="right-columns">
    	<div class="submenu popular-brand">
    		<span class="title"><?php echo $this->__('Popular Brands')?></span>
        	<ul>
        		<li><a href="#"><?php echo $this->__('MamyPoko')?></a></li>
        		<li><a href="#"><?php echo $this->__('Pampers')?></a></li>
        		<li><a href="#"><?php echo $this->__('Merries')?></a></li>
        		<li><a href="#"><?php echo $this->__('Nepia')?></a></li>
        		<li><a href="#"><?php echo $this->__('Huggies')?></a></li>
        		<li><a href="#"><?php echo $this->__('Ruparooz')?></a></li>
        		<li><a href="#"><?php echo $this->__('Okiedog')?></a></li>
        	</ul>
    	</div>
    	<div class="submenu our-choice">
    		<span class="title"><?php echo $this->__('Our Choice')?></span>
        	<ul>
        		<li><a href="#"><?php echo $this->__('MamyPoko')?></a></li>
        		<li><a href="#"><?php echo $this->__('Pampers')?></a></li>
        		<li><a href="#"><?php echo $this->__('Merries')?></a></li>
        		<li><a href="#"><?php echo $this->__('Nepia')?></a></li>
        		<li><a href="#"><?php echo $this->__('Huggies')?></a></li>
        		<li><a href="#"><?php echo $this->__('Ruparooz')?></a></li>
        		<li><a href="#"><?php echo $this->__('Okiedog')?></a></li>
        	</ul>
    	</div>
    	<div class="clear"></div>
    	<?php $productData = $child->getFeaturedProduct(); ?>
	    <?php if($productData): ?>
	        <div class="featured-product">
	        	<?php 
	        		$product =  Mage::getModel('catalog/product')->load($productData['product_id']); 
	            	$_imageUrl =  Mage::helper('catalog/image')->init($product, 'small_image')->resize(131, 192);
	        	?>
	            <?php if ($_imageUrl): ?>
	                <a href="<?php echo $product->getProductUrl(); ?>"
	                   class="featured-image">
	                    <img src="<?php echo $_imageUrl; ?>"/>
	                </a>
	            <?php endif; ?>
	        </div>
	    <?php else: ?>
	        <?php echo $this->__('Featured Products Not Available')?>
	    <?php endif;?>
    </div>
    <div class="clear"></div>
    <a href="<?php echo $child->getUrl()?>" class="browse-all"><?php echo $this->__('Browse All')?></a>
</li>