<?php
/**
 * Magento Enterprise Edition
 *
 * @author      Guidance Magento Team <magento@guidance.com>
 * @category    design
 * @package     enterprise_rtb
 * @copyright   Copyright (c) 2013 Guidance Solutions (http://www.guidance.com)
 *
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $menuTree = $this->getHtml('level-top') ?>
<?php if($menuTree): ?>
    <div class="nav-container container">
            <ul id="nav" class="nav">
                <?php
                $children = $this->addFeaturedProductData($menuTree->getChildren());
                $parentLevel = $menuTree->getLevel();
                $childLevel = is_null($parentLevel) ? 0 : $parentLevel + 1;
                $parentsCount = $children->count();
                $counter = 0;
                ?>
                <?php foreach ($children as $child): ?>
                    <?php
                    $outermostClassCode = '';
                    $outermostClass = $menuTree->getOutermostClass()." parent-".$counter;
                    ?>
                    <?php if ($childLevel == 0 && $outermostClass): ?>
                        <?php $outermostClassCode = ' class="' . $outermostClass . ' '. strtolower(str_replace(array('&',' '), "_", $child->getName())) .'" ';
                        $child->setClass($outermostClass); ?>
                    <?php endif; ?>
                    <li <?php echo $this->_getRenderedMenuItemAttributes($child)?>>
                            <a href="javascript:void(0)" <?php echo $outermostClassCode ?>>
                                <span><span><?php echo $this->escapeHtml($child->getName()) ?></span></span>
                            </a>
                            <?php if ($child->hasChildren()): ?>
                                <ul class="level-hover <?php echo $childLevel ." ".strtolower(str_replace(array('&',' '), "_", $child->getName()))."_hover";?>">
                                    <?php echo $this->getSubMenuHtml($child) ?>
                                </ul>
                            <?php endif; ?>
                    </li>
                    <?php $counter++;?>
                <?php endforeach; ?>
            </ul>
    </div>
<?php endif ?>