
<input type="hidden" id="3rdparty-type" value="cartsuccess"/>
<input type="hidden" id="3rdparty-value" value="<?php echo $this->getOrderId(); ?>" />

<style type="text/css">
    .wrapper_success_page{display:table;background:#4EC7DA;width:80%;color:#fff;font-family:arial;position:relative;margin:5%;padding:2%}.wrapper_success_page p{margin:0}.wrapper_success_page .col_left p:nth-of-type(1){font-size:23px;line-height:20px}.wrapper_success_page .col_left p:nth-of-type(2){font-size:67px;line-height:65px;border-bottom:6px dotted;margin:0 0 100px;display:table}.wrapper_success_page .col_left p:nth-of-type(3){font-size:21px}.wrapper_success_page .order_id{color:#403c0a}.wrapper_success_page .say_thanks{border-bottom:7px dotted;margin-top:150px;position:relative}.wrapper_success_page .say_thanks p{padding:0 0 0 10px;background:#4EC7DA;position:absolute;right:-6px;top:-10px}.wrapper_success_page .col_left{float:left;width:62%;padding:2% 5% 2% 2%;border-right:1px #fff solid}.wrapper_success_page .col_right{width:28%;float:left;margin-left:2%;height:200px}
</style>

<?php
if ($this->getOrderId()):
    if ($this->getCanViewOrder()):
        $orderNoLink = sprintf('<a href="%s" class="order_id">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()));
    else:
        $orderNoLink = sprintf('<a class="order_id">%s</a>', $this->escapeHtml($this->getOrderId()));
    endif;
endif;
?>

<div class="wrapper_success_page">
    <div class="col_left">
        <p><?php echo $this->__('THANK YOU FOR SHOPPING WITH'); ?></p>
        <p><?php echo $this->__('BILNA.COM'); ?></p>
        <p>
            <?php echo $this->__('Your order no is'); ?>: <?php echo $orderNoLink; ?>.
            <br/>
            
            <?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress'); ?>.
            <br/><br/>
            
            <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()): ?>
                <?php echo $this->__('Click'); ?> <a href="<?php echo $this->escapeHtml($this->getPrintUrl()); ?>"><?php echo $this->__('here'); ?></a> <?php echo $this->__('to print a copy of your order confirmation'); ?>.
            <?php endif; ?>
                
            <br/><br/>
            <?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()); ?>
        </p>
		
        <div class="say_thanks">
            <p><?php echo $this->__('Have a great day :)'); ?></p>
        </div>
    </div>
    
    <div class="col_right">
        <?php echo $this->getInstruction(); ?>
    </div>
</div>
<script type="text/javascript">
jQuery(document).ready(function () {    
    var ajaxURL = '<?php echo Mage::getUrl('',array('_secure'=>true));?>/ajaxrequest/data/retrieveconfirm2/';

    var data = {};
    data.orderId = '<?php echo $this->escapeHtml($this->getOrderId())?>';

    jQuery.ajax({
        type: "POST",
        url : ajaxURL,
        data: { data: data },
        success: function(data){
            response = jQuery.parseJSON(data);
            if(response.status == true){
                dataLayer.push({'customer': JSON.stringify(response.data.customer)});
                dataLayer.push( {'order': JSON.stringify(response.data.order)} );
                dataLayer.push({'event': 'salesConversionEvent'});
                
            }else{
                return false;
            }
        },
        error: function() {
            return false;
        }
    });
});
</script>