<?php $_helper = Mage::helper('megamenu'); ?>
<?php $_storeCategories = $_helper->getStoreCategories(); ?>

<?php if (count($_storeCategories) > 0): ?>
    <div class="nav-container-mobile">
        <ul>
            <?php $_currentMainCategory = $_helper->getCurrentMainCategory(); ?>
            <?php foreach ($_storeCategories as $_storeCategory): ?>
                <?php
                $_storeCategoryDisplay = ($_storeCategory->getId() == $_currentMainCategory) ? 'style="display:block;"' : '';
                $_storeCategoryClass = '';
                
                if ($_currentMainCategory != '' || !empty ($_currentMainCategory)):
                    if ($_storeCategory->getId() != $_currentMainCategory):
                        $_storeCategoryClass = 'inactive';
                    endif;
                endif;
                ?>
            
                <li class="cat-leveltop store-category <?php echo 'cat-leveltop-' . $_storeCategory->getId(); ?> <?php echo $_storeCategoryClass; ?>">
                    <a id="<?php echo $_storeCategory->getId(); ?>" class="categories <?php echo strtolower(str_replace(array ("&"," ","'"), "", $_storeCategory->getName())); ?>" href="<?php echo $_helper->getCategoryUrl($_storeCategory); ?>">
                        <?php echo $_storeCategory->getName(); ?>
                    </a>
                    <?php $_storeCategories2 = $_storeCategory->getChildrenCategories(); ?>
                    <?php if (count($_storeCategories2) > 0): ?>
                        <ul id="ul-<?php echo $_storeCategory->getId(); ?>" class="store-category-child category-child" <?php echo $_storeCategoryDisplay; ?>>
                            <?php foreach ($_storeCategories2 as $_storeCategory2): ?>
                                <li class="store-category2">
                                    <a id="<?php echo $_storeCategory2->getId(); ?>" parent="<?php echo $_storeCategory->getId(); ?>" class="subcategories" href="<?php echo $_helper->getCategoryUrl($_storeCategory2); ?>">
                                        <?php echo $_storeCategory2->getName(); ?>
                                    </a>
                                    <?php $_storeCategories3 = $_storeCategory2->getChildrenCategories(); ?>
                                    <?php if (count($_storeCategories3) > 0): ?>
                                        <ul id="ul-<?php echo $_storeCategory2->getId(); ?>" class="store-category2-child category-child">
                                            <?php foreach ($_storeCategories3 as $_storeCategory3): ?>
                                                <li class="store-category3">
                                                    <a class="subcategories" href="<?php echo $_helper->getCategoryUrl($_storeCategory3); ?>">
                                                        <?php echo $_storeCategory3->getName(); ?>
                                                    </a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>