<?php $_helper = Mage::helper('megamenu'); ?>
<?php $_storeCategories = $_helper->getStoreCategories(); ?>

<?php if (count($_storeCategories) > 0): ?>
    <div class="nav-container-mobile">
        <ul>
            <?php foreach ($_storeCategories as $_storeCategory): ?>
                <?php $_storeCategoryDisplay = ($_storeCategory->getId() == $_helper->getCurrentMainCategory()) ? 'style="display:block;"' : ''; ?>
                <li class="cat-leveltop store-category <?php echo 'cat-leveltop-' . $_storeCategory->getId(); ?>">
                    <a class="categories <?php echo strtolower(str_replace(array ("&"," ","'"), "", $_storeCategory->getName())); ?>" href="<?php echo $_helper->getCategoryUrl($_storeCategory); ?>">
                        <?php echo $_storeCategory->getName(); ?>
                    </a>
                    <?php $_storeCategories2 = $_storeCategory->getChildrenCategories(); ?>
                    <?php if (count($_storeCategories2) > 0): ?>
                        <ul class="store-category-child category-child" <?php echo $_storeCategoryDisplay; ?>>
                            <?php foreach ($_storeCategories2 as $_storeCategory2): ?>
                                <li class="store-category2">
                                    <a class="subcategories" href="<?php echo $_helper->getCategoryUrl($_storeCategory2); ?>">
                                        <?php echo $_storeCategory2->getName(); ?>
                                    </a>
                                    <?php $_storeCategories3 = $_storeCategory2->getChildrenCategories(); ?>
                                    <?php if (count($_storeCategories3) > 0): ?>
                                        <ul class="store-category2-child category-child">
                                            <?php foreach ($_storeCategories3 as $_storeCategory3): ?>
                                                <li class="store-category3">
                                                    <a class="subcategories" href="<?php echo $_helper->getCategoryUrl($_storeCategory3); ?>">
                                                        <?php echo $_storeCategory3->getName(); ?>
                                                    </a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<style type="text/css">
    .category-child {
        display: none;
    }
</style>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.store-category > a').live('click', function() {
            if (!jQuery(this).next().is(':visible')) {
                jQuery(this).next().show();
                jQuery(this).addClass('active');
                return false;
            }
            
            window.location.href = jQuery(this).attr('href');
        });
        
        jQuery('.store-category2 > a').live('click', function() {
            if (!jQuery(this).next().is(':visible')) {
                jQuery(this).next().show();
                jQuery(this).addClass('active');
                return false;
            }
            
            window.location.href = jQuery(this).attr('href');
        });
    });
</script>

<?php /*
<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>

<?php
$currCategoryId = NULL;

if (is_object(Mage::registry('current_category'))) {
    if (Mage::registry('current_category')->getParentId() == 2) {
        $currCategoryId = Mage::registry('current_category')->getId();
    }
}
?>

<div class="nav-container-mobile">
    <ul>
        <?php foreach ($_categories as $category): ?>
            <?php if ($category->getIsActive()): ?>
                <?php 
                // get all children
                if (Mage::helper('catalog/category_flat')->isEnabled()) {
                    $children = (array) $category->getChildrenNodes();
                    $childrenCount = count($children);
                }
                else {
                    $children = $category->getChildren();
                    $childrenCount = $children->count();
                }
                $hasChildren = ($children && $childrenCount);

                // select active children
                $activeChildren = array ();
                            
                foreach ($children as $child) {
                    if ($child->getIsActive()) {
                        $activeChildren[] = $child;
                    }
                }
                    
                $activeChildrenCount = count($activeChildren);
                $hasActiveChildren = ($activeChildrenCount > 0);
				
                ?>
				<?php //echo $currCategoryId."-".$category->getId(); ?>
                <li class="cat-leveltop <?php echo "cat-leveltop-".strtolower($category->getId()); ?> <?php echo ($hasActiveChildren)?('parent'):('')?> <?php echo ($currCategoryId==$category->getId())?('active-mobile-menu'):(''); ?>">
                    <?php $url = Mage::getModel("catalog/category")->load($category->getId())->getUrl(); ?>
                    <a class="categories <?php echo strtolower(str_replace(array ("&"," ","'"), "", $category->getName())); ?>" href="<?php echo $url ?>"><?php echo $category->getName(); ?></a>
                    <?php if ($hasActiveChildren): ?>
                        <ul class="cat-sub">
                            <li>
                                <div>
                                    <ul>
                                        <?php foreach ($activeChildren as $activeChild): ?>
                                            <?php if(strtolower($activeChild->getName())!='gift card'): ?>
                                                <li>
                                                    <?php $subsubcategories = $activeChild->getChildren() ?>
                                                    <?php
                                                    // select active children
                                                    $activeChildren2 = array ();
                                                    foreach ($subsubcategories as $child) {
                                                        if ($child->getIsActive()) {
                                                            $activeChildren2[] = $child;
                                                        }
                                                    }
                                                    
                                                    $activeChildrenCount2 = count($activeChildren2);
                                                    $hasActiveChildren2 = ($activeChildrenCount2 > 0);
                                                    ?>
                                                        
                                                    <?php $url = Mage::getModel("catalog/category")->load($activeChild->getId())->getUrl(); ?>
                                                    <a href="<?php echo $url; ?>" rel="<?php echo $url ?>" class="subcategories <?php echo strtolower(str_replace(array ("&"," ","'"), "", $activeChild->getName())); ?> <?php if ($hasActiveChildren2): ?> haschild<?php endif;?>"><?php echo ucwords(strtolower($activeChild->getName())); ?><?php if ($hasActiveChildren2): ?><span class="arrow"></span><?php endif;?></a>
                                                    <!--
                                                    <?php //if ($hasActiveChildren2): ?>
                                                        <div class="subsubcategories">
                                                            <ul>
                                                                <?php //foreach ($subsubcategories as $subsubcategory): ?>
                                                                    <li>
                                                                        <a href="<?php //echo $this->getCategoryUrl($subsubcategory); ?>"><?php //echo ucwords(strtolower($subsubcategory->getName())); ?></a>
                                                                    </li>
                                                                <?php //endforeach; ?>
                                                            </ul>
                                                        </div>
                                                    <?php //endif; ?>
													-->
                                                </li>
		                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    <?php endif; ?>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.cat-leveltop.parent a.categories').live('click', function() {
            if (!jQuery(this).next().is(':visible')) {
                jQuery(this).next().show();
                jQuery(this).addClass('active');
                return false;
            }
            
            window.location.href = jQuery(this).attr('rel');
        });
    });
</script>
*/ ?>