<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Afptc
 * @version    1.0.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<?php 
    $_product = $this->getProduct();    
    $_helper = $this->helper('catalog/output');
?>
 <div id="aw-afptc-popup" style='display:none'>
<form method="post" action="<?php echo $this->getPostUrl(); ?>" onsubmit="$('aw-afptc-accept').disabled = true">   
        <h2 class='aw-afptc-promo-message'><?php echo $this->__('The following item will be added to your cart'); ?></h2>
        <div>
            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2> 
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <div><?php echo $this->getPriceHtml($_product, true) ?></div>
            <div>            
                <button type="submit" title="<?php echo $this->__('Accept') ?>" id='aw-afptc-accept' class="button btn-cart"><span><span><?php echo $this->__('Accept') ?></span></span></button>
                <button type="button" title="<?php echo $this->__('Decline') ?>" id='aw-afptc-decline' class="button btn-cart"><span><span><?php echo $this->__('Decline') ?></span></span></button>
            </div>
            <?php if($this->getDoNotShowAllowed()): ?>
                <div>
                    <input type='checkbox' name='aw-afptc-decline-rule' id='aw-afptc-decline-rule'> 
                    <label for='aw-afptc-decline-rule'><?php echo $this->__('Do not show message box again'); ?></label>
                </div>
            <?php endif; ?>
            <input type='hidden' name='aw-afptc-session-key' value='<?php echo $this->getSessionKey(); ?>' />
        </div>  
</form>
 </div>

<div id="aw-afptc-overlay" style="display:none"></div> 
    
<script type='text/javascript'>    
     var awAfptcPopupInit = function() {         
         var awAfptcPopupObj = new awAfptcPopup({
           el: $('aw-afptc-popup'),
           overlay: $('aw-afptc-overlay'),
           decline: $('aw-afptc-decline'),
           declineCheck: $('aw-afptc-decline-rule'),           
           cookie: '<?php echo $this->getDeclineCookieName(); ?>'
       });
       awAfptcPopupObj.align();     
     }     
     <?php if($this->isAjax()): ?> 
        awAfptcPopupInit();
    <?php else: ?>        
         Event.observe(document, 'dom:loaded', function() {        
            awAfptcPopupInit();
         });        
    <?php endif; ?>    
</script>


