<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Clickcheckout
 * @version    1.1.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
	?>
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<title><?php echo $this->__('Terms and Conditions');?></title>
</head>
<ol class="checkout-agreements">
<?php foreach ($this->getAgreements() as $_a): ?>
        <div class="agreement-content"<?php /*echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')*/?>>
            <?php if ($_a->getIsHtml()):?>
                <h3><?php echo $_a->getCheckboxText() ?></h3>
                <?php echo $_a->getContent() ?>
            <?php else:?>
                <h3><?php echo nl2br($this->htmlEscape($_a->getCheckboxText())) ?></h3>
                <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
            <?php endif; ?>
            <br /><br />
        </div>
<?php endforeach ?>
</ol>

