<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code; ?>" style="display:none;">
    <div>
        <?php echo $this->getMethod()->getConfigData('message'); ?>
    </div>
    <li>
        <label for="klikbca_userid" class="required"><em>*</em><?php echo $this->__('User ID KlikBCA:'); ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('User ID KlikBCA:'); ?>" class="input-text required-entry" id="klikbca_user_id" name="payment[klikbca_user_id]" value="<?php echo $this->htmlEscape($this->getInfoData('klikbca_user_id')); ?>" />
        </span>
    </li>
</ul>
