<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Clickcheckout
 * @version    1.1.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
	?>
<?php $i=0?>
<?php foreach ($this->getAgreements() as $_a): ?>
    <?php $i++?>
    <input type="hidden" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" disabled="true"/>
<?php endforeach ?>
<?php if($i!=0): ?>
<input type="checkbox" id="aw_clickcheckout_agree" name="agreements" value="" onchange="setAgreements(this.checked,'<?php echo $i?>');"/><label for="aw_clickcheckout_agree"><?php echo $this->__('I agree with all')?> <a href="#" onclick="popWin('<?php echo $this->getUrl('awclickcheckout/oneclick/agreements') ?>', '', 'width=500,height=500,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><?php echo $this->__('terms and conditions')?></a></label>
<?php endif;?>

