<?php
$x = $this->productsScriptAction();
?>
<!DOCTYPE html>
<html>
<head>
    <title>Advertisement</title>
    <meta charset="utf-8">
</head>
<body marginwidth="0" marginheight="0" style="background-color:transparent; width: 100%; text-align: center;" topmargin="0" leftmargin="0">
    <div id="main4b414196be" style="width:468px;height:60px;border: 1px solid #20C5DF;position:relative;padding:0px;background-color:#fff;cursor:pointer;overflow:hidden;margin-left:auto;margin-right:auto;">
        <div id="cto_banner_content">
            <style>
                .thumb {
                    position: relative;
                    width: 62px;
                    height: 56px;
                    border: 1px solid #FF9B42;
                    padding: 0px;
                    margin: 1px;
                    float: left
                }
                .thumb img{
                    padding: 2px ;
                }
                .logo_banner{
                    padding: 0px 0px 0px 0px ;   
					background: none repeat scroll 0 0 #FFFAF4;
					display: block;
					clear: both;
					position: absolute;
					right: 0;
					width: 72px;
                }
				.logo_banner img{
					padding: 14px 0 12px;
                }
				
				.logo_banner img.fs-aff{
					padding: 2px 0;
                }
                .text {
                    display: none;
                    position: absolute;
                    left: 0;
                    bottom: 0;
                    width: 100%;
                    height: 100%;
                    background: #fff;
                    background: rgba(255,255,255,0.8);
                    text-align: center;
                    font-size: 9px;
                    color: #20C5DF;
                    font-weight: bold;
					font-family: helvetica, arial, 'sans-serif';
                }
                .thumb:hover .text {
                    display: block;
                }
				.buynow-aff {
					background: none repeat scroll 0 0 #ff7626;
					bottom: -9px;
					color: #FFF;
					display: block;
					font-size: 9px;
					padding: 3px 0;
					position: absolute;
					text-align: center;
					width: 100%;
				}
            </style>
            <div id="cto_banner_content" class="ad">
                <?php foreach($x as $row):?>
                <a href="<?php echo $row['a'];?>" alt="<?php echo $row['name'];?>" target="_blank">
                <div class="thumb">
                    <?php echo $row['img']; ?>
                    <span class="text">
                        <?php if( $row['price']['old_price'] > $row['price']['special_price'] ) : ?>
                        <p style="font-size: 9px;" class="none-text"></p>
                        <p style="font-size: 9px;" class="none-text"></p>
                        <?php else :?>
                        <p style="font-size: 9px;" class="none-text"></p>
						<p class="buynow-aff">Buy Now</p>
                    <?php endif;?>
                    </span>
                </div>
                </a>
                <?php endforeach; ?>
                <div class="logo_banner">
                    <img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" height="29px"/>
					<div style="clear: both;"></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>