<input type="hidden" id="3rdparty-type" value="cartsuccess"/>
<input type="hidden" id="3rdparty-value" value="<?php echo $this->getOrderId(); ?>" />
<input type="hidden" id="order-id" value="<?php echo $this->getOrderId(); ?>" />

<!--popup start-->
	<div class="success-form-popup hidden">
        <div class="popup">
            <form target="_blank" action="" method="post" id="event-form" name="event_form">
            <div class="blockbkg" id="bkg">
                <div class="cont" id="dlg">
                    <img id="gimmick-banner" src="" />
                    <div id="gimmick-tos" name="tos" style="-moz-appearance:textfield-multiline;-webkit-appearance:textarea;border:1px solid gray;font:medium-moz-fixed;font:-webkit-small-control;padding:2px;resize:none;overflow-y:scroll; height:167px; font-weight: bold; font-family: 'tin_doghouseregular';"></div>
                    <input id="event-data" name="data" type="hidden" value="" class="hidden" />
                    <div class="position_button"> 
                        <img src="http://assets.bilna.com/media/wysiwyg/gimmick-event/BUTTON-JOIN.jpg" class="ok" id="friso-form-submit" onclick="_frisoSave();jQuery('#event-form').submit();" />
                        <img src="http://assets.bilna.com/media/wysiwyg/gimmick-event/BUTTON-NOTJOIN.jpg" class="cancel" id="friso-cancel" />
                    </div>
                </div>
            </div>
            </form>
            <div style="clear: both;"></div>
        </div>
    </div>
<!--popup end-->
	
<style type="text/css">
    .wrapper_success_page{display:table;background:#4ec7da;width:80%;color:#fff;font-family:arial;position:relative;margin:5%;padding:2%}.wrapper_success_page p{margin:0}.wrapper_success_page .col_left p:nth-of-type(1){font-size:23px;line-height:20px}.wrapper_success_page .col_left p:nth-of-type(2){font-size:67px;line-height:65px;border-bottom:6px dotted;margin:0 0 100px;display:table}.wrapper_success_page .col_left p:nth-of-type(3){font-size:21px}.wrapper_success_page .order_id{color:#403c0a}.wrapper_success_page .say_thanks{border-bottom:7px dotted;margin-top:150px;position:relative}.wrapper_success_page .say_thanks p{padding:0 0 0 10px;background:#4EC7DA;position:absolute;right:-6px;top:-10px}.wrapper_success_page .col_left{float:left;width:62%;padding:2% 5% 2% 2%;border-right:1px #fff solid}.wrapper_success_page .col_right{width:28%;float:left;margin-left:2%;height:200px}
    .wrapper_failure_page{display:table;background:#da4e4e;width:80%;color:#fff;font-family:arial;position:relative;margin:5%;padding:2%}.wrapper_failure_page p{margin:0}.wrapper_failure_page .col_left p:nth-of-type(1){font-size:23px;line-height:20px}.wrapper_failure_page .col_left p:nth-of-type(2){font-size:67px;line-height:65px;border-bottom:6px dotted;margin:0 0 100px;display:table}.wrapper_failure_page .col_left p:nth-of-type(3){font-size:21px}.wrapper_failure_page .order_id{color:#403c0a}.wrapper_failure_page .say_thanks{border-bottom:7px dotted;margin-top:150px;position:relative}.wrapper_failure_page .say_thanks p{padding:0 0 0 10px;background:#da4e4e;position:absolute;right:-6px;top:-10px}.wrapper_failure_page .col_left{float:left;width:62%;padding:2% 5% 2% 2%;border-right:1px #fff solid}.wrapper_failure_page .col_right{width:28%;float:left;margin-left:2%;height:200px}
    .wrapper_challange_page{display:table;background:#dac54e;width:80%;color:#fff;font-family:arial;position:relative;margin:5%;padding:2%}.wrapper_challange_page p{margin:0}.wrapper_challange_page .col_left p:nth-of-type(1){font-size:23px;line-height:20px}.wrapper_challange_page .col_left p:nth-of-type(2){font-size:67px;line-height:65px;border-bottom:6px dotted;margin:0 0 100px;display:table}.wrapper_challange_page .col_left p:nth-of-type(3){font-size:21px}.wrapper_challange_page .order_id{color:#403c0a}.wrapper_challange_page .say_thanks{border-bottom:7px dotted;margin-top:150px;position:relative}.wrapper_challange_page .say_thanks p{padding:0 0 0 10px;background:#dac54e;position:absolute;right:-6px;top:-10px}.wrapper_challange_page .col_left{float:left;width:62%;padding:2% 5% 2% 2%;border-right:1px #fff solid}.wrapper_challange_page .col_right{width:28%;float:left;margin-left:2%;height:200px}
    .redirect_area{font-family:arial;display:block}.redirect_area .title_payment h3{color:#4ec7da;font-size:21px}.redirect_area .title_payment h3,.redirect_area .title_payment p{margin:3px 0}.redirect_area p{font-size:14px;color:#ffba5a}.redirect_area .redirect_button{margin:20px 0;background:#ffba5a;font-size:21px;color:#fff;border:0;padding:10px 20px}
    @media only screen and (max-width: 767px) {
        .wrapper_success_page .col_left p:nth-of-type(2){font-size:45px;}
    }
    @media only screen and (max-width: 483px) {
        .wrapper_success_page .col_left p:nth-of-type(2){font-size:35px;}
    }
    .success-form-popup {
        background: rgba(0,0,0,0.7);
        width: 100%;
        height:100%;
        padding-top: 5%;
        position: absolute;
        top: 0;
        left: 0;
        z-index: 999;
    }
    .success-form-popup .popup {
        width: 90%;
        max-width: 500px;
        margin: 5% auto;
        background: #fff;
        padding: 2%;
        border-radius:5px;
    }
    .success-form-popup .popup img#gimmick-banner {
        width: 100%;
    }
</style>

<?php
if ($this->getOrderId()):
    if ($this->getCanViewOrder()):
        $orderNoLink = sprintf('<a href="%s" class="order_id">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()));
    else:
        $orderNoLink = sprintf('<a class="order_id">%s</a>', $this->escapeHtml($this->getOrderId()));
    endif;
endif;
?>

<?php
$responsePage = '';
$redirectUrl = '';
$retrieveConfirm2 = true;
$vaNumbers = new stdClass();

if (in_array($this->getOrderPaymentCode(), $this->getPaymentMethodBankTransfer())):
    $responsePage = 'success';
elseif (in_array($this->getOrderPaymentCode(), $this->getPaymentMethodKlikpay())):
    $responsePage = 'success';
elseif (in_array($this->getOrderPaymentCode(), $this->getPaymentMethodCc())):
    $responseCharge = $this->getResponseCharge();
    $transactionStatus = $responseCharge->transaction_status;
    $fraudStatus = $responseCharge->fraud_status;
    
    if ($transactionStatus == 'capture'):
        if ($fraudStatus == 'accept'):
            $responsePage = 'success';
        elseif ($fraudStatus == 'challenge'):
            $responsePage = 'challenge';
        endif;
    elseif ($transactionStatus == 'challenge'):
        $responsePage = 'challenge';
    elseif ($transactionStatus == 'deny'):
        $responsePage = 'failure';
    else:
        $responsePage = 'challange';
    endif;
elseif (in_array($this->getOrderPaymentCode(), $this->getPaymentMethodVtdirect())):
    $responseCharge = $this->getResponseCharge();
    $responsePage = 'failure';

    if ($responseCharge->status_code == 201):
        if (isset ($responseCharge->redirect_url)):
            $responsePage = 'redirect';
            $redirectUrl = $responseCharge->redirect_url;
        endif;
    endif;
// If It's Virtual Account Transaction
elseif (in_array($this->getOrderPaymentCode(), $this->getPaymentMethodVA())):
    $responseCharge = $this->getResponseCharge();
    $responsePage = 'failure';

    if ($responseCharge->status_code == 201):
        $responsePage = 'virtualAccountSuccess';
        $vaNumbers = $responseCharge->va_numbers[0];
    endif;
else:
    $responsePage = 'failure';
endif;
?>

<?php if ($responsePage == 'success'): ?>
    <div class="wrapper_success_page">
        <div class="col_left"><p>
        <?php
        $custname = trim(Mage::helper('customer')->getCustomerName());
        if ($custname == "") {
            echo "Dear Customer,";
        }else{            
            echo "Dear " . $custname . ",";
        }
        ?></p></div>
        <div class="col_left">
        <!--p><?php //echo $this->__('THANK YOU FOR SHOPPING WITH'); ?></p-->
        <p><?php echo $this->__('Terima kasih Anda telah berbelanja di'); ?></p>          
            <!--p><?php //echo $this->__('BILNA.COM'); ?></p-->
            <p><?php echo $this->__('Bilna.com'); ?></p>
            <p>
                <!--<?php //echo $this->__('Your order no is'); ?>: <?php echo $orderNoLink; ?>.-->
                <?php echo $this->__('Nomor order Anda adalah'); ?>: <?php echo $orderNoLink; ?>.
                <br/>

                <!--<?php //echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress'); ?>.-->
                <?php echo $this->__(' Anda akan segera menerima email konfirmasi mengenai detail order dan link untuk cek status order.'); ?>
                <br/><br/>

                <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()): ?>
                    <!--<?php //echo $this->__('Click'); ?> <a href="<?php //echo $this->escapeHtml($this->getPrintUrl()); ?>"><?php //echo $this->__('here'); ?></a> <?php //echo $this->__('to print a copy of your order confirmation'); ?>.-->
                    <?php echo $this->__('Klik'); ?> <a href="<?php echo $this->escapeHtml($this->getPrintUrl()); ?>"><?php echo $this->__('di sini'); ?></a> <?php echo $this->__('untuk mencetak konfirmasi order.'); ?>                       
                <?php endif; ?>

                <br/><br/>
                <!--<?php //echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()); ?>-->
                <?php echo $this->__('Klik <a href="%s">di sini</a> untuk berbelanja kembali.', $this->getUrl()); ?>
                                       .
            </p>

            <div class="say_thanks">
                <!--p><?php //echo $this->__('Have a great day :)'); ?></p-->
                <p><?php echo $this->__('Selamat beraktifitas! :)'); ?></p>
            </div>
        </div>

        <?php if ($this->getInstruction()): ?>
            <div class="col_right">
                <?php echo $this->getInstruction(); ?>
            </div>
        <?php endif; ?>
    </div>
<?php elseif ($responsePage == 'challenge'): ?>
    <div class="wrapper_challange_page">
        <div class="col_left"><p><?php echo "Dear " . Mage::helper('customer')->getCustomerName() . ","; ?></p></div>
        <div class="col_left">
            <!--<p><?php //echo $this->__('THANK YOU FOR SHOPPING WITH'); ?></p>-->
            <p><?php echo $this->__('Terima kasih Anda telah berbelanja di'); ?></p>
            <!--<p><?php //echo $this->__('BILNA.COM'); ?></p>-->
            <p><?php echo $this->__('Bilna.com'); ?></p>                          
            <p>
                <!--<?php //echo $this->__('Your order no is'); ?>: <?php //echo $orderNoLink; ?>.-->
                <?php echo $this->__('Nomor order Anda adalah'); ?>: <?php echo $orderNoLink; ?>.
                <br/>
                <?php echo $this->__('Status pembayaran Anda akan kami informasikan segera.'); ?>
                <br/>
                
                <br/><br/>
                <!--<?php //echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()); ?>-->
                <?php echo $this->__('Klik <a href="%s">di sini</a> untuk berbelanja kembali.', $this->getUrl()); ?>
            </p>

            <div class="say_thanks">
                <!--p><?php //echo $this->__('Have a great day! :)'); ?></p-->
                <p><?php echo $this->__('Selamat beraktifitas! :)'); ?></p>                
            </div>
        </div>

        <div class="col_right"></div>
    </div>
<?php elseif ($responsePage == 'threedsecure' || $responsePage == 'redirect'): ?>
    <div class="redirect_area">
        <div class="title_payment">
            <br/>
            <h3><?php echo $this->__('Redirect page'); ?></h3>
        </div>

        <br/><br/><br/>

        <p><?php echo $this->__('This page will be redirect in 5 seconds.'); ?></p>

        <br/><br/>

        <button class="redirect_button" onclick="window.location='<?php echo $redirectUrl; ?>'">
            <?php echo $this->__('Redirect'); ?>
        </button>
    </div>
    <script type="text/javascript">
        setTimeout(function() {
            document.location = '<?php echo $redirectUrl; ?>';
        }, 5000);
    </script>

<?php elseif ($responsePage == 'virtualAccountSuccess'): ?>
    <div class="wrapper_success_page">
        <div class="col_left"><p>
                <?php
                $custname = trim(Mage::helper('customer')->getCustomerName());
                if ($custname == "") {
                    echo "Dear Customer,";
                }else{
                    echo "Dear " . $custname . ",";
                }
                ?></p></div>
        <div class="col_left">
            <!--p><?php //echo $this->__('THANK YOU FOR SHOPPING WITH'); ?></p-->
            <p><?php echo $this->__('Terima kasih Anda telah berbelanja di'); ?></p>
            <!--p><?php //echo $this->__('BILNA.COM'); ?></p-->
            <p><?php echo $this->__('Bilna.com'); ?></p>
            <p>
                <!--<?php //echo $this->__('Your order no is'); ?>: <?php echo $orderNoLink; ?>.-->
                <?php echo $this->__('Nomor order Anda adalah'); ?>: <?php echo $orderNoLink; ?>.
                <br/>

                <!--<?php //echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress'); ?>.-->
                <?php echo $this->__(' Anda akan segera menerima email konfirmasi mengenai detail order dan link untuk cek status order.'); ?>
                <br/><br/>

                <?php
                echo "<b>Please complete payment with transfer method to this ".$vaNumbers->bank." bank virtual account number:</b> ".$vaNumbers->va_number;
                echo "<br /><br />";
                echo "You have 24 hours to complete payment before this transaction expired <br />";
                ?>
                <br/><br/>

                <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()): ?>
                    <!--<?php //echo $this->__('Click'); ?> <a href="<?php //echo $this->escapeHtml($this->getPrintUrl()); ?>"><?php //echo $this->__('here'); ?></a> <?php //echo $this->__('to print a copy of your order confirmation'); ?>.-->
                    <?php echo $this->__('Klik'); ?> <a href="<?php echo $this->escapeHtml($this->getPrintUrl()); ?>"><?php echo $this->__('di sini'); ?></a> <?php echo $this->__('untuk mencetak konfirmasi order.'); ?>
                <?php endif; ?>

                <br/><br/>
                <!--<?php //echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()); ?>-->
                <?php echo $this->__('Klik <a href="%s">di sini</a> untuk berbelanja kembali.', $this->getUrl()); ?>
                .
            </p>

            <div class="say_thanks">
                <!--p><?php //echo $this->__('Have a great day :)'); ?></p-->
                <p><?php echo $this->__('Selamat beraktifitas! :)'); ?></p>
            </div>
        </div>

        <?php if ($this->getInstruction()): ?>
            <div class="col_right">
                <?php echo $this->getInstruction(); ?>
            </div>
        <?php endif; ?>
    </div>

<?php elseif ($responsePage == 'failure'): ?>
    <div class="wrapper_failure_page">
        <div class="col_left"><p><?php echo "Dear " . Mage::helper('customer')->getCustomerName() . ","; ?></p></div>
        <div class="col_left">
            <!--<p><?php //echo $this->__('THANK YOU FOR SHOPPING WITH'); ?></p>-->
            <p><?php echo $this->__('Terima kasih Anda telah berbelanja di'); ?></p>
            <!--<p><?php //echo $this->__('BILNA.COM'); ?></p>-->
            <p><?php echo $this->__('Bilna.com'); ?></p>
            <p>
                <!--<?php //echo $this->__('Your order no is'); ?>: <?php //echo $orderNoLink; ?>.-->
                <?php echo $this->__('Kami informasikan, transaksi pembayaran untuk nomor order'); ?> [<?php echo $orderNoLink; ?>] <?php echo $this->__('adalah gagal'); ?>.
                <br/>
                <?php echo $this->__('Mohon pastikan seluruh detail kartu kredit yang Anda masukan tepat.'); ?>
                <br/>
                
                <br/><br/>
                <!--<?php //echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()); ?>-->
                <?php echo $this->__('Klik <a href="%s">di sini</a> untuk berbelanja kembali.', $this->getUrl()); ?>
            </p>
		
            <div class="say_thanks">
                <!--p><?php //echo $this->__('Have a great day! :)'); ?></p-->
                <p><?php echo $this->__('Selamat beraktifitas! :)'); ?></p>
            </div>
        </div>	
        <div class="col_right"></div>
    </div>
<?php else: ?>
    <!-- do nothing -->
<?php endif; ?>

<?php $cartItems = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId()); ?>
<?php $skuCollection = array(); ?>
<?php $qtyCollection = array(); ?>
<?php $valueCollection = array(); ?>
<?php $idCollection = array(); ?>
<?php foreach($cartItems->getAllItems() as $cartItem) : ?>
    <?php $idCollection[] = $cartItem->getProductId(); ?>
    <?php $skuCollection[] = $cartItem->getSku(); ?>
    <?php $qtyCollection[] = number_format($cartItem->getData('qty_ordered'), 0, '', ''); ?>
    <?php $valueCollection[] = number_format($cartItem->getPrice(), 0, '', ''); ?>
    <?php $totalAll += ($cartItem->getData('qty_ordered') * $cartItem->getPrice()); ?>
<?php endforeach; ?>
<?php $idDisplay =  implode("','", $idCollection); ?>
<?php $skuDisplay =  implode("','", $skuCollection); ?>
<?php $qtyDisplay =  implode("','", $qtyCollection); ?>
<?php $valueDisplay =  implode("','", $valueCollection); ?>

<?php if ($retrieveConfirm2): ?>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            dataLayer.push({'ecomm_pagetype': 'thankyoupage'});
            dataLayer.push({'ecomm_prodid': ['<?php echo $skuDisplay; ?>']});
            dataLayer.push({'ecomm_totalvalue': '<?php echo $totalAll; ?>'});
            dataLayer.push({'orderid': '<?php echo $this->getOrderId(); ?>'});
            dataLayer.push({'productid': ['<?php echo $idDisplay; ?>']});
            dataLayer.push({'skuid': ['<?php echo $skuDisplay; ?>']});
            dataLayer.push({'prices': ['<?php echo $valueDisplay; ?>']});
            dataLayer.push({'quantities': ['<?php echo $qtyDisplay; ?>']});

    	    var ajaxURL = 'https://www.bilna.com/ajaxrequest/data/retrieveconfirm2/';

            var data = {};
            data.orderId = '<?php echo $this->escapeHtml($this->getOrderId()); ?>';

            jQuery.ajax({
                type: "POST",
                url : ajaxURL,
                data: {data: data},
                success: function(data) {
                    response = jQuery.parseJSON(data);

                    if (response.status == true) {
                    	dataLayer.push({'newcustomer': '0'} );
                    	dataLayer.push({'orderid': response.data.order.id} );

                    	dataLayer.push( {'productid': response.data.order.productIds} );
                    	dataLayer.push( {'prices': response.data.order.productPrices} );
                    	dataLayer.push( {'quantities': response.data.order.productQtys} );
                    	
                        dataLayer.push({'customer': response.data.customer});
                        dataLayer.push({'order': response.data.order});
                        dataLayer.push({'event': 'salesConversionEvent'});
                    }
                    else {
                        return false;
                    }
                },
                error: function() {
                    return false;
                }
            });
        });
    </script>
<?php endif; ?>
